// Code generated by ent, DO NOT EDIT.

package pagoaplicacion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the pagoaplicacion type in the database.
	Label = "pago_aplicacion"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreadoEn holds the string denoting the creado_en field in the database.
	FieldCreadoEn = "creado_en"
	// FieldPagoID holds the string denoting the pago_id field in the database.
	FieldPagoID = "pago_id"
	// FieldCargoID holds the string denoting the cargo_id field in the database.
	FieldCargoID = "cargo_id"
	// FieldMoneda holds the string denoting the moneda field in the database.
	FieldMoneda = "moneda"
	// FieldMontoAplicado holds the string denoting the monto_aplicado field in the database.
	FieldMontoAplicado = "monto_aplicado"
	// EdgePago holds the string denoting the pago edge name in mutations.
	EdgePago = "pago"
	// EdgeCargo holds the string denoting the cargo edge name in mutations.
	EdgeCargo = "cargo"
	// Table holds the table name of the pagoaplicacion in the database.
	Table = "pago_aplicaciones"
	// PagoTable is the table that holds the pago relation/edge.
	PagoTable = "pago_aplicaciones"
	// PagoInverseTable is the table name for the Pago entity.
	// It exists in this package in order to avoid circular dependency with the "pago" package.
	PagoInverseTable = "pagos"
	// PagoColumn is the table column denoting the pago relation/edge.
	PagoColumn = "pago_id"
	// CargoTable is the table that holds the cargo relation/edge.
	CargoTable = "pago_aplicaciones"
	// CargoInverseTable is the table name for the Cargo entity.
	// It exists in this package in order to avoid circular dependency with the "cargo" package.
	CargoInverseTable = "cargos"
	// CargoColumn is the table column denoting the cargo relation/edge.
	CargoColumn = "cargo_id"
)

// Columns holds all SQL columns for pagoaplicacion fields.
var Columns = []string{
	FieldID,
	FieldCreadoEn,
	FieldPagoID,
	FieldCargoID,
	FieldMoneda,
	FieldMontoAplicado,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreadoEn holds the default value on creation for the "creado_en" field.
	DefaultCreadoEn func() time.Time
	// DefaultMoneda holds the default value on creation for the "moneda" field.
	DefaultMoneda string
	// MonedaValidator is a validator for the "moneda" field. It is called by the builders before save.
	MonedaValidator func(string) error
	// DefaultMontoAplicado holds the default value on creation for the "monto_aplicado" field.
	DefaultMontoAplicado int64
)

// OrderOption defines the ordering options for the PagoAplicacion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreadoEn orders the results by the creado_en field.
func ByCreadoEn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreadoEn, opts...).ToFunc()
}

// ByPagoID orders the results by the pago_id field.
func ByPagoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPagoID, opts...).ToFunc()
}

// ByCargoID orders the results by the cargo_id field.
func ByCargoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCargoID, opts...).ToFunc()
}

// ByMoneda orders the results by the moneda field.
func ByMoneda(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMoneda, opts...).ToFunc()
}

// ByMontoAplicado orders the results by the monto_aplicado field.
func ByMontoAplicado(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMontoAplicado, opts...).ToFunc()
}

// ByPagoField orders the results by pago field.
func ByPagoField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPagoStep(), sql.OrderByField(field, opts...))
	}
}

// ByCargoField orders the results by cargo field.
func ByCargoField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCargoStep(), sql.OrderByField(field, opts...))
	}
}
func newPagoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PagoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PagoTable, PagoColumn),
	)
}
func newCargoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CargoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CargoTable, CargoColumn),
	)
}
