// Code generated by ent, DO NOT EDIT.

package clientetelefono

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the clientetelefono type in the database.
	Label = "cliente_telefono"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreadoEn holds the string denoting the creado_en field in the database.
	FieldCreadoEn = "creado_en"
	// FieldActualizadoEn holds the string denoting the actualizado_en field in the database.
	FieldActualizadoEn = "actualizado_en"
	// FieldClienteID holds the string denoting the cliente_id field in the database.
	FieldClienteID = "cliente_id"
	// FieldTelefono holds the string denoting the telefono field in the database.
	FieldTelefono = "telefono"
	// FieldEtiqueta holds the string denoting the etiqueta field in the database.
	FieldEtiqueta = "etiqueta"
	// FieldPrincipal holds the string denoting the principal field in the database.
	FieldPrincipal = "principal"
	// FieldWhatsapp holds the string denoting the whatsapp field in the database.
	FieldWhatsapp = "whatsapp"
	// EdgeCliente holds the string denoting the cliente edge name in mutations.
	EdgeCliente = "cliente"
	// Table holds the table name of the clientetelefono in the database.
	Table = "cliente_telefonos"
	// ClienteTable is the table that holds the cliente relation/edge.
	ClienteTable = "cliente_telefonos"
	// ClienteInverseTable is the table name for the Cliente entity.
	// It exists in this package in order to avoid circular dependency with the "cliente" package.
	ClienteInverseTable = "clientes"
	// ClienteColumn is the table column denoting the cliente relation/edge.
	ClienteColumn = "cliente_id"
)

// Columns holds all SQL columns for clientetelefono fields.
var Columns = []string{
	FieldID,
	FieldCreadoEn,
	FieldActualizadoEn,
	FieldClienteID,
	FieldTelefono,
	FieldEtiqueta,
	FieldPrincipal,
	FieldWhatsapp,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreadoEn holds the default value on creation for the "creado_en" field.
	DefaultCreadoEn func() time.Time
	// DefaultActualizadoEn holds the default value on creation for the "actualizado_en" field.
	DefaultActualizadoEn func() time.Time
	// UpdateDefaultActualizadoEn holds the default value on update for the "actualizado_en" field.
	UpdateDefaultActualizadoEn func() time.Time
	// TelefonoValidator is a validator for the "telefono" field. It is called by the builders before save.
	TelefonoValidator func(string) error
	// EtiquetaValidator is a validator for the "etiqueta" field. It is called by the builders before save.
	EtiquetaValidator func(string) error
	// DefaultPrincipal holds the default value on creation for the "principal" field.
	DefaultPrincipal bool
	// DefaultWhatsapp holds the default value on creation for the "whatsapp" field.
	DefaultWhatsapp bool
)

// OrderOption defines the ordering options for the ClienteTelefono queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreadoEn orders the results by the creado_en field.
func ByCreadoEn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreadoEn, opts...).ToFunc()
}

// ByActualizadoEn orders the results by the actualizado_en field.
func ByActualizadoEn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualizadoEn, opts...).ToFunc()
}

// ByClienteID orders the results by the cliente_id field.
func ByClienteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClienteID, opts...).ToFunc()
}

// ByTelefono orders the results by the telefono field.
func ByTelefono(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTelefono, opts...).ToFunc()
}

// ByEtiqueta orders the results by the etiqueta field.
func ByEtiqueta(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEtiqueta, opts...).ToFunc()
}

// ByPrincipal orders the results by the principal field.
func ByPrincipal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrincipal, opts...).ToFunc()
}

// ByWhatsapp orders the results by the whatsapp field.
func ByWhatsapp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWhatsapp, opts...).ToFunc()
}

// ByClienteField orders the results by cliente field.
func ByClienteField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClienteStep(), sql.OrderByField(field, opts...))
	}
}
func newClienteStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClienteInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ClienteTable, ClienteColumn),
	)
}
