// Code generated by ent, DO NOT EDIT.

package movimientocaja

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the movimientocaja type in the database.
	Label = "movimiento_caja"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreadoEn holds the string denoting the creado_en field in the database.
	FieldCreadoEn = "creado_en"
	// FieldEmpresaID holds the string denoting the empresa_id field in the database.
	FieldEmpresaID = "empresa_id"
	// FieldPagoID holds the string denoting the pago_id field in the database.
	FieldPagoID = "pago_id"
	// FieldGastoID holds the string denoting the gasto_id field in the database.
	FieldGastoID = "gasto_id"
	// FieldTipo holds the string denoting the tipo field in the database.
	FieldTipo = "tipo"
	// FieldConcepto holds the string denoting the concepto field in the database.
	FieldConcepto = "concepto"
	// FieldFechaMovimiento holds the string denoting the fecha_movimiento field in the database.
	FieldFechaMovimiento = "fecha_movimiento"
	// FieldMoneda holds the string denoting the moneda field in the database.
	FieldMoneda = "moneda"
	// FieldMonto holds the string denoting the monto field in the database.
	FieldMonto = "monto"
	// FieldMetodo holds the string denoting the metodo field in the database.
	FieldMetodo = "metodo"
	// FieldReferencia holds the string denoting the referencia field in the database.
	FieldReferencia = "referencia"
	// FieldObservaciones holds the string denoting the observaciones field in the database.
	FieldObservaciones = "observaciones"
	// EdgeEmpresa holds the string denoting the empresa edge name in mutations.
	EdgeEmpresa = "empresa"
	// EdgePago holds the string denoting the pago edge name in mutations.
	EdgePago = "pago"
	// EdgeGasto holds the string denoting the gasto edge name in mutations.
	EdgeGasto = "gasto"
	// Table holds the table name of the movimientocaja in the database.
	Table = "movimientos_caja"
	// EmpresaTable is the table that holds the empresa relation/edge.
	EmpresaTable = "movimientos_caja"
	// EmpresaInverseTable is the table name for the Empresa entity.
	// It exists in this package in order to avoid circular dependency with the "empresa" package.
	EmpresaInverseTable = "empresas"
	// EmpresaColumn is the table column denoting the empresa relation/edge.
	EmpresaColumn = "empresa_id"
	// PagoTable is the table that holds the pago relation/edge.
	PagoTable = "movimientos_caja"
	// PagoInverseTable is the table name for the Pago entity.
	// It exists in this package in order to avoid circular dependency with the "pago" package.
	PagoInverseTable = "pagos"
	// PagoColumn is the table column denoting the pago relation/edge.
	PagoColumn = "pago_id"
	// GastoTable is the table that holds the gasto relation/edge.
	GastoTable = "movimientos_caja"
	// GastoInverseTable is the table name for the Gasto entity.
	// It exists in this package in order to avoid circular dependency with the "gasto" package.
	GastoInverseTable = "gastos"
	// GastoColumn is the table column denoting the gasto relation/edge.
	GastoColumn = "gasto_id"
)

// Columns holds all SQL columns for movimientocaja fields.
var Columns = []string{
	FieldID,
	FieldCreadoEn,
	FieldEmpresaID,
	FieldPagoID,
	FieldGastoID,
	FieldTipo,
	FieldConcepto,
	FieldFechaMovimiento,
	FieldMoneda,
	FieldMonto,
	FieldMetodo,
	FieldReferencia,
	FieldObservaciones,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreadoEn holds the default value on creation for the "creado_en" field.
	DefaultCreadoEn func() time.Time
	// ConceptoValidator is a validator for the "concepto" field. It is called by the builders before save.
	ConceptoValidator func(string) error
	// DefaultMoneda holds the default value on creation for the "moneda" field.
	DefaultMoneda string
	// MonedaValidator is a validator for the "moneda" field. It is called by the builders before save.
	MonedaValidator func(string) error
	// DefaultMonto holds the default value on creation for the "monto" field.
	DefaultMonto int64
	// ReferenciaValidator is a validator for the "referencia" field. It is called by the builders before save.
	ReferenciaValidator func(string) error
	// ObservacionesValidator is a validator for the "observaciones" field. It is called by the builders before save.
	ObservacionesValidator func(string) error
)

// Tipo defines the type for the "tipo" enum field.
type Tipo string

// TipoIngreso is the default value of the Tipo enum.
const DefaultTipo = TipoIngreso

// Tipo values.
const (
	TipoIngreso Tipo = "ingreso"
	TipoEgreso  Tipo = "egreso"
	TipoAjuste  Tipo = "ajuste"
)

func (t Tipo) String() string {
	return string(t)
}

// TipoValidator is a validator for the "tipo" field enum values. It is called by the builders before save.
func TipoValidator(t Tipo) error {
	switch t {
	case TipoIngreso, TipoEgreso, TipoAjuste:
		return nil
	default:
		return fmt.Errorf("movimientocaja: invalid enum value for tipo field: %q", t)
	}
}

// Metodo defines the type for the "metodo" enum field.
type Metodo string

// MetodoEfectivo is the default value of the Metodo enum.
const DefaultMetodo = MetodoEfectivo

// Metodo values.
const (
	MetodoEfectivo      Metodo = "efectivo"
	MetodoTransferencia Metodo = "transferencia"
	MetodoYape          Metodo = "yape"
	MetodoPlin          Metodo = "plin"
	MetodoTarjeta       Metodo = "tarjeta"
	MetodoDeposito      Metodo = "deposito"
	MetodoOtro          Metodo = "otro"
)

func (m Metodo) String() string {
	return string(m)
}

// MetodoValidator is a validator for the "metodo" field enum values. It is called by the builders before save.
func MetodoValidator(m Metodo) error {
	switch m {
	case MetodoEfectivo, MetodoTransferencia, MetodoYape, MetodoPlin, MetodoTarjeta, MetodoDeposito, MetodoOtro:
		return nil
	default:
		return fmt.Errorf("movimientocaja: invalid enum value for metodo field: %q", m)
	}
}

// OrderOption defines the ordering options for the MovimientoCaja queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreadoEn orders the results by the creado_en field.
func ByCreadoEn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreadoEn, opts...).ToFunc()
}

// ByEmpresaID orders the results by the empresa_id field.
func ByEmpresaID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmpresaID, opts...).ToFunc()
}

// ByPagoID orders the results by the pago_id field.
func ByPagoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPagoID, opts...).ToFunc()
}

// ByGastoID orders the results by the gasto_id field.
func ByGastoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGastoID, opts...).ToFunc()
}

// ByTipo orders the results by the tipo field.
func ByTipo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTipo, opts...).ToFunc()
}

// ByConcepto orders the results by the concepto field.
func ByConcepto(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConcepto, opts...).ToFunc()
}

// ByFechaMovimiento orders the results by the fecha_movimiento field.
func ByFechaMovimiento(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFechaMovimiento, opts...).ToFunc()
}

// ByMoneda orders the results by the moneda field.
func ByMoneda(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMoneda, opts...).ToFunc()
}

// ByMonto orders the results by the monto field.
func ByMonto(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonto, opts...).ToFunc()
}

// ByMetodo orders the results by the metodo field.
func ByMetodo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetodo, opts...).ToFunc()
}

// ByReferencia orders the results by the referencia field.
func ByReferencia(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferencia, opts...).ToFunc()
}

// ByObservaciones orders the results by the observaciones field.
func ByObservaciones(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservaciones, opts...).ToFunc()
}

// ByEmpresaField orders the results by empresa field.
func ByEmpresaField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEmpresaStep(), sql.OrderByField(field, opts...))
	}
}

// ByPagoField orders the results by pago field.
func ByPagoField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPagoStep(), sql.OrderByField(field, opts...))
	}
}

// ByGastoField orders the results by gasto field.
func ByGastoField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGastoStep(), sql.OrderByField(field, opts...))
	}
}
func newEmpresaStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EmpresaInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EmpresaTable, EmpresaColumn),
	)
}
func newPagoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PagoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PagoTable, PagoColumn),
	)
}
func newGastoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GastoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GastoTable, GastoColumn),
	)
}
