// Code generated by ent, DO NOT EDIT.

package cargo

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the cargo type in the database.
	Label = "cargo"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreadoEn holds the string denoting the creado_en field in the database.
	FieldCreadoEn = "creado_en"
	// FieldContratoID holds the string denoting the contrato_id field in the database.
	FieldContratoID = "contrato_id"
	// FieldConcepto holds the string denoting the concepto field in the database.
	FieldConcepto = "concepto"
	// FieldDescripcion holds the string denoting the descripcion field in the database.
	FieldDescripcion = "descripcion"
	// FieldMoneda holds the string denoting the moneda field in the database.
	FieldMoneda = "moneda"
	// FieldPeriodoInicio holds the string denoting the periodo_inicio field in the database.
	FieldPeriodoInicio = "periodo_inicio"
	// FieldPeriodoFin holds the string denoting the periodo_fin field in the database.
	FieldPeriodoFin = "periodo_fin"
	// FieldFechaEmision holds the string denoting the fecha_emision field in the database.
	FieldFechaEmision = "fecha_emision"
	// FieldFechaVencimiento holds the string denoting the fecha_vencimiento field in the database.
	FieldFechaVencimiento = "fecha_vencimiento"
	// FieldMonto holds the string denoting the monto field in the database.
	FieldMonto = "monto"
	// FieldSaldo holds the string denoting the saldo field in the database.
	FieldSaldo = "saldo"
	// FieldEstado holds the string denoting the estado field in the database.
	FieldEstado = "estado"
	// FieldGeneradoAutomaticamente holds the string denoting the generado_automaticamente field in the database.
	FieldGeneradoAutomaticamente = "generado_automaticamente"
	// EdgeContrato holds the string denoting the contrato edge name in mutations.
	EdgeContrato = "contrato"
	// EdgeAplicacionesPago holds the string denoting the aplicaciones_pago edge name in mutations.
	EdgeAplicacionesPago = "aplicaciones_pago"
	// EdgeServicioMedicion holds the string denoting the servicio_medicion edge name in mutations.
	EdgeServicioMedicion = "servicio_medicion"
	// Table holds the table name of the cargo in the database.
	Table = "cargos"
	// ContratoTable is the table that holds the contrato relation/edge.
	ContratoTable = "cargos"
	// ContratoInverseTable is the table name for the Contrato entity.
	// It exists in this package in order to avoid circular dependency with the "contrato" package.
	ContratoInverseTable = "contratos"
	// ContratoColumn is the table column denoting the contrato relation/edge.
	ContratoColumn = "contrato_id"
	// AplicacionesPagoTable is the table that holds the aplicaciones_pago relation/edge.
	AplicacionesPagoTable = "pago_aplicaciones"
	// AplicacionesPagoInverseTable is the table name for the PagoAplicacion entity.
	// It exists in this package in order to avoid circular dependency with the "pagoaplicacion" package.
	AplicacionesPagoInverseTable = "pago_aplicaciones"
	// AplicacionesPagoColumn is the table column denoting the aplicaciones_pago relation/edge.
	AplicacionesPagoColumn = "cargo_id"
	// ServicioMedicionTable is the table that holds the servicio_medicion relation/edge.
	ServicioMedicionTable = "cargos"
	// ServicioMedicionInverseTable is the table name for the ServicioMedicion entity.
	// It exists in this package in order to avoid circular dependency with the "serviciomedicion" package.
	ServicioMedicionInverseTable = "servicio_mediciones"
	// ServicioMedicionColumn is the table column denoting the servicio_medicion relation/edge.
	ServicioMedicionColumn = "servicio_medicion_cargo"
)

// Columns holds all SQL columns for cargo fields.
var Columns = []string{
	FieldID,
	FieldCreadoEn,
	FieldContratoID,
	FieldConcepto,
	FieldDescripcion,
	FieldMoneda,
	FieldPeriodoInicio,
	FieldPeriodoFin,
	FieldFechaEmision,
	FieldFechaVencimiento,
	FieldMonto,
	FieldSaldo,
	FieldEstado,
	FieldGeneradoAutomaticamente,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "cargos"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"servicio_medicion_cargo",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreadoEn holds the default value on creation for the "creado_en" field.
	DefaultCreadoEn func() time.Time
	// DescripcionValidator is a validator for the "descripcion" field. It is called by the builders before save.
	DescripcionValidator func(string) error
	// DefaultMoneda holds the default value on creation for the "moneda" field.
	DefaultMoneda string
	// MonedaValidator is a validator for the "moneda" field. It is called by the builders before save.
	MonedaValidator func(string) error
	// DefaultMonto holds the default value on creation for the "monto" field.
	DefaultMonto int64
	// DefaultSaldo holds the default value on creation for the "saldo" field.
	DefaultSaldo int64
	// DefaultGeneradoAutomaticamente holds the default value on creation for the "generado_automaticamente" field.
	DefaultGeneradoAutomaticamente bool
)

// Concepto defines the type for the "concepto" enum field.
type Concepto string

// ConceptoRenta is the default value of the Concepto enum.
const DefaultConcepto = ConceptoRenta

// Concepto values.
const (
	ConceptoRenta         Concepto = "renta"
	ConceptoDeposito      Concepto = "deposito"
	ConceptoAgua          Concepto = "agua"
	ConceptoLuz           Concepto = "luz"
	ConceptoInternet      Concepto = "internet"
	ConceptoMantenimiento Concepto = "mantenimiento"
	ConceptoMora          Concepto = "mora"
	ConceptoOtro          Concepto = "otro"
)

func (c Concepto) String() string {
	return string(c)
}

// ConceptoValidator is a validator for the "concepto" field enum values. It is called by the builders before save.
func ConceptoValidator(c Concepto) error {
	switch c {
	case ConceptoRenta, ConceptoDeposito, ConceptoAgua, ConceptoLuz, ConceptoInternet, ConceptoMantenimiento, ConceptoMora, ConceptoOtro:
		return nil
	default:
		return fmt.Errorf("cargo: invalid enum value for concepto field: %q", c)
	}
}

// Estado defines the type for the "estado" enum field.
type Estado string

// EstadoPendiente is the default value of the Estado enum.
const DefaultEstado = EstadoPendiente

// Estado values.
const (
	EstadoPendiente Estado = "pendiente"
	EstadoParcial   Estado = "parcial"
	EstadoPagado    Estado = "pagado"
	EstadoVencido   Estado = "vencido"
	EstadoAnulado   Estado = "anulado"
)

func (e Estado) String() string {
	return string(e)
}

// EstadoValidator is a validator for the "estado" field enum values. It is called by the builders before save.
func EstadoValidator(e Estado) error {
	switch e {
	case EstadoPendiente, EstadoParcial, EstadoPagado, EstadoVencido, EstadoAnulado:
		return nil
	default:
		return fmt.Errorf("cargo: invalid enum value for estado field: %q", e)
	}
}

// OrderOption defines the ordering options for the Cargo queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreadoEn orders the results by the creado_en field.
func ByCreadoEn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreadoEn, opts...).ToFunc()
}

// ByContratoID orders the results by the contrato_id field.
func ByContratoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContratoID, opts...).ToFunc()
}

// ByConcepto orders the results by the concepto field.
func ByConcepto(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConcepto, opts...).ToFunc()
}

// ByDescripcion orders the results by the descripcion field.
func ByDescripcion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescripcion, opts...).ToFunc()
}

// ByMoneda orders the results by the moneda field.
func ByMoneda(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMoneda, opts...).ToFunc()
}

// ByPeriodoInicio orders the results by the periodo_inicio field.
func ByPeriodoInicio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodoInicio, opts...).ToFunc()
}

// ByPeriodoFin orders the results by the periodo_fin field.
func ByPeriodoFin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodoFin, opts...).ToFunc()
}

// ByFechaEmision orders the results by the fecha_emision field.
func ByFechaEmision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFechaEmision, opts...).ToFunc()
}

// ByFechaVencimiento orders the results by the fecha_vencimiento field.
func ByFechaVencimiento(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFechaVencimiento, opts...).ToFunc()
}

// ByMonto orders the results by the monto field.
func ByMonto(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonto, opts...).ToFunc()
}

// BySaldo orders the results by the saldo field.
func BySaldo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSaldo, opts...).ToFunc()
}

// ByEstado orders the results by the estado field.
func ByEstado(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstado, opts...).ToFunc()
}

// ByGeneradoAutomaticamente orders the results by the generado_automaticamente field.
func ByGeneradoAutomaticamente(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGeneradoAutomaticamente, opts...).ToFunc()
}

// ByContratoField orders the results by contrato field.
func ByContratoField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newContratoStep(), sql.OrderByField(field, opts...))
	}
}

// ByAplicacionesPagoCount orders the results by aplicaciones_pago count.
func ByAplicacionesPagoCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAplicacionesPagoStep(), opts...)
	}
}

// ByAplicacionesPago orders the results by aplicaciones_pago terms.
func ByAplicacionesPago(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAplicacionesPagoStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByServicioMedicionField orders the results by servicio_medicion field.
func ByServicioMedicionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newServicioMedicionStep(), sql.OrderByField(field, opts...))
	}
}
func newContratoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ContratoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ContratoTable, ContratoColumn),
	)
}
func newAplicacionesPagoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AplicacionesPagoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AplicacionesPagoTable, AplicacionesPagoColumn),
	)
}
func newServicioMedicionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ServicioMedicionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, ServicioMedicionTable, ServicioMedicionColumn),
	)
}
