// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rentals-go/ent/asistencia"
	"rentals-go/ent/empresa"
	"rentals-go/ent/usuario"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AsistenciaCreate is the builder for creating a Asistencia entity.
type AsistenciaCreate struct {
	config
	mutation *AsistenciaMutation
	hooks    []Hook
}

// SetCreadoEn sets the "creado_en" field.
func (_c *AsistenciaCreate) SetCreadoEn(v time.Time) *AsistenciaCreate {
	_c.mutation.SetCreadoEn(v)
	return _c
}

// SetNillableCreadoEn sets the "creado_en" field if the given value is not nil.
func (_c *AsistenciaCreate) SetNillableCreadoEn(v *time.Time) *AsistenciaCreate {
	if v != nil {
		_c.SetCreadoEn(*v)
	}
	return _c
}

// SetEmpresaID sets the "empresa_id" field.
func (_c *AsistenciaCreate) SetEmpresaID(v int) *AsistenciaCreate {
	_c.mutation.SetEmpresaID(v)
	return _c
}

// SetUsuarioID sets the "usuario_id" field.
func (_c *AsistenciaCreate) SetUsuarioID(v int) *AsistenciaCreate {
	_c.mutation.SetUsuarioID(v)
	return _c
}

// SetFecha sets the "fecha" field.
func (_c *AsistenciaCreate) SetFecha(v time.Time) *AsistenciaCreate {
	_c.mutation.SetFecha(v)
	return _c
}

// SetHoraEntrada sets the "hora_entrada" field.
func (_c *AsistenciaCreate) SetHoraEntrada(v time.Time) *AsistenciaCreate {
	_c.mutation.SetHoraEntrada(v)
	return _c
}

// SetNillableHoraEntrada sets the "hora_entrada" field if the given value is not nil.
func (_c *AsistenciaCreate) SetNillableHoraEntrada(v *time.Time) *AsistenciaCreate {
	if v != nil {
		_c.SetHoraEntrada(*v)
	}
	return _c
}

// SetHoraSalida sets the "hora_salida" field.
func (_c *AsistenciaCreate) SetHoraSalida(v time.Time) *AsistenciaCreate {
	_c.mutation.SetHoraSalida(v)
	return _c
}

// SetNillableHoraSalida sets the "hora_salida" field if the given value is not nil.
func (_c *AsistenciaCreate) SetNillableHoraSalida(v *time.Time) *AsistenciaCreate {
	if v != nil {
		_c.SetHoraSalida(*v)
	}
	return _c
}

// SetEstado sets the "estado" field.
func (_c *AsistenciaCreate) SetEstado(v asistencia.Estado) *AsistenciaCreate {
	_c.mutation.SetEstado(v)
	return _c
}

// SetNillableEstado sets the "estado" field if the given value is not nil.
func (_c *AsistenciaCreate) SetNillableEstado(v *asistencia.Estado) *AsistenciaCreate {
	if v != nil {
		_c.SetEstado(*v)
	}
	return _c
}

// SetNotas sets the "notas" field.
func (_c *AsistenciaCreate) SetNotas(v string) *AsistenciaCreate {
	_c.mutation.SetNotas(v)
	return _c
}

// SetNillableNotas sets the "notas" field if the given value is not nil.
func (_c *AsistenciaCreate) SetNillableNotas(v *string) *AsistenciaCreate {
	if v != nil {
		_c.SetNotas(*v)
	}
	return _c
}

// SetHorasTrabajadas sets the "horas_trabajadas" field.
func (_c *AsistenciaCreate) SetHorasTrabajadas(v float64) *AsistenciaCreate {
	_c.mutation.SetHorasTrabajadas(v)
	return _c
}

// SetNillableHorasTrabajadas sets the "horas_trabajadas" field if the given value is not nil.
func (_c *AsistenciaCreate) SetNillableHorasTrabajadas(v *float64) *AsistenciaCreate {
	if v != nil {
		_c.SetHorasTrabajadas(*v)
	}
	return _c
}

// SetEmpresa sets the "empresa" edge to the Empresa entity.
func (_c *AsistenciaCreate) SetEmpresa(v *Empresa) *AsistenciaCreate {
	return _c.SetEmpresaID(v.ID)
}

// SetUsuario sets the "usuario" edge to the Usuario entity.
func (_c *AsistenciaCreate) SetUsuario(v *Usuario) *AsistenciaCreate {
	return _c.SetUsuarioID(v.ID)
}

// Mutation returns the AsistenciaMutation object of the builder.
func (_c *AsistenciaCreate) Mutation() *AsistenciaMutation {
	return _c.mutation
}

// Save creates the Asistencia in the database.
func (_c *AsistenciaCreate) Save(ctx context.Context) (*Asistencia, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AsistenciaCreate) SaveX(ctx context.Context) *Asistencia {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AsistenciaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AsistenciaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AsistenciaCreate) defaults() {
	if _, ok := _c.mutation.CreadoEn(); !ok {
		v := asistencia.DefaultCreadoEn()
		_c.mutation.SetCreadoEn(v)
	}
	if _, ok := _c.mutation.Estado(); !ok {
		v := asistencia.DefaultEstado
		_c.mutation.SetEstado(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AsistenciaCreate) check() error {
	if _, ok := _c.mutation.CreadoEn(); !ok {
		return &ValidationError{Name: "creado_en", err: errors.New(`ent: missing required field "Asistencia.creado_en"`)}
	}
	if _, ok := _c.mutation.EmpresaID(); !ok {
		return &ValidationError{Name: "empresa_id", err: errors.New(`ent: missing required field "Asistencia.empresa_id"`)}
	}
	if _, ok := _c.mutation.UsuarioID(); !ok {
		return &ValidationError{Name: "usuario_id", err: errors.New(`ent: missing required field "Asistencia.usuario_id"`)}
	}
	if _, ok := _c.mutation.Fecha(); !ok {
		return &ValidationError{Name: "fecha", err: errors.New(`ent: missing required field "Asistencia.fecha"`)}
	}
	if _, ok := _c.mutation.Estado(); !ok {
		return &ValidationError{Name: "estado", err: errors.New(`ent: missing required field "Asistencia.estado"`)}
	}
	if v, ok := _c.mutation.Estado(); ok {
		if err := asistencia.EstadoValidator(v); err != nil {
			return &ValidationError{Name: "estado", err: fmt.Errorf(`ent: validator failed for field "Asistencia.estado": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Notas(); ok {
		if err := asistencia.NotasValidator(v); err != nil {
			return &ValidationError{Name: "notas", err: fmt.Errorf(`ent: validator failed for field "Asistencia.notas": %w`, err)}
		}
	}
	if len(_c.mutation.EmpresaIDs()) == 0 {
		return &ValidationError{Name: "empresa", err: errors.New(`ent: missing required edge "Asistencia.empresa"`)}
	}
	if len(_c.mutation.UsuarioIDs()) == 0 {
		return &ValidationError{Name: "usuario", err: errors.New(`ent: missing required edge "Asistencia.usuario"`)}
	}
	return nil
}

func (_c *AsistenciaCreate) sqlSave(ctx context.Context) (*Asistencia, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AsistenciaCreate) createSpec() (*Asistencia, *sqlgraph.CreateSpec) {
	var (
		_node = &Asistencia{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(asistencia.Table, sqlgraph.NewFieldSpec(asistencia.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreadoEn(); ok {
		_spec.SetField(asistencia.FieldCreadoEn, field.TypeTime, value)
		_node.CreadoEn = value
	}
	if value, ok := _c.mutation.Fecha(); ok {
		_spec.SetField(asistencia.FieldFecha, field.TypeTime, value)
		_node.Fecha = value
	}
	if value, ok := _c.mutation.HoraEntrada(); ok {
		_spec.SetField(asistencia.FieldHoraEntrada, field.TypeTime, value)
		_node.HoraEntrada = &value
	}
	if value, ok := _c.mutation.HoraSalida(); ok {
		_spec.SetField(asistencia.FieldHoraSalida, field.TypeTime, value)
		_node.HoraSalida = &value
	}
	if value, ok := _c.mutation.Estado(); ok {
		_spec.SetField(asistencia.FieldEstado, field.TypeEnum, value)
		_node.Estado = value
	}
	if value, ok := _c.mutation.Notas(); ok {
		_spec.SetField(asistencia.FieldNotas, field.TypeString, value)
		_node.Notas = &value
	}
	if value, ok := _c.mutation.HorasTrabajadas(); ok {
		_spec.SetField(asistencia.FieldHorasTrabajadas, field.TypeFloat64, value)
		_node.HorasTrabajadas = &value
	}
	if nodes := _c.mutation.EmpresaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asistencia.EmpresaTable,
			Columns: []string{asistencia.EmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresa.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EmpresaID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsuarioIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asistencia.UsuarioTable,
			Columns: []string{asistencia.UsuarioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usuario.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UsuarioID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AsistenciaCreateBulk is the builder for creating many Asistencia entities in bulk.
type AsistenciaCreateBulk struct {
	config
	err      error
	builders []*AsistenciaCreate
}

// Save creates the Asistencia entities in the database.
func (_c *AsistenciaCreateBulk) Save(ctx context.Context) ([]*Asistencia, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Asistencia, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AsistenciaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AsistenciaCreateBulk) SaveX(ctx context.Context) []*Asistencia {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AsistenciaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AsistenciaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
