// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rentals-go/ent/cita"
	"rentals-go/ent/cliente"
	"rentals-go/ent/empresa"
	"rentals-go/ent/propiedad"
	"rentals-go/ent/unidad"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CitaCreate is the builder for creating a Cita entity.
type CitaCreate struct {
	config
	mutation *CitaMutation
	hooks    []Hook
}

// SetCreadoEn sets the "creado_en" field.
func (_c *CitaCreate) SetCreadoEn(v time.Time) *CitaCreate {
	_c.mutation.SetCreadoEn(v)
	return _c
}

// SetNillableCreadoEn sets the "creado_en" field if the given value is not nil.
func (_c *CitaCreate) SetNillableCreadoEn(v *time.Time) *CitaCreate {
	if v != nil {
		_c.SetCreadoEn(*v)
	}
	return _c
}

// SetEmpresaID sets the "empresa_id" field.
func (_c *CitaCreate) SetEmpresaID(v int) *CitaCreate {
	_c.mutation.SetEmpresaID(v)
	return _c
}

// SetPropiedadID sets the "propiedad_id" field.
func (_c *CitaCreate) SetPropiedadID(v int) *CitaCreate {
	_c.mutation.SetPropiedadID(v)
	return _c
}

// SetNillablePropiedadID sets the "propiedad_id" field if the given value is not nil.
func (_c *CitaCreate) SetNillablePropiedadID(v *int) *CitaCreate {
	if v != nil {
		_c.SetPropiedadID(*v)
	}
	return _c
}

// SetUnidadID sets the "unidad_id" field.
func (_c *CitaCreate) SetUnidadID(v int) *CitaCreate {
	_c.mutation.SetUnidadID(v)
	return _c
}

// SetNillableUnidadID sets the "unidad_id" field if the given value is not nil.
func (_c *CitaCreate) SetNillableUnidadID(v *int) *CitaCreate {
	if v != nil {
		_c.SetUnidadID(*v)
	}
	return _c
}

// SetClienteID sets the "cliente_id" field.
func (_c *CitaCreate) SetClienteID(v int) *CitaCreate {
	_c.mutation.SetClienteID(v)
	return _c
}

// SetNillableClienteID sets the "cliente_id" field if the given value is not nil.
func (_c *CitaCreate) SetNillableClienteID(v *int) *CitaCreate {
	if v != nil {
		_c.SetClienteID(*v)
	}
	return _c
}

// SetNombreProspecto sets the "nombre_prospecto" field.
func (_c *CitaCreate) SetNombreProspecto(v string) *CitaCreate {
	_c.mutation.SetNombreProspecto(v)
	return _c
}

// SetTelefonoProspecto sets the "telefono_prospecto" field.
func (_c *CitaCreate) SetTelefonoProspecto(v string) *CitaCreate {
	_c.mutation.SetTelefonoProspecto(v)
	return _c
}

// SetCorreoProspecto sets the "correo_prospecto" field.
func (_c *CitaCreate) SetCorreoProspecto(v string) *CitaCreate {
	_c.mutation.SetCorreoProspecto(v)
	return _c
}

// SetNillableCorreoProspecto sets the "correo_prospecto" field if the given value is not nil.
func (_c *CitaCreate) SetNillableCorreoProspecto(v *string) *CitaCreate {
	if v != nil {
		_c.SetCorreoProspecto(*v)
	}
	return _c
}

// SetFechaVisita sets the "fecha_visita" field.
func (_c *CitaCreate) SetFechaVisita(v time.Time) *CitaCreate {
	_c.mutation.SetFechaVisita(v)
	return _c
}

// SetEstado sets the "estado" field.
func (_c *CitaCreate) SetEstado(v cita.Estado) *CitaCreate {
	_c.mutation.SetEstado(v)
	return _c
}

// SetNillableEstado sets the "estado" field if the given value is not nil.
func (_c *CitaCreate) SetNillableEstado(v *cita.Estado) *CitaCreate {
	if v != nil {
		_c.SetEstado(*v)
	}
	return _c
}

// SetComentarios sets the "comentarios" field.
func (_c *CitaCreate) SetComentarios(v string) *CitaCreate {
	_c.mutation.SetComentarios(v)
	return _c
}

// SetNillableComentarios sets the "comentarios" field if the given value is not nil.
func (_c *CitaCreate) SetNillableComentarios(v *string) *CitaCreate {
	if v != nil {
		_c.SetComentarios(*v)
	}
	return _c
}

// SetEmpresa sets the "empresa" edge to the Empresa entity.
func (_c *CitaCreate) SetEmpresa(v *Empresa) *CitaCreate {
	return _c.SetEmpresaID(v.ID)
}

// SetPropiedad sets the "propiedad" edge to the Propiedad entity.
func (_c *CitaCreate) SetPropiedad(v *Propiedad) *CitaCreate {
	return _c.SetPropiedadID(v.ID)
}

// SetUnidad sets the "unidad" edge to the Unidad entity.
func (_c *CitaCreate) SetUnidad(v *Unidad) *CitaCreate {
	return _c.SetUnidadID(v.ID)
}

// SetCliente sets the "cliente" edge to the Cliente entity.
func (_c *CitaCreate) SetCliente(v *Cliente) *CitaCreate {
	return _c.SetClienteID(v.ID)
}

// Mutation returns the CitaMutation object of the builder.
func (_c *CitaCreate) Mutation() *CitaMutation {
	return _c.mutation
}

// Save creates the Cita in the database.
func (_c *CitaCreate) Save(ctx context.Context) (*Cita, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CitaCreate) SaveX(ctx context.Context) *Cita {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CitaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CitaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CitaCreate) defaults() {
	if _, ok := _c.mutation.CreadoEn(); !ok {
		v := cita.DefaultCreadoEn()
		_c.mutation.SetCreadoEn(v)
	}
	if _, ok := _c.mutation.Estado(); !ok {
		v := cita.DefaultEstado
		_c.mutation.SetEstado(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CitaCreate) check() error {
	if _, ok := _c.mutation.CreadoEn(); !ok {
		return &ValidationError{Name: "creado_en", err: errors.New(`ent: missing required field "Cita.creado_en"`)}
	}
	if _, ok := _c.mutation.EmpresaID(); !ok {
		return &ValidationError{Name: "empresa_id", err: errors.New(`ent: missing required field "Cita.empresa_id"`)}
	}
	if _, ok := _c.mutation.NombreProspecto(); !ok {
		return &ValidationError{Name: "nombre_prospecto", err: errors.New(`ent: missing required field "Cita.nombre_prospecto"`)}
	}
	if v, ok := _c.mutation.NombreProspecto(); ok {
		if err := cita.NombreProspectoValidator(v); err != nil {
			return &ValidationError{Name: "nombre_prospecto", err: fmt.Errorf(`ent: validator failed for field "Cita.nombre_prospecto": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TelefonoProspecto(); !ok {
		return &ValidationError{Name: "telefono_prospecto", err: errors.New(`ent: missing required field "Cita.telefono_prospecto"`)}
	}
	if v, ok := _c.mutation.TelefonoProspecto(); ok {
		if err := cita.TelefonoProspectoValidator(v); err != nil {
			return &ValidationError{Name: "telefono_prospecto", err: fmt.Errorf(`ent: validator failed for field "Cita.telefono_prospecto": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CorreoProspecto(); ok {
		if err := cita.CorreoProspectoValidator(v); err != nil {
			return &ValidationError{Name: "correo_prospecto", err: fmt.Errorf(`ent: validator failed for field "Cita.correo_prospecto": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FechaVisita(); !ok {
		return &ValidationError{Name: "fecha_visita", err: errors.New(`ent: missing required field "Cita.fecha_visita"`)}
	}
	if _, ok := _c.mutation.Estado(); !ok {
		return &ValidationError{Name: "estado", err: errors.New(`ent: missing required field "Cita.estado"`)}
	}
	if v, ok := _c.mutation.Estado(); ok {
		if err := cita.EstadoValidator(v); err != nil {
			return &ValidationError{Name: "estado", err: fmt.Errorf(`ent: validator failed for field "Cita.estado": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Comentarios(); ok {
		if err := cita.ComentariosValidator(v); err != nil {
			return &ValidationError{Name: "comentarios", err: fmt.Errorf(`ent: validator failed for field "Cita.comentarios": %w`, err)}
		}
	}
	if len(_c.mutation.EmpresaIDs()) == 0 {
		return &ValidationError{Name: "empresa", err: errors.New(`ent: missing required edge "Cita.empresa"`)}
	}
	return nil
}

func (_c *CitaCreate) sqlSave(ctx context.Context) (*Cita, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CitaCreate) createSpec() (*Cita, *sqlgraph.CreateSpec) {
	var (
		_node = &Cita{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cita.Table, sqlgraph.NewFieldSpec(cita.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreadoEn(); ok {
		_spec.SetField(cita.FieldCreadoEn, field.TypeTime, value)
		_node.CreadoEn = value
	}
	if value, ok := _c.mutation.NombreProspecto(); ok {
		_spec.SetField(cita.FieldNombreProspecto, field.TypeString, value)
		_node.NombreProspecto = value
	}
	if value, ok := _c.mutation.TelefonoProspecto(); ok {
		_spec.SetField(cita.FieldTelefonoProspecto, field.TypeString, value)
		_node.TelefonoProspecto = value
	}
	if value, ok := _c.mutation.CorreoProspecto(); ok {
		_spec.SetField(cita.FieldCorreoProspecto, field.TypeString, value)
		_node.CorreoProspecto = &value
	}
	if value, ok := _c.mutation.FechaVisita(); ok {
		_spec.SetField(cita.FieldFechaVisita, field.TypeTime, value)
		_node.FechaVisita = value
	}
	if value, ok := _c.mutation.Estado(); ok {
		_spec.SetField(cita.FieldEstado, field.TypeEnum, value)
		_node.Estado = value
	}
	if value, ok := _c.mutation.Comentarios(); ok {
		_spec.SetField(cita.FieldComentarios, field.TypeString, value)
		_node.Comentarios = &value
	}
	if nodes := _c.mutation.EmpresaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cita.EmpresaTable,
			Columns: []string{cita.EmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresa.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EmpresaID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PropiedadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cita.PropiedadTable,
			Columns: []string{cita.PropiedadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propiedad.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PropiedadID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UnidadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cita.UnidadTable,
			Columns: []string{cita.UnidadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unidad.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UnidadID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ClienteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cita.ClienteTable,
			Columns: []string{cita.ClienteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cliente.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ClienteID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CitaCreateBulk is the builder for creating many Cita entities in bulk.
type CitaCreateBulk struct {
	config
	err      error
	builders []*CitaCreate
}

// Save creates the Cita entities in the database.
func (_c *CitaCreateBulk) Save(ctx context.Context) ([]*Cita, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Cita, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CitaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CitaCreateBulk) SaveX(ctx context.Context) []*Cita {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CitaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CitaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
