// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rentals-go/ent/cliente"
	"rentals-go/ent/clientetelefono"
	"rentals-go/ent/contrato"
	"rentals-go/ent/empresa"
	"rentals-go/ent/pago"
	"rentals-go/ent/ticket"
	"rentals-go/ent/tipoidentificacion"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClienteCreate is the builder for creating a Cliente entity.
type ClienteCreate struct {
	config
	mutation *ClienteMutation
	hooks    []Hook
}

// SetCreadoEn sets the "creado_en" field.
func (_c *ClienteCreate) SetCreadoEn(v time.Time) *ClienteCreate {
	_c.mutation.SetCreadoEn(v)
	return _c
}

// SetNillableCreadoEn sets the "creado_en" field if the given value is not nil.
func (_c *ClienteCreate) SetNillableCreadoEn(v *time.Time) *ClienteCreate {
	if v != nil {
		_c.SetCreadoEn(*v)
	}
	return _c
}

// SetEmpresaID sets the "empresa_id" field.
func (_c *ClienteCreate) SetEmpresaID(v int) *ClienteCreate {
	_c.mutation.SetEmpresaID(v)
	return _c
}

// SetTipoIdentificacionID sets the "tipo_identificacion_id" field.
func (_c *ClienteCreate) SetTipoIdentificacionID(v int) *ClienteCreate {
	_c.mutation.SetTipoIdentificacionID(v)
	return _c
}

// SetDocumentoNumero sets the "documento_numero" field.
func (_c *ClienteCreate) SetDocumentoNumero(v string) *ClienteCreate {
	_c.mutation.SetDocumentoNumero(v)
	return _c
}

// SetNombres sets the "nombres" field.
func (_c *ClienteCreate) SetNombres(v string) *ClienteCreate {
	_c.mutation.SetNombres(v)
	return _c
}

// SetApellidos sets the "apellidos" field.
func (_c *ClienteCreate) SetApellidos(v string) *ClienteCreate {
	_c.mutation.SetApellidos(v)
	return _c
}

// SetNillableApellidos sets the "apellidos" field if the given value is not nil.
func (_c *ClienteCreate) SetNillableApellidos(v *string) *ClienteCreate {
	if v != nil {
		_c.SetApellidos(*v)
	}
	return _c
}

// SetCorreo sets the "correo" field.
func (_c *ClienteCreate) SetCorreo(v string) *ClienteCreate {
	_c.mutation.SetCorreo(v)
	return _c
}

// SetNillableCorreo sets the "correo" field if the given value is not nil.
func (_c *ClienteCreate) SetNillableCorreo(v *string) *ClienteCreate {
	if v != nil {
		_c.SetCorreo(*v)
	}
	return _c
}

// SetFechaNacimiento sets the "fecha_nacimiento" field.
func (_c *ClienteCreate) SetFechaNacimiento(v time.Time) *ClienteCreate {
	_c.mutation.SetFechaNacimiento(v)
	return _c
}

// SetNillableFechaNacimiento sets the "fecha_nacimiento" field if the given value is not nil.
func (_c *ClienteCreate) SetNillableFechaNacimiento(v *time.Time) *ClienteCreate {
	if v != nil {
		_c.SetFechaNacimiento(*v)
	}
	return _c
}

// SetNacionalidad sets the "nacionalidad" field.
func (_c *ClienteCreate) SetNacionalidad(v string) *ClienteCreate {
	_c.mutation.SetNacionalidad(v)
	return _c
}

// SetNillableNacionalidad sets the "nacionalidad" field if the given value is not nil.
func (_c *ClienteCreate) SetNillableNacionalidad(v *string) *ClienteCreate {
	if v != nil {
		_c.SetNacionalidad(*v)
	}
	return _c
}

// SetDireccion sets the "direccion" field.
func (_c *ClienteCreate) SetDireccion(v string) *ClienteCreate {
	_c.mutation.SetDireccion(v)
	return _c
}

// SetNillableDireccion sets the "direccion" field if the given value is not nil.
func (_c *ClienteCreate) SetNillableDireccion(v *string) *ClienteCreate {
	if v != nil {
		_c.SetDireccion(*v)
	}
	return _c
}

// SetContactoEmergencia sets the "contacto_emergencia" field.
func (_c *ClienteCreate) SetContactoEmergencia(v string) *ClienteCreate {
	_c.mutation.SetContactoEmergencia(v)
	return _c
}

// SetNillableContactoEmergencia sets the "contacto_emergencia" field if the given value is not nil.
func (_c *ClienteCreate) SetNillableContactoEmergencia(v *string) *ClienteCreate {
	if v != nil {
		_c.SetContactoEmergencia(*v)
	}
	return _c
}

// SetTelefonoEmergencia sets the "telefono_emergencia" field.
func (_c *ClienteCreate) SetTelefonoEmergencia(v string) *ClienteCreate {
	_c.mutation.SetTelefonoEmergencia(v)
	return _c
}

// SetNillableTelefonoEmergencia sets the "telefono_emergencia" field if the given value is not nil.
func (_c *ClienteCreate) SetNillableTelefonoEmergencia(v *string) *ClienteCreate {
	if v != nil {
		_c.SetTelefonoEmergencia(*v)
	}
	return _c
}

// SetNotas sets the "notas" field.
func (_c *ClienteCreate) SetNotas(v string) *ClienteCreate {
	_c.mutation.SetNotas(v)
	return _c
}

// SetNillableNotas sets the "notas" field if the given value is not nil.
func (_c *ClienteCreate) SetNillableNotas(v *string) *ClienteCreate {
	if v != nil {
		_c.SetNotas(*v)
	}
	return _c
}

// SetEstado sets the "estado" field.
func (_c *ClienteCreate) SetEstado(v cliente.Estado) *ClienteCreate {
	_c.mutation.SetEstado(v)
	return _c
}

// SetNillableEstado sets the "estado" field if the given value is not nil.
func (_c *ClienteCreate) SetNillableEstado(v *cliente.Estado) *ClienteCreate {
	if v != nil {
		_c.SetEstado(*v)
	}
	return _c
}

// SetEmpresa sets the "empresa" edge to the Empresa entity.
func (_c *ClienteCreate) SetEmpresa(v *Empresa) *ClienteCreate {
	return _c.SetEmpresaID(v.ID)
}

// SetTipoIdentificacion sets the "tipo_identificacion" edge to the TipoIdentificacion entity.
func (_c *ClienteCreate) SetTipoIdentificacion(v *TipoIdentificacion) *ClienteCreate {
	return _c.SetTipoIdentificacionID(v.ID)
}

// AddTelefonoIDs adds the "telefonos" edge to the ClienteTelefono entity by IDs.
func (_c *ClienteCreate) AddTelefonoIDs(ids ...int) *ClienteCreate {
	_c.mutation.AddTelefonoIDs(ids...)
	return _c
}

// AddTelefonos adds the "telefonos" edges to the ClienteTelefono entity.
func (_c *ClienteCreate) AddTelefonos(v ...*ClienteTelefono) *ClienteCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTelefonoIDs(ids...)
}

// AddContratoIDs adds the "contratos" edge to the Contrato entity by IDs.
func (_c *ClienteCreate) AddContratoIDs(ids ...int) *ClienteCreate {
	_c.mutation.AddContratoIDs(ids...)
	return _c
}

// AddContratos adds the "contratos" edges to the Contrato entity.
func (_c *ClienteCreate) AddContratos(v ...*Contrato) *ClienteCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddContratoIDs(ids...)
}

// AddPagoIDs adds the "pagos" edge to the Pago entity by IDs.
func (_c *ClienteCreate) AddPagoIDs(ids ...int) *ClienteCreate {
	_c.mutation.AddPagoIDs(ids...)
	return _c
}

// AddPagos adds the "pagos" edges to the Pago entity.
func (_c *ClienteCreate) AddPagos(v ...*Pago) *ClienteCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPagoIDs(ids...)
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (_c *ClienteCreate) AddTicketIDs(ids ...int) *ClienteCreate {
	_c.mutation.AddTicketIDs(ids...)
	return _c
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (_c *ClienteCreate) AddTickets(v ...*Ticket) *ClienteCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTicketIDs(ids...)
}

// Mutation returns the ClienteMutation object of the builder.
func (_c *ClienteCreate) Mutation() *ClienteMutation {
	return _c.mutation
}

// Save creates the Cliente in the database.
func (_c *ClienteCreate) Save(ctx context.Context) (*Cliente, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ClienteCreate) SaveX(ctx context.Context) *Cliente {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClienteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClienteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ClienteCreate) defaults() {
	if _, ok := _c.mutation.CreadoEn(); !ok {
		v := cliente.DefaultCreadoEn()
		_c.mutation.SetCreadoEn(v)
	}
	if _, ok := _c.mutation.Estado(); !ok {
		v := cliente.DefaultEstado
		_c.mutation.SetEstado(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ClienteCreate) check() error {
	if _, ok := _c.mutation.CreadoEn(); !ok {
		return &ValidationError{Name: "creado_en", err: errors.New(`ent: missing required field "Cliente.creado_en"`)}
	}
	if _, ok := _c.mutation.EmpresaID(); !ok {
		return &ValidationError{Name: "empresa_id", err: errors.New(`ent: missing required field "Cliente.empresa_id"`)}
	}
	if _, ok := _c.mutation.TipoIdentificacionID(); !ok {
		return &ValidationError{Name: "tipo_identificacion_id", err: errors.New(`ent: missing required field "Cliente.tipo_identificacion_id"`)}
	}
	if _, ok := _c.mutation.DocumentoNumero(); !ok {
		return &ValidationError{Name: "documento_numero", err: errors.New(`ent: missing required field "Cliente.documento_numero"`)}
	}
	if v, ok := _c.mutation.DocumentoNumero(); ok {
		if err := cliente.DocumentoNumeroValidator(v); err != nil {
			return &ValidationError{Name: "documento_numero", err: fmt.Errorf(`ent: validator failed for field "Cliente.documento_numero": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Nombres(); !ok {
		return &ValidationError{Name: "nombres", err: errors.New(`ent: missing required field "Cliente.nombres"`)}
	}
	if v, ok := _c.mutation.Nombres(); ok {
		if err := cliente.NombresValidator(v); err != nil {
			return &ValidationError{Name: "nombres", err: fmt.Errorf(`ent: validator failed for field "Cliente.nombres": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Apellidos(); ok {
		if err := cliente.ApellidosValidator(v); err != nil {
			return &ValidationError{Name: "apellidos", err: fmt.Errorf(`ent: validator failed for field "Cliente.apellidos": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Correo(); ok {
		if err := cliente.CorreoValidator(v); err != nil {
			return &ValidationError{Name: "correo", err: fmt.Errorf(`ent: validator failed for field "Cliente.correo": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Nacionalidad(); ok {
		if err := cliente.NacionalidadValidator(v); err != nil {
			return &ValidationError{Name: "nacionalidad", err: fmt.Errorf(`ent: validator failed for field "Cliente.nacionalidad": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Direccion(); ok {
		if err := cliente.DireccionValidator(v); err != nil {
			return &ValidationError{Name: "direccion", err: fmt.Errorf(`ent: validator failed for field "Cliente.direccion": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ContactoEmergencia(); ok {
		if err := cliente.ContactoEmergenciaValidator(v); err != nil {
			return &ValidationError{Name: "contacto_emergencia", err: fmt.Errorf(`ent: validator failed for field "Cliente.contacto_emergencia": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TelefonoEmergencia(); ok {
		if err := cliente.TelefonoEmergenciaValidator(v); err != nil {
			return &ValidationError{Name: "telefono_emergencia", err: fmt.Errorf(`ent: validator failed for field "Cliente.telefono_emergencia": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Notas(); ok {
		if err := cliente.NotasValidator(v); err != nil {
			return &ValidationError{Name: "notas", err: fmt.Errorf(`ent: validator failed for field "Cliente.notas": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Estado(); !ok {
		return &ValidationError{Name: "estado", err: errors.New(`ent: missing required field "Cliente.estado"`)}
	}
	if v, ok := _c.mutation.Estado(); ok {
		if err := cliente.EstadoValidator(v); err != nil {
			return &ValidationError{Name: "estado", err: fmt.Errorf(`ent: validator failed for field "Cliente.estado": %w`, err)}
		}
	}
	if len(_c.mutation.EmpresaIDs()) == 0 {
		return &ValidationError{Name: "empresa", err: errors.New(`ent: missing required edge "Cliente.empresa"`)}
	}
	if len(_c.mutation.TipoIdentificacionIDs()) == 0 {
		return &ValidationError{Name: "tipo_identificacion", err: errors.New(`ent: missing required edge "Cliente.tipo_identificacion"`)}
	}
	return nil
}

func (_c *ClienteCreate) sqlSave(ctx context.Context) (*Cliente, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ClienteCreate) createSpec() (*Cliente, *sqlgraph.CreateSpec) {
	var (
		_node = &Cliente{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cliente.Table, sqlgraph.NewFieldSpec(cliente.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreadoEn(); ok {
		_spec.SetField(cliente.FieldCreadoEn, field.TypeTime, value)
		_node.CreadoEn = value
	}
	if value, ok := _c.mutation.DocumentoNumero(); ok {
		_spec.SetField(cliente.FieldDocumentoNumero, field.TypeString, value)
		_node.DocumentoNumero = value
	}
	if value, ok := _c.mutation.Nombres(); ok {
		_spec.SetField(cliente.FieldNombres, field.TypeString, value)
		_node.Nombres = value
	}
	if value, ok := _c.mutation.Apellidos(); ok {
		_spec.SetField(cliente.FieldApellidos, field.TypeString, value)
		_node.Apellidos = &value
	}
	if value, ok := _c.mutation.Correo(); ok {
		_spec.SetField(cliente.FieldCorreo, field.TypeString, value)
		_node.Correo = &value
	}
	if value, ok := _c.mutation.FechaNacimiento(); ok {
		_spec.SetField(cliente.FieldFechaNacimiento, field.TypeTime, value)
		_node.FechaNacimiento = &value
	}
	if value, ok := _c.mutation.Nacionalidad(); ok {
		_spec.SetField(cliente.FieldNacionalidad, field.TypeString, value)
		_node.Nacionalidad = &value
	}
	if value, ok := _c.mutation.Direccion(); ok {
		_spec.SetField(cliente.FieldDireccion, field.TypeString, value)
		_node.Direccion = &value
	}
	if value, ok := _c.mutation.ContactoEmergencia(); ok {
		_spec.SetField(cliente.FieldContactoEmergencia, field.TypeString, value)
		_node.ContactoEmergencia = &value
	}
	if value, ok := _c.mutation.TelefonoEmergencia(); ok {
		_spec.SetField(cliente.FieldTelefonoEmergencia, field.TypeString, value)
		_node.TelefonoEmergencia = &value
	}
	if value, ok := _c.mutation.Notas(); ok {
		_spec.SetField(cliente.FieldNotas, field.TypeString, value)
		_node.Notas = &value
	}
	if value, ok := _c.mutation.Estado(); ok {
		_spec.SetField(cliente.FieldEstado, field.TypeEnum, value)
		_node.Estado = value
	}
	if nodes := _c.mutation.EmpresaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cliente.EmpresaTable,
			Columns: []string{cliente.EmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresa.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EmpresaID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TipoIdentificacionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cliente.TipoIdentificacionTable,
			Columns: []string{cliente.TipoIdentificacionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tipoidentificacion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TipoIdentificacionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TelefonosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cliente.TelefonosTable,
			Columns: []string{cliente.TelefonosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientetelefono.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ContratosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cliente.ContratosTable,
			Columns: []string{cliente.ContratosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contrato.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PagosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cliente.PagosTable,
			Columns: []string{cliente.PagosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pago.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cliente.TicketsTable,
			Columns: []string{cliente.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClienteCreateBulk is the builder for creating many Cliente entities in bulk.
type ClienteCreateBulk struct {
	config
	err      error
	builders []*ClienteCreate
}

// Save creates the Cliente entities in the database.
func (_c *ClienteCreateBulk) Save(ctx context.Context) ([]*Cliente, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Cliente, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClienteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ClienteCreateBulk) SaveX(ctx context.Context) []*Cliente {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClienteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClienteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
