// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"rentals-go/ent/cliente"
	"rentals-go/ent/empresa"
	"rentals-go/ent/tipoidentificacion"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Cliente is the model entity for the Cliente schema.
type Cliente struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreadoEn holds the value of the "creado_en" field.
	CreadoEn time.Time `json:"creado_en,omitempty"`
	// EmpresaID holds the value of the "empresa_id" field.
	EmpresaID int `json:"empresa_id,omitempty"`
	// TipoIdentificacionID holds the value of the "tipo_identificacion_id" field.
	TipoIdentificacionID int `json:"tipo_identificacion_id,omitempty"`
	// DocumentoNumero holds the value of the "documento_numero" field.
	DocumentoNumero string `json:"documento_numero,omitempty"`
	// Nombres holds the value of the "nombres" field.
	Nombres string `json:"nombres,omitempty"`
	// Apellidos holds the value of the "apellidos" field.
	Apellidos *string `json:"apellidos,omitempty"`
	// Correo holds the value of the "correo" field.
	Correo *string `json:"correo,omitempty"`
	// FechaNacimiento holds the value of the "fecha_nacimiento" field.
	FechaNacimiento *time.Time `json:"fecha_nacimiento,omitempty"`
	// Nacionalidad holds the value of the "nacionalidad" field.
	Nacionalidad *string `json:"nacionalidad,omitempty"`
	// Direccion holds the value of the "direccion" field.
	Direccion *string `json:"direccion,omitempty"`
	// ContactoEmergencia holds the value of the "contacto_emergencia" field.
	ContactoEmergencia *string `json:"contacto_emergencia,omitempty"`
	// TelefonoEmergencia holds the value of the "telefono_emergencia" field.
	TelefonoEmergencia *string `json:"telefono_emergencia,omitempty"`
	// Notas holds the value of the "notas" field.
	Notas *string `json:"notas,omitempty"`
	// Estado holds the value of the "estado" field.
	Estado cliente.Estado `json:"estado,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ClienteQuery when eager-loading is set.
	Edges        ClienteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ClienteEdges holds the relations/edges for other nodes in the graph.
type ClienteEdges struct {
	// Empresa holds the value of the empresa edge.
	Empresa *Empresa `json:"empresa,omitempty"`
	// TipoIdentificacion holds the value of the tipo_identificacion edge.
	TipoIdentificacion *TipoIdentificacion `json:"tipo_identificacion,omitempty"`
	// Telefonos holds the value of the telefonos edge.
	Telefonos []*ClienteTelefono `json:"telefonos,omitempty"`
	// Contratos holds the value of the contratos edge.
	Contratos []*Contrato `json:"contratos,omitempty"`
	// Pagos holds the value of the pagos edge.
	Pagos []*Pago `json:"pagos,omitempty"`
	// Tickets holds the value of the tickets edge.
	Tickets []*Ticket `json:"tickets,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// EmpresaOrErr returns the Empresa value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ClienteEdges) EmpresaOrErr() (*Empresa, error) {
	if e.Empresa != nil {
		return e.Empresa, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: empresa.Label}
	}
	return nil, &NotLoadedError{edge: "empresa"}
}

// TipoIdentificacionOrErr returns the TipoIdentificacion value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ClienteEdges) TipoIdentificacionOrErr() (*TipoIdentificacion, error) {
	if e.TipoIdentificacion != nil {
		return e.TipoIdentificacion, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: tipoidentificacion.Label}
	}
	return nil, &NotLoadedError{edge: "tipo_identificacion"}
}

// TelefonosOrErr returns the Telefonos value or an error if the edge
// was not loaded in eager-loading.
func (e ClienteEdges) TelefonosOrErr() ([]*ClienteTelefono, error) {
	if e.loadedTypes[2] {
		return e.Telefonos, nil
	}
	return nil, &NotLoadedError{edge: "telefonos"}
}

// ContratosOrErr returns the Contratos value or an error if the edge
// was not loaded in eager-loading.
func (e ClienteEdges) ContratosOrErr() ([]*Contrato, error) {
	if e.loadedTypes[3] {
		return e.Contratos, nil
	}
	return nil, &NotLoadedError{edge: "contratos"}
}

// PagosOrErr returns the Pagos value or an error if the edge
// was not loaded in eager-loading.
func (e ClienteEdges) PagosOrErr() ([]*Pago, error) {
	if e.loadedTypes[4] {
		return e.Pagos, nil
	}
	return nil, &NotLoadedError{edge: "pagos"}
}

// TicketsOrErr returns the Tickets value or an error if the edge
// was not loaded in eager-loading.
func (e ClienteEdges) TicketsOrErr() ([]*Ticket, error) {
	if e.loadedTypes[5] {
		return e.Tickets, nil
	}
	return nil, &NotLoadedError{edge: "tickets"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Cliente) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cliente.FieldID, cliente.FieldEmpresaID, cliente.FieldTipoIdentificacionID:
			values[i] = new(sql.NullInt64)
		case cliente.FieldDocumentoNumero, cliente.FieldNombres, cliente.FieldApellidos, cliente.FieldCorreo, cliente.FieldNacionalidad, cliente.FieldDireccion, cliente.FieldContactoEmergencia, cliente.FieldTelefonoEmergencia, cliente.FieldNotas, cliente.FieldEstado:
			values[i] = new(sql.NullString)
		case cliente.FieldCreadoEn, cliente.FieldFechaNacimiento:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Cliente fields.
func (_m *Cliente) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cliente.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case cliente.FieldCreadoEn:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field creado_en", values[i])
			} else if value.Valid {
				_m.CreadoEn = value.Time
			}
		case cliente.FieldEmpresaID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field empresa_id", values[i])
			} else if value.Valid {
				_m.EmpresaID = int(value.Int64)
			}
		case cliente.FieldTipoIdentificacionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tipo_identificacion_id", values[i])
			} else if value.Valid {
				_m.TipoIdentificacionID = int(value.Int64)
			}
		case cliente.FieldDocumentoNumero:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field documento_numero", values[i])
			} else if value.Valid {
				_m.DocumentoNumero = value.String
			}
		case cliente.FieldNombres:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nombres", values[i])
			} else if value.Valid {
				_m.Nombres = value.String
			}
		case cliente.FieldApellidos:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field apellidos", values[i])
			} else if value.Valid {
				_m.Apellidos = new(string)
				*_m.Apellidos = value.String
			}
		case cliente.FieldCorreo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field correo", values[i])
			} else if value.Valid {
				_m.Correo = new(string)
				*_m.Correo = value.String
			}
		case cliente.FieldFechaNacimiento:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field fecha_nacimiento", values[i])
			} else if value.Valid {
				_m.FechaNacimiento = new(time.Time)
				*_m.FechaNacimiento = value.Time
			}
		case cliente.FieldNacionalidad:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nacionalidad", values[i])
			} else if value.Valid {
				_m.Nacionalidad = new(string)
				*_m.Nacionalidad = value.String
			}
		case cliente.FieldDireccion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field direccion", values[i])
			} else if value.Valid {
				_m.Direccion = new(string)
				*_m.Direccion = value.String
			}
		case cliente.FieldContactoEmergencia:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contacto_emergencia", values[i])
			} else if value.Valid {
				_m.ContactoEmergencia = new(string)
				*_m.ContactoEmergencia = value.String
			}
		case cliente.FieldTelefonoEmergencia:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field telefono_emergencia", values[i])
			} else if value.Valid {
				_m.TelefonoEmergencia = new(string)
				*_m.TelefonoEmergencia = value.String
			}
		case cliente.FieldNotas:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notas", values[i])
			} else if value.Valid {
				_m.Notas = new(string)
				*_m.Notas = value.String
			}
		case cliente.FieldEstado:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field estado", values[i])
			} else if value.Valid {
				_m.Estado = cliente.Estado(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Cliente.
// This includes values selected through modifiers, order, etc.
func (_m *Cliente) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEmpresa queries the "empresa" edge of the Cliente entity.
func (_m *Cliente) QueryEmpresa() *EmpresaQuery {
	return NewClienteClient(_m.config).QueryEmpresa(_m)
}

// QueryTipoIdentificacion queries the "tipo_identificacion" edge of the Cliente entity.
func (_m *Cliente) QueryTipoIdentificacion() *TipoIdentificacionQuery {
	return NewClienteClient(_m.config).QueryTipoIdentificacion(_m)
}

// QueryTelefonos queries the "telefonos" edge of the Cliente entity.
func (_m *Cliente) QueryTelefonos() *ClienteTelefonoQuery {
	return NewClienteClient(_m.config).QueryTelefonos(_m)
}

// QueryContratos queries the "contratos" edge of the Cliente entity.
func (_m *Cliente) QueryContratos() *ContratoQuery {
	return NewClienteClient(_m.config).QueryContratos(_m)
}

// QueryPagos queries the "pagos" edge of the Cliente entity.
func (_m *Cliente) QueryPagos() *PagoQuery {
	return NewClienteClient(_m.config).QueryPagos(_m)
}

// QueryTickets queries the "tickets" edge of the Cliente entity.
func (_m *Cliente) QueryTickets() *TicketQuery {
	return NewClienteClient(_m.config).QueryTickets(_m)
}

// Update returns a builder for updating this Cliente.
// Note that you need to call Cliente.Unwrap() before calling this method if this Cliente
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Cliente) Update() *ClienteUpdateOne {
	return NewClienteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Cliente entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Cliente) Unwrap() *Cliente {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Cliente is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Cliente) String() string {
	var builder strings.Builder
	builder.WriteString("Cliente(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("creado_en=")
	builder.WriteString(_m.CreadoEn.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("empresa_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmpresaID))
	builder.WriteString(", ")
	builder.WriteString("tipo_identificacion_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TipoIdentificacionID))
	builder.WriteString(", ")
	builder.WriteString("documento_numero=")
	builder.WriteString(_m.DocumentoNumero)
	builder.WriteString(", ")
	builder.WriteString("nombres=")
	builder.WriteString(_m.Nombres)
	builder.WriteString(", ")
	if v := _m.Apellidos; v != nil {
		builder.WriteString("apellidos=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Correo; v != nil {
		builder.WriteString("correo=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FechaNacimiento; v != nil {
		builder.WriteString("fecha_nacimiento=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Nacionalidad; v != nil {
		builder.WriteString("nacionalidad=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Direccion; v != nil {
		builder.WriteString("direccion=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ContactoEmergencia; v != nil {
		builder.WriteString("contacto_emergencia=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TelefonoEmergencia; v != nil {
		builder.WriteString("telefono_emergencia=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Notas; v != nil {
		builder.WriteString("notas=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("estado=")
	builder.WriteString(fmt.Sprintf("%v", _m.Estado))
	builder.WriteByte(')')
	return builder.String()
}

// Clientes is a parsable slice of Cliente.
type Clientes []*Cliente
