// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"rentals-go/ent/empresa"
	"rentals-go/ent/empresausuario"
	"rentals-go/ent/predicate"
	"rentals-go/ent/rol"
	"rentals-go/ent/usuario"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmpresaUsuarioQuery is the builder for querying EmpresaUsuario entities.
type EmpresaUsuarioQuery struct {
	config
	ctx         *QueryContext
	order       []empresausuario.OrderOption
	inters      []Interceptor
	predicates  []predicate.EmpresaUsuario
	withEmpresa *EmpresaQuery
	withUsuario *UsuarioQuery
	withRol     *RolQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EmpresaUsuarioQuery builder.
func (_q *EmpresaUsuarioQuery) Where(ps ...predicate.EmpresaUsuario) *EmpresaUsuarioQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *EmpresaUsuarioQuery) Limit(limit int) *EmpresaUsuarioQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *EmpresaUsuarioQuery) Offset(offset int) *EmpresaUsuarioQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *EmpresaUsuarioQuery) Unique(unique bool) *EmpresaUsuarioQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *EmpresaUsuarioQuery) Order(o ...empresausuario.OrderOption) *EmpresaUsuarioQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryEmpresa chains the current query on the "empresa" edge.
func (_q *EmpresaUsuarioQuery) QueryEmpresa() *EmpresaQuery {
	query := (&EmpresaClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(empresausuario.Table, empresausuario.FieldID, selector),
			sqlgraph.To(empresa.Table, empresa.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, empresausuario.EmpresaTable, empresausuario.EmpresaColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUsuario chains the current query on the "usuario" edge.
func (_q *EmpresaUsuarioQuery) QueryUsuario() *UsuarioQuery {
	query := (&UsuarioClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(empresausuario.Table, empresausuario.FieldID, selector),
			sqlgraph.To(usuario.Table, usuario.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, empresausuario.UsuarioTable, empresausuario.UsuarioColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRol chains the current query on the "rol" edge.
func (_q *EmpresaUsuarioQuery) QueryRol() *RolQuery {
	query := (&RolClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(empresausuario.Table, empresausuario.FieldID, selector),
			sqlgraph.To(rol.Table, rol.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, empresausuario.RolTable, empresausuario.RolColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EmpresaUsuario entity from the query.
// Returns a *NotFoundError when no EmpresaUsuario was found.
func (_q *EmpresaUsuarioQuery) First(ctx context.Context) (*EmpresaUsuario, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{empresausuario.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *EmpresaUsuarioQuery) FirstX(ctx context.Context) *EmpresaUsuario {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EmpresaUsuario ID from the query.
// Returns a *NotFoundError when no EmpresaUsuario ID was found.
func (_q *EmpresaUsuarioQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{empresausuario.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *EmpresaUsuarioQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EmpresaUsuario entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EmpresaUsuario entity is found.
// Returns a *NotFoundError when no EmpresaUsuario entities are found.
func (_q *EmpresaUsuarioQuery) Only(ctx context.Context) (*EmpresaUsuario, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{empresausuario.Label}
	default:
		return nil, &NotSingularError{empresausuario.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *EmpresaUsuarioQuery) OnlyX(ctx context.Context) *EmpresaUsuario {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EmpresaUsuario ID in the query.
// Returns a *NotSingularError when more than one EmpresaUsuario ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *EmpresaUsuarioQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{empresausuario.Label}
	default:
		err = &NotSingularError{empresausuario.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *EmpresaUsuarioQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EmpresaUsuarios.
func (_q *EmpresaUsuarioQuery) All(ctx context.Context) ([]*EmpresaUsuario, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EmpresaUsuario, *EmpresaUsuarioQuery]()
	return withInterceptors[[]*EmpresaUsuario](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *EmpresaUsuarioQuery) AllX(ctx context.Context) []*EmpresaUsuario {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EmpresaUsuario IDs.
func (_q *EmpresaUsuarioQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(empresausuario.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *EmpresaUsuarioQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *EmpresaUsuarioQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*EmpresaUsuarioQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *EmpresaUsuarioQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *EmpresaUsuarioQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *EmpresaUsuarioQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EmpresaUsuarioQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *EmpresaUsuarioQuery) Clone() *EmpresaUsuarioQuery {
	if _q == nil {
		return nil
	}
	return &EmpresaUsuarioQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]empresausuario.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.EmpresaUsuario{}, _q.predicates...),
		withEmpresa: _q.withEmpresa.Clone(),
		withUsuario: _q.withUsuario.Clone(),
		withRol:     _q.withRol.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithEmpresa tells the query-builder to eager-load the nodes that are connected to
// the "empresa" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EmpresaUsuarioQuery) WithEmpresa(opts ...func(*EmpresaQuery)) *EmpresaUsuarioQuery {
	query := (&EmpresaClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEmpresa = query
	return _q
}

// WithUsuario tells the query-builder to eager-load the nodes that are connected to
// the "usuario" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EmpresaUsuarioQuery) WithUsuario(opts ...func(*UsuarioQuery)) *EmpresaUsuarioQuery {
	query := (&UsuarioClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUsuario = query
	return _q
}

// WithRol tells the query-builder to eager-load the nodes that are connected to
// the "rol" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EmpresaUsuarioQuery) WithRol(opts ...func(*RolQuery)) *EmpresaUsuarioQuery {
	query := (&RolClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRol = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreadoEn time.Time `json:"creado_en,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EmpresaUsuario.Query().
//		GroupBy(empresausuario.FieldCreadoEn).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *EmpresaUsuarioQuery) GroupBy(field string, fields ...string) *EmpresaUsuarioGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EmpresaUsuarioGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = empresausuario.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreadoEn time.Time `json:"creado_en,omitempty"`
//	}
//
//	client.EmpresaUsuario.Query().
//		Select(empresausuario.FieldCreadoEn).
//		Scan(ctx, &v)
func (_q *EmpresaUsuarioQuery) Select(fields ...string) *EmpresaUsuarioSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &EmpresaUsuarioSelect{EmpresaUsuarioQuery: _q}
	sbuild.label = empresausuario.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EmpresaUsuarioSelect configured with the given aggregations.
func (_q *EmpresaUsuarioQuery) Aggregate(fns ...AggregateFunc) *EmpresaUsuarioSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *EmpresaUsuarioQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !empresausuario.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *EmpresaUsuarioQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EmpresaUsuario, error) {
	var (
		nodes       = []*EmpresaUsuario{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withEmpresa != nil,
			_q.withUsuario != nil,
			_q.withRol != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EmpresaUsuario).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EmpresaUsuario{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withEmpresa; query != nil {
		if err := _q.loadEmpresa(ctx, query, nodes, nil,
			func(n *EmpresaUsuario, e *Empresa) { n.Edges.Empresa = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUsuario; query != nil {
		if err := _q.loadUsuario(ctx, query, nodes, nil,
			func(n *EmpresaUsuario, e *Usuario) { n.Edges.Usuario = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRol; query != nil {
		if err := _q.loadRol(ctx, query, nodes, nil,
			func(n *EmpresaUsuario, e *Rol) { n.Edges.Rol = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *EmpresaUsuarioQuery) loadEmpresa(ctx context.Context, query *EmpresaQuery, nodes []*EmpresaUsuario, init func(*EmpresaUsuario), assign func(*EmpresaUsuario, *Empresa)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*EmpresaUsuario)
	for i := range nodes {
		fk := nodes[i].EmpresaID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(empresa.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "empresa_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *EmpresaUsuarioQuery) loadUsuario(ctx context.Context, query *UsuarioQuery, nodes []*EmpresaUsuario, init func(*EmpresaUsuario), assign func(*EmpresaUsuario, *Usuario)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*EmpresaUsuario)
	for i := range nodes {
		fk := nodes[i].UsuarioID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(usuario.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "usuario_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *EmpresaUsuarioQuery) loadRol(ctx context.Context, query *RolQuery, nodes []*EmpresaUsuario, init func(*EmpresaUsuario), assign func(*EmpresaUsuario, *Rol)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*EmpresaUsuario)
	for i := range nodes {
		fk := nodes[i].RolID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(rol.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "rol_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *EmpresaUsuarioQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *EmpresaUsuarioQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(empresausuario.Table, empresausuario.Columns, sqlgraph.NewFieldSpec(empresausuario.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, empresausuario.FieldID)
		for i := range fields {
			if fields[i] != empresausuario.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withEmpresa != nil {
			_spec.Node.AddColumnOnce(empresausuario.FieldEmpresaID)
		}
		if _q.withUsuario != nil {
			_spec.Node.AddColumnOnce(empresausuario.FieldUsuarioID)
		}
		if _q.withRol != nil {
			_spec.Node.AddColumnOnce(empresausuario.FieldRolID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *EmpresaUsuarioQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(empresausuario.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = empresausuario.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EmpresaUsuarioGroupBy is the group-by builder for EmpresaUsuario entities.
type EmpresaUsuarioGroupBy struct {
	selector
	build *EmpresaUsuarioQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *EmpresaUsuarioGroupBy) Aggregate(fns ...AggregateFunc) *EmpresaUsuarioGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *EmpresaUsuarioGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EmpresaUsuarioQuery, *EmpresaUsuarioGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *EmpresaUsuarioGroupBy) sqlScan(ctx context.Context, root *EmpresaUsuarioQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EmpresaUsuarioSelect is the builder for selecting fields of EmpresaUsuario entities.
type EmpresaUsuarioSelect struct {
	*EmpresaUsuarioQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *EmpresaUsuarioSelect) Aggregate(fns ...AggregateFunc) *EmpresaUsuarioSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *EmpresaUsuarioSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EmpresaUsuarioQuery, *EmpresaUsuarioSelect](ctx, _s.EmpresaUsuarioQuery, _s, _s.inters, v)
}

func (_s *EmpresaUsuarioSelect) sqlScan(ctx context.Context, root *EmpresaUsuarioQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
