// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"rentals-go/ent/empresa"
	"rentals-go/ent/empresausuario"
	"rentals-go/ent/rol"
	"rentals-go/ent/usuario"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// EmpresaUsuario is the model entity for the EmpresaUsuario schema.
type EmpresaUsuario struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreadoEn holds the value of the "creado_en" field.
	CreadoEn time.Time `json:"creado_en,omitempty"`
	// ActualizadoEn holds the value of the "actualizado_en" field.
	ActualizadoEn time.Time `json:"actualizado_en,omitempty"`
	// EmpresaID holds the value of the "empresa_id" field.
	EmpresaID int `json:"empresa_id,omitempty"`
	// UsuarioID holds the value of the "usuario_id" field.
	UsuarioID int `json:"usuario_id,omitempty"`
	// RolID holds the value of the "rol_id" field.
	RolID int `json:"rol_id,omitempty"`
	// Principal holds the value of the "principal" field.
	Principal bool `json:"principal,omitempty"`
	// Estado holds the value of the "estado" field.
	Estado empresausuario.Estado `json:"estado,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EmpresaUsuarioQuery when eager-loading is set.
	Edges        EmpresaUsuarioEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EmpresaUsuarioEdges holds the relations/edges for other nodes in the graph.
type EmpresaUsuarioEdges struct {
	// Empresa holds the value of the empresa edge.
	Empresa *Empresa `json:"empresa,omitempty"`
	// Usuario holds the value of the usuario edge.
	Usuario *Usuario `json:"usuario,omitempty"`
	// Rol holds the value of the rol edge.
	Rol *Rol `json:"rol,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// EmpresaOrErr returns the Empresa value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EmpresaUsuarioEdges) EmpresaOrErr() (*Empresa, error) {
	if e.Empresa != nil {
		return e.Empresa, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: empresa.Label}
	}
	return nil, &NotLoadedError{edge: "empresa"}
}

// UsuarioOrErr returns the Usuario value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EmpresaUsuarioEdges) UsuarioOrErr() (*Usuario, error) {
	if e.Usuario != nil {
		return e.Usuario, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: usuario.Label}
	}
	return nil, &NotLoadedError{edge: "usuario"}
}

// RolOrErr returns the Rol value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EmpresaUsuarioEdges) RolOrErr() (*Rol, error) {
	if e.Rol != nil {
		return e.Rol, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: rol.Label}
	}
	return nil, &NotLoadedError{edge: "rol"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EmpresaUsuario) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case empresausuario.FieldPrincipal:
			values[i] = new(sql.NullBool)
		case empresausuario.FieldID, empresausuario.FieldEmpresaID, empresausuario.FieldUsuarioID, empresausuario.FieldRolID:
			values[i] = new(sql.NullInt64)
		case empresausuario.FieldEstado:
			values[i] = new(sql.NullString)
		case empresausuario.FieldCreadoEn, empresausuario.FieldActualizadoEn:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EmpresaUsuario fields.
func (_m *EmpresaUsuario) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case empresausuario.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case empresausuario.FieldCreadoEn:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field creado_en", values[i])
			} else if value.Valid {
				_m.CreadoEn = value.Time
			}
		case empresausuario.FieldActualizadoEn:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field actualizado_en", values[i])
			} else if value.Valid {
				_m.ActualizadoEn = value.Time
			}
		case empresausuario.FieldEmpresaID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field empresa_id", values[i])
			} else if value.Valid {
				_m.EmpresaID = int(value.Int64)
			}
		case empresausuario.FieldUsuarioID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usuario_id", values[i])
			} else if value.Valid {
				_m.UsuarioID = int(value.Int64)
			}
		case empresausuario.FieldRolID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rol_id", values[i])
			} else if value.Valid {
				_m.RolID = int(value.Int64)
			}
		case empresausuario.FieldPrincipal:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field principal", values[i])
			} else if value.Valid {
				_m.Principal = value.Bool
			}
		case empresausuario.FieldEstado:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field estado", values[i])
			} else if value.Valid {
				_m.Estado = empresausuario.Estado(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EmpresaUsuario.
// This includes values selected through modifiers, order, etc.
func (_m *EmpresaUsuario) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEmpresa queries the "empresa" edge of the EmpresaUsuario entity.
func (_m *EmpresaUsuario) QueryEmpresa() *EmpresaQuery {
	return NewEmpresaUsuarioClient(_m.config).QueryEmpresa(_m)
}

// QueryUsuario queries the "usuario" edge of the EmpresaUsuario entity.
func (_m *EmpresaUsuario) QueryUsuario() *UsuarioQuery {
	return NewEmpresaUsuarioClient(_m.config).QueryUsuario(_m)
}

// QueryRol queries the "rol" edge of the EmpresaUsuario entity.
func (_m *EmpresaUsuario) QueryRol() *RolQuery {
	return NewEmpresaUsuarioClient(_m.config).QueryRol(_m)
}

// Update returns a builder for updating this EmpresaUsuario.
// Note that you need to call EmpresaUsuario.Unwrap() before calling this method if this EmpresaUsuario
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EmpresaUsuario) Update() *EmpresaUsuarioUpdateOne {
	return NewEmpresaUsuarioClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EmpresaUsuario entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EmpresaUsuario) Unwrap() *EmpresaUsuario {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EmpresaUsuario is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EmpresaUsuario) String() string {
	var builder strings.Builder
	builder.WriteString("EmpresaUsuario(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("creado_en=")
	builder.WriteString(_m.CreadoEn.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("actualizado_en=")
	builder.WriteString(_m.ActualizadoEn.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("empresa_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmpresaID))
	builder.WriteString(", ")
	builder.WriteString("usuario_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsuarioID))
	builder.WriteString(", ")
	builder.WriteString("rol_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RolID))
	builder.WriteString(", ")
	builder.WriteString("principal=")
	builder.WriteString(fmt.Sprintf("%v", _m.Principal))
	builder.WriteString(", ")
	builder.WriteString("estado=")
	builder.WriteString(fmt.Sprintf("%v", _m.Estado))
	builder.WriteByte(')')
	return builder.String()
}

// EmpresaUsuarios is a parsable slice of EmpresaUsuario.
type EmpresaUsuarios []*EmpresaUsuario
