// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"rentals-go/ent/empresa"
	"rentals-go/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmpresaDelete is the builder for deleting a Empresa entity.
type EmpresaDelete struct {
	config
	hooks    []Hook
	mutation *EmpresaMutation
}

// Where appends a list predicates to the EmpresaDelete builder.
func (_d *EmpresaDelete) Where(ps ...predicate.Empresa) *EmpresaDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EmpresaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EmpresaDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EmpresaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(empresa.Table, sqlgraph.NewFieldSpec(empresa.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EmpresaDeleteOne is the builder for deleting a single Empresa entity.
type EmpresaDeleteOne struct {
	_d *EmpresaDelete
}

// Where appends a list predicates to the EmpresaDelete builder.
func (_d *EmpresaDeleteOne) Where(ps ...predicate.Empresa) *EmpresaDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EmpresaDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{empresa.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EmpresaDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
