// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rentals-go/ent/empresa"
	"rentals-go/ent/horario"
	"rentals-go/ent/usuario"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HorarioCreate is the builder for creating a Horario entity.
type HorarioCreate struct {
	config
	mutation *HorarioMutation
	hooks    []Hook
}

// SetCreadoEn sets the "creado_en" field.
func (_c *HorarioCreate) SetCreadoEn(v time.Time) *HorarioCreate {
	_c.mutation.SetCreadoEn(v)
	return _c
}

// SetNillableCreadoEn sets the "creado_en" field if the given value is not nil.
func (_c *HorarioCreate) SetNillableCreadoEn(v *time.Time) *HorarioCreate {
	if v != nil {
		_c.SetCreadoEn(*v)
	}
	return _c
}

// SetEmpresaID sets the "empresa_id" field.
func (_c *HorarioCreate) SetEmpresaID(v int) *HorarioCreate {
	_c.mutation.SetEmpresaID(v)
	return _c
}

// SetUsuarioID sets the "usuario_id" field.
func (_c *HorarioCreate) SetUsuarioID(v int) *HorarioCreate {
	_c.mutation.SetUsuarioID(v)
	return _c
}

// SetHoraEntrada sets the "hora_entrada" field.
func (_c *HorarioCreate) SetHoraEntrada(v string) *HorarioCreate {
	_c.mutation.SetHoraEntrada(v)
	return _c
}

// SetNillableHoraEntrada sets the "hora_entrada" field if the given value is not nil.
func (_c *HorarioCreate) SetNillableHoraEntrada(v *string) *HorarioCreate {
	if v != nil {
		_c.SetHoraEntrada(*v)
	}
	return _c
}

// SetHoraSalida sets the "hora_salida" field.
func (_c *HorarioCreate) SetHoraSalida(v string) *HorarioCreate {
	_c.mutation.SetHoraSalida(v)
	return _c
}

// SetNillableHoraSalida sets the "hora_salida" field if the given value is not nil.
func (_c *HorarioCreate) SetNillableHoraSalida(v *string) *HorarioCreate {
	if v != nil {
		_c.SetHoraSalida(*v)
	}
	return _c
}

// SetToleranciaMinutos sets the "tolerancia_minutos" field.
func (_c *HorarioCreate) SetToleranciaMinutos(v int) *HorarioCreate {
	_c.mutation.SetToleranciaMinutos(v)
	return _c
}

// SetNillableToleranciaMinutos sets the "tolerancia_minutos" field if the given value is not nil.
func (_c *HorarioCreate) SetNillableToleranciaMinutos(v *int) *HorarioCreate {
	if v != nil {
		_c.SetToleranciaMinutos(*v)
	}
	return _c
}

// SetDiasLaborables sets the "dias_laborables" field.
func (_c *HorarioCreate) SetDiasLaborables(v string) *HorarioCreate {
	_c.mutation.SetDiasLaborables(v)
	return _c
}

// SetNillableDiasLaborables sets the "dias_laborables" field if the given value is not nil.
func (_c *HorarioCreate) SetNillableDiasLaborables(v *string) *HorarioCreate {
	if v != nil {
		_c.SetDiasLaborables(*v)
	}
	return _c
}

// SetEmpresa sets the "empresa" edge to the Empresa entity.
func (_c *HorarioCreate) SetEmpresa(v *Empresa) *HorarioCreate {
	return _c.SetEmpresaID(v.ID)
}

// SetUsuario sets the "usuario" edge to the Usuario entity.
func (_c *HorarioCreate) SetUsuario(v *Usuario) *HorarioCreate {
	return _c.SetUsuarioID(v.ID)
}

// Mutation returns the HorarioMutation object of the builder.
func (_c *HorarioCreate) Mutation() *HorarioMutation {
	return _c.mutation
}

// Save creates the Horario in the database.
func (_c *HorarioCreate) Save(ctx context.Context) (*Horario, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HorarioCreate) SaveX(ctx context.Context) *Horario {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HorarioCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HorarioCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HorarioCreate) defaults() {
	if _, ok := _c.mutation.CreadoEn(); !ok {
		v := horario.DefaultCreadoEn()
		_c.mutation.SetCreadoEn(v)
	}
	if _, ok := _c.mutation.HoraEntrada(); !ok {
		v := horario.DefaultHoraEntrada
		_c.mutation.SetHoraEntrada(v)
	}
	if _, ok := _c.mutation.HoraSalida(); !ok {
		v := horario.DefaultHoraSalida
		_c.mutation.SetHoraSalida(v)
	}
	if _, ok := _c.mutation.ToleranciaMinutos(); !ok {
		v := horario.DefaultToleranciaMinutos
		_c.mutation.SetToleranciaMinutos(v)
	}
	if _, ok := _c.mutation.DiasLaborables(); !ok {
		v := horario.DefaultDiasLaborables
		_c.mutation.SetDiasLaborables(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HorarioCreate) check() error {
	if _, ok := _c.mutation.CreadoEn(); !ok {
		return &ValidationError{Name: "creado_en", err: errors.New(`ent: missing required field "Horario.creado_en"`)}
	}
	if _, ok := _c.mutation.EmpresaID(); !ok {
		return &ValidationError{Name: "empresa_id", err: errors.New(`ent: missing required field "Horario.empresa_id"`)}
	}
	if _, ok := _c.mutation.UsuarioID(); !ok {
		return &ValidationError{Name: "usuario_id", err: errors.New(`ent: missing required field "Horario.usuario_id"`)}
	}
	if _, ok := _c.mutation.HoraEntrada(); !ok {
		return &ValidationError{Name: "hora_entrada", err: errors.New(`ent: missing required field "Horario.hora_entrada"`)}
	}
	if _, ok := _c.mutation.HoraSalida(); !ok {
		return &ValidationError{Name: "hora_salida", err: errors.New(`ent: missing required field "Horario.hora_salida"`)}
	}
	if _, ok := _c.mutation.ToleranciaMinutos(); !ok {
		return &ValidationError{Name: "tolerancia_minutos", err: errors.New(`ent: missing required field "Horario.tolerancia_minutos"`)}
	}
	if _, ok := _c.mutation.DiasLaborables(); !ok {
		return &ValidationError{Name: "dias_laborables", err: errors.New(`ent: missing required field "Horario.dias_laborables"`)}
	}
	if len(_c.mutation.EmpresaIDs()) == 0 {
		return &ValidationError{Name: "empresa", err: errors.New(`ent: missing required edge "Horario.empresa"`)}
	}
	if len(_c.mutation.UsuarioIDs()) == 0 {
		return &ValidationError{Name: "usuario", err: errors.New(`ent: missing required edge "Horario.usuario"`)}
	}
	return nil
}

func (_c *HorarioCreate) sqlSave(ctx context.Context) (*Horario, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HorarioCreate) createSpec() (*Horario, *sqlgraph.CreateSpec) {
	var (
		_node = &Horario{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(horario.Table, sqlgraph.NewFieldSpec(horario.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreadoEn(); ok {
		_spec.SetField(horario.FieldCreadoEn, field.TypeTime, value)
		_node.CreadoEn = value
	}
	if value, ok := _c.mutation.HoraEntrada(); ok {
		_spec.SetField(horario.FieldHoraEntrada, field.TypeString, value)
		_node.HoraEntrada = value
	}
	if value, ok := _c.mutation.HoraSalida(); ok {
		_spec.SetField(horario.FieldHoraSalida, field.TypeString, value)
		_node.HoraSalida = value
	}
	if value, ok := _c.mutation.ToleranciaMinutos(); ok {
		_spec.SetField(horario.FieldToleranciaMinutos, field.TypeInt, value)
		_node.ToleranciaMinutos = value
	}
	if value, ok := _c.mutation.DiasLaborables(); ok {
		_spec.SetField(horario.FieldDiasLaborables, field.TypeString, value)
		_node.DiasLaborables = value
	}
	if nodes := _c.mutation.EmpresaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   horario.EmpresaTable,
			Columns: []string{horario.EmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresa.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EmpresaID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsuarioIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   horario.UsuarioTable,
			Columns: []string{horario.UsuarioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usuario.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UsuarioID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HorarioCreateBulk is the builder for creating many Horario entities in bulk.
type HorarioCreateBulk struct {
	config
	err      error
	builders []*HorarioCreate
}

// Save creates the Horario entities in the database.
func (_c *HorarioCreateBulk) Save(ctx context.Context) ([]*Horario, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Horario, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HorarioMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HorarioCreateBulk) SaveX(ctx context.Context) []*Horario {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HorarioCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HorarioCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
