// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rentals-go/ent/empresa"
	"rentals-go/ent/gasto"
	"rentals-go/ent/movimientocaja"
	"rentals-go/ent/pago"
	"rentals-go/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MovimientoCajaUpdate is the builder for updating MovimientoCaja entities.
type MovimientoCajaUpdate struct {
	config
	hooks    []Hook
	mutation *MovimientoCajaMutation
}

// Where appends a list predicates to the MovimientoCajaUpdate builder.
func (_u *MovimientoCajaUpdate) Where(ps ...predicate.MovimientoCaja) *MovimientoCajaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmpresaID sets the "empresa_id" field.
func (_u *MovimientoCajaUpdate) SetEmpresaID(v int) *MovimientoCajaUpdate {
	_u.mutation.SetEmpresaID(v)
	return _u
}

// SetNillableEmpresaID sets the "empresa_id" field if the given value is not nil.
func (_u *MovimientoCajaUpdate) SetNillableEmpresaID(v *int) *MovimientoCajaUpdate {
	if v != nil {
		_u.SetEmpresaID(*v)
	}
	return _u
}

// SetPagoID sets the "pago_id" field.
func (_u *MovimientoCajaUpdate) SetPagoID(v int) *MovimientoCajaUpdate {
	_u.mutation.SetPagoID(v)
	return _u
}

// SetNillablePagoID sets the "pago_id" field if the given value is not nil.
func (_u *MovimientoCajaUpdate) SetNillablePagoID(v *int) *MovimientoCajaUpdate {
	if v != nil {
		_u.SetPagoID(*v)
	}
	return _u
}

// ClearPagoID clears the value of the "pago_id" field.
func (_u *MovimientoCajaUpdate) ClearPagoID() *MovimientoCajaUpdate {
	_u.mutation.ClearPagoID()
	return _u
}

// SetGastoID sets the "gasto_id" field.
func (_u *MovimientoCajaUpdate) SetGastoID(v int) *MovimientoCajaUpdate {
	_u.mutation.SetGastoID(v)
	return _u
}

// SetNillableGastoID sets the "gasto_id" field if the given value is not nil.
func (_u *MovimientoCajaUpdate) SetNillableGastoID(v *int) *MovimientoCajaUpdate {
	if v != nil {
		_u.SetGastoID(*v)
	}
	return _u
}

// ClearGastoID clears the value of the "gasto_id" field.
func (_u *MovimientoCajaUpdate) ClearGastoID() *MovimientoCajaUpdate {
	_u.mutation.ClearGastoID()
	return _u
}

// SetTipo sets the "tipo" field.
func (_u *MovimientoCajaUpdate) SetTipo(v movimientocaja.Tipo) *MovimientoCajaUpdate {
	_u.mutation.SetTipo(v)
	return _u
}

// SetNillableTipo sets the "tipo" field if the given value is not nil.
func (_u *MovimientoCajaUpdate) SetNillableTipo(v *movimientocaja.Tipo) *MovimientoCajaUpdate {
	if v != nil {
		_u.SetTipo(*v)
	}
	return _u
}

// SetConcepto sets the "concepto" field.
func (_u *MovimientoCajaUpdate) SetConcepto(v string) *MovimientoCajaUpdate {
	_u.mutation.SetConcepto(v)
	return _u
}

// SetNillableConcepto sets the "concepto" field if the given value is not nil.
func (_u *MovimientoCajaUpdate) SetNillableConcepto(v *string) *MovimientoCajaUpdate {
	if v != nil {
		_u.SetConcepto(*v)
	}
	return _u
}

// SetFechaMovimiento sets the "fecha_movimiento" field.
func (_u *MovimientoCajaUpdate) SetFechaMovimiento(v time.Time) *MovimientoCajaUpdate {
	_u.mutation.SetFechaMovimiento(v)
	return _u
}

// SetNillableFechaMovimiento sets the "fecha_movimiento" field if the given value is not nil.
func (_u *MovimientoCajaUpdate) SetNillableFechaMovimiento(v *time.Time) *MovimientoCajaUpdate {
	if v != nil {
		_u.SetFechaMovimiento(*v)
	}
	return _u
}

// SetMoneda sets the "moneda" field.
func (_u *MovimientoCajaUpdate) SetMoneda(v string) *MovimientoCajaUpdate {
	_u.mutation.SetMoneda(v)
	return _u
}

// SetNillableMoneda sets the "moneda" field if the given value is not nil.
func (_u *MovimientoCajaUpdate) SetNillableMoneda(v *string) *MovimientoCajaUpdate {
	if v != nil {
		_u.SetMoneda(*v)
	}
	return _u
}

// SetMonto sets the "monto" field.
func (_u *MovimientoCajaUpdate) SetMonto(v int64) *MovimientoCajaUpdate {
	_u.mutation.ResetMonto()
	_u.mutation.SetMonto(v)
	return _u
}

// SetNillableMonto sets the "monto" field if the given value is not nil.
func (_u *MovimientoCajaUpdate) SetNillableMonto(v *int64) *MovimientoCajaUpdate {
	if v != nil {
		_u.SetMonto(*v)
	}
	return _u
}

// AddMonto adds value to the "monto" field.
func (_u *MovimientoCajaUpdate) AddMonto(v int64) *MovimientoCajaUpdate {
	_u.mutation.AddMonto(v)
	return _u
}

// SetMetodo sets the "metodo" field.
func (_u *MovimientoCajaUpdate) SetMetodo(v movimientocaja.Metodo) *MovimientoCajaUpdate {
	_u.mutation.SetMetodo(v)
	return _u
}

// SetNillableMetodo sets the "metodo" field if the given value is not nil.
func (_u *MovimientoCajaUpdate) SetNillableMetodo(v *movimientocaja.Metodo) *MovimientoCajaUpdate {
	if v != nil {
		_u.SetMetodo(*v)
	}
	return _u
}

// SetReferencia sets the "referencia" field.
func (_u *MovimientoCajaUpdate) SetReferencia(v string) *MovimientoCajaUpdate {
	_u.mutation.SetReferencia(v)
	return _u
}

// SetNillableReferencia sets the "referencia" field if the given value is not nil.
func (_u *MovimientoCajaUpdate) SetNillableReferencia(v *string) *MovimientoCajaUpdate {
	if v != nil {
		_u.SetReferencia(*v)
	}
	return _u
}

// ClearReferencia clears the value of the "referencia" field.
func (_u *MovimientoCajaUpdate) ClearReferencia() *MovimientoCajaUpdate {
	_u.mutation.ClearReferencia()
	return _u
}

// SetObservaciones sets the "observaciones" field.
func (_u *MovimientoCajaUpdate) SetObservaciones(v string) *MovimientoCajaUpdate {
	_u.mutation.SetObservaciones(v)
	return _u
}

// SetNillableObservaciones sets the "observaciones" field if the given value is not nil.
func (_u *MovimientoCajaUpdate) SetNillableObservaciones(v *string) *MovimientoCajaUpdate {
	if v != nil {
		_u.SetObservaciones(*v)
	}
	return _u
}

// ClearObservaciones clears the value of the "observaciones" field.
func (_u *MovimientoCajaUpdate) ClearObservaciones() *MovimientoCajaUpdate {
	_u.mutation.ClearObservaciones()
	return _u
}

// SetEmpresa sets the "empresa" edge to the Empresa entity.
func (_u *MovimientoCajaUpdate) SetEmpresa(v *Empresa) *MovimientoCajaUpdate {
	return _u.SetEmpresaID(v.ID)
}

// SetPago sets the "pago" edge to the Pago entity.
func (_u *MovimientoCajaUpdate) SetPago(v *Pago) *MovimientoCajaUpdate {
	return _u.SetPagoID(v.ID)
}

// SetGasto sets the "gasto" edge to the Gasto entity.
func (_u *MovimientoCajaUpdate) SetGasto(v *Gasto) *MovimientoCajaUpdate {
	return _u.SetGastoID(v.ID)
}

// Mutation returns the MovimientoCajaMutation object of the builder.
func (_u *MovimientoCajaUpdate) Mutation() *MovimientoCajaMutation {
	return _u.mutation
}

// ClearEmpresa clears the "empresa" edge to the Empresa entity.
func (_u *MovimientoCajaUpdate) ClearEmpresa() *MovimientoCajaUpdate {
	_u.mutation.ClearEmpresa()
	return _u
}

// ClearPago clears the "pago" edge to the Pago entity.
func (_u *MovimientoCajaUpdate) ClearPago() *MovimientoCajaUpdate {
	_u.mutation.ClearPago()
	return _u
}

// ClearGasto clears the "gasto" edge to the Gasto entity.
func (_u *MovimientoCajaUpdate) ClearGasto() *MovimientoCajaUpdate {
	_u.mutation.ClearGasto()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MovimientoCajaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MovimientoCajaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MovimientoCajaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MovimientoCajaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MovimientoCajaUpdate) check() error {
	if v, ok := _u.mutation.Tipo(); ok {
		if err := movimientocaja.TipoValidator(v); err != nil {
			return &ValidationError{Name: "tipo", err: fmt.Errorf(`ent: validator failed for field "MovimientoCaja.tipo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Concepto(); ok {
		if err := movimientocaja.ConceptoValidator(v); err != nil {
			return &ValidationError{Name: "concepto", err: fmt.Errorf(`ent: validator failed for field "MovimientoCaja.concepto": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Moneda(); ok {
		if err := movimientocaja.MonedaValidator(v); err != nil {
			return &ValidationError{Name: "moneda", err: fmt.Errorf(`ent: validator failed for field "MovimientoCaja.moneda": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Metodo(); ok {
		if err := movimientocaja.MetodoValidator(v); err != nil {
			return &ValidationError{Name: "metodo", err: fmt.Errorf(`ent: validator failed for field "MovimientoCaja.metodo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Referencia(); ok {
		if err := movimientocaja.ReferenciaValidator(v); err != nil {
			return &ValidationError{Name: "referencia", err: fmt.Errorf(`ent: validator failed for field "MovimientoCaja.referencia": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Observaciones(); ok {
		if err := movimientocaja.ObservacionesValidator(v); err != nil {
			return &ValidationError{Name: "observaciones", err: fmt.Errorf(`ent: validator failed for field "MovimientoCaja.observaciones": %w`, err)}
		}
	}
	if _u.mutation.EmpresaCleared() && len(_u.mutation.EmpresaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MovimientoCaja.empresa"`)
	}
	return nil
}

func (_u *MovimientoCajaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(movimientocaja.Table, movimientocaja.Columns, sqlgraph.NewFieldSpec(movimientocaja.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tipo(); ok {
		_spec.SetField(movimientocaja.FieldTipo, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Concepto(); ok {
		_spec.SetField(movimientocaja.FieldConcepto, field.TypeString, value)
	}
	if value, ok := _u.mutation.FechaMovimiento(); ok {
		_spec.SetField(movimientocaja.FieldFechaMovimiento, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Moneda(); ok {
		_spec.SetField(movimientocaja.FieldMoneda, field.TypeString, value)
	}
	if value, ok := _u.mutation.Monto(); ok {
		_spec.SetField(movimientocaja.FieldMonto, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMonto(); ok {
		_spec.AddField(movimientocaja.FieldMonto, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Metodo(); ok {
		_spec.SetField(movimientocaja.FieldMetodo, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Referencia(); ok {
		_spec.SetField(movimientocaja.FieldReferencia, field.TypeString, value)
	}
	if _u.mutation.ReferenciaCleared() {
		_spec.ClearField(movimientocaja.FieldReferencia, field.TypeString)
	}
	if value, ok := _u.mutation.Observaciones(); ok {
		_spec.SetField(movimientocaja.FieldObservaciones, field.TypeString, value)
	}
	if _u.mutation.ObservacionesCleared() {
		_spec.ClearField(movimientocaja.FieldObservaciones, field.TypeString)
	}
	if _u.mutation.EmpresaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   movimientocaja.EmpresaTable,
			Columns: []string{movimientocaja.EmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresa.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmpresaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   movimientocaja.EmpresaTable,
			Columns: []string{movimientocaja.EmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresa.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PagoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   movimientocaja.PagoTable,
			Columns: []string{movimientocaja.PagoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pago.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PagoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   movimientocaja.PagoTable,
			Columns: []string{movimientocaja.PagoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pago.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GastoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   movimientocaja.GastoTable,
			Columns: []string{movimientocaja.GastoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gasto.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GastoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   movimientocaja.GastoTable,
			Columns: []string{movimientocaja.GastoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gasto.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{movimientocaja.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MovimientoCajaUpdateOne is the builder for updating a single MovimientoCaja entity.
type MovimientoCajaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MovimientoCajaMutation
}

// SetEmpresaID sets the "empresa_id" field.
func (_u *MovimientoCajaUpdateOne) SetEmpresaID(v int) *MovimientoCajaUpdateOne {
	_u.mutation.SetEmpresaID(v)
	return _u
}

// SetNillableEmpresaID sets the "empresa_id" field if the given value is not nil.
func (_u *MovimientoCajaUpdateOne) SetNillableEmpresaID(v *int) *MovimientoCajaUpdateOne {
	if v != nil {
		_u.SetEmpresaID(*v)
	}
	return _u
}

// SetPagoID sets the "pago_id" field.
func (_u *MovimientoCajaUpdateOne) SetPagoID(v int) *MovimientoCajaUpdateOne {
	_u.mutation.SetPagoID(v)
	return _u
}

// SetNillablePagoID sets the "pago_id" field if the given value is not nil.
func (_u *MovimientoCajaUpdateOne) SetNillablePagoID(v *int) *MovimientoCajaUpdateOne {
	if v != nil {
		_u.SetPagoID(*v)
	}
	return _u
}

// ClearPagoID clears the value of the "pago_id" field.
func (_u *MovimientoCajaUpdateOne) ClearPagoID() *MovimientoCajaUpdateOne {
	_u.mutation.ClearPagoID()
	return _u
}

// SetGastoID sets the "gasto_id" field.
func (_u *MovimientoCajaUpdateOne) SetGastoID(v int) *MovimientoCajaUpdateOne {
	_u.mutation.SetGastoID(v)
	return _u
}

// SetNillableGastoID sets the "gasto_id" field if the given value is not nil.
func (_u *MovimientoCajaUpdateOne) SetNillableGastoID(v *int) *MovimientoCajaUpdateOne {
	if v != nil {
		_u.SetGastoID(*v)
	}
	return _u
}

// ClearGastoID clears the value of the "gasto_id" field.
func (_u *MovimientoCajaUpdateOne) ClearGastoID() *MovimientoCajaUpdateOne {
	_u.mutation.ClearGastoID()
	return _u
}

// SetTipo sets the "tipo" field.
func (_u *MovimientoCajaUpdateOne) SetTipo(v movimientocaja.Tipo) *MovimientoCajaUpdateOne {
	_u.mutation.SetTipo(v)
	return _u
}

// SetNillableTipo sets the "tipo" field if the given value is not nil.
func (_u *MovimientoCajaUpdateOne) SetNillableTipo(v *movimientocaja.Tipo) *MovimientoCajaUpdateOne {
	if v != nil {
		_u.SetTipo(*v)
	}
	return _u
}

// SetConcepto sets the "concepto" field.
func (_u *MovimientoCajaUpdateOne) SetConcepto(v string) *MovimientoCajaUpdateOne {
	_u.mutation.SetConcepto(v)
	return _u
}

// SetNillableConcepto sets the "concepto" field if the given value is not nil.
func (_u *MovimientoCajaUpdateOne) SetNillableConcepto(v *string) *MovimientoCajaUpdateOne {
	if v != nil {
		_u.SetConcepto(*v)
	}
	return _u
}

// SetFechaMovimiento sets the "fecha_movimiento" field.
func (_u *MovimientoCajaUpdateOne) SetFechaMovimiento(v time.Time) *MovimientoCajaUpdateOne {
	_u.mutation.SetFechaMovimiento(v)
	return _u
}

// SetNillableFechaMovimiento sets the "fecha_movimiento" field if the given value is not nil.
func (_u *MovimientoCajaUpdateOne) SetNillableFechaMovimiento(v *time.Time) *MovimientoCajaUpdateOne {
	if v != nil {
		_u.SetFechaMovimiento(*v)
	}
	return _u
}

// SetMoneda sets the "moneda" field.
func (_u *MovimientoCajaUpdateOne) SetMoneda(v string) *MovimientoCajaUpdateOne {
	_u.mutation.SetMoneda(v)
	return _u
}

// SetNillableMoneda sets the "moneda" field if the given value is not nil.
func (_u *MovimientoCajaUpdateOne) SetNillableMoneda(v *string) *MovimientoCajaUpdateOne {
	if v != nil {
		_u.SetMoneda(*v)
	}
	return _u
}

// SetMonto sets the "monto" field.
func (_u *MovimientoCajaUpdateOne) SetMonto(v int64) *MovimientoCajaUpdateOne {
	_u.mutation.ResetMonto()
	_u.mutation.SetMonto(v)
	return _u
}

// SetNillableMonto sets the "monto" field if the given value is not nil.
func (_u *MovimientoCajaUpdateOne) SetNillableMonto(v *int64) *MovimientoCajaUpdateOne {
	if v != nil {
		_u.SetMonto(*v)
	}
	return _u
}

// AddMonto adds value to the "monto" field.
func (_u *MovimientoCajaUpdateOne) AddMonto(v int64) *MovimientoCajaUpdateOne {
	_u.mutation.AddMonto(v)
	return _u
}

// SetMetodo sets the "metodo" field.
func (_u *MovimientoCajaUpdateOne) SetMetodo(v movimientocaja.Metodo) *MovimientoCajaUpdateOne {
	_u.mutation.SetMetodo(v)
	return _u
}

// SetNillableMetodo sets the "metodo" field if the given value is not nil.
func (_u *MovimientoCajaUpdateOne) SetNillableMetodo(v *movimientocaja.Metodo) *MovimientoCajaUpdateOne {
	if v != nil {
		_u.SetMetodo(*v)
	}
	return _u
}

// SetReferencia sets the "referencia" field.
func (_u *MovimientoCajaUpdateOne) SetReferencia(v string) *MovimientoCajaUpdateOne {
	_u.mutation.SetReferencia(v)
	return _u
}

// SetNillableReferencia sets the "referencia" field if the given value is not nil.
func (_u *MovimientoCajaUpdateOne) SetNillableReferencia(v *string) *MovimientoCajaUpdateOne {
	if v != nil {
		_u.SetReferencia(*v)
	}
	return _u
}

// ClearReferencia clears the value of the "referencia" field.
func (_u *MovimientoCajaUpdateOne) ClearReferencia() *MovimientoCajaUpdateOne {
	_u.mutation.ClearReferencia()
	return _u
}

// SetObservaciones sets the "observaciones" field.
func (_u *MovimientoCajaUpdateOne) SetObservaciones(v string) *MovimientoCajaUpdateOne {
	_u.mutation.SetObservaciones(v)
	return _u
}

// SetNillableObservaciones sets the "observaciones" field if the given value is not nil.
func (_u *MovimientoCajaUpdateOne) SetNillableObservaciones(v *string) *MovimientoCajaUpdateOne {
	if v != nil {
		_u.SetObservaciones(*v)
	}
	return _u
}

// ClearObservaciones clears the value of the "observaciones" field.
func (_u *MovimientoCajaUpdateOne) ClearObservaciones() *MovimientoCajaUpdateOne {
	_u.mutation.ClearObservaciones()
	return _u
}

// SetEmpresa sets the "empresa" edge to the Empresa entity.
func (_u *MovimientoCajaUpdateOne) SetEmpresa(v *Empresa) *MovimientoCajaUpdateOne {
	return _u.SetEmpresaID(v.ID)
}

// SetPago sets the "pago" edge to the Pago entity.
func (_u *MovimientoCajaUpdateOne) SetPago(v *Pago) *MovimientoCajaUpdateOne {
	return _u.SetPagoID(v.ID)
}

// SetGasto sets the "gasto" edge to the Gasto entity.
func (_u *MovimientoCajaUpdateOne) SetGasto(v *Gasto) *MovimientoCajaUpdateOne {
	return _u.SetGastoID(v.ID)
}

// Mutation returns the MovimientoCajaMutation object of the builder.
func (_u *MovimientoCajaUpdateOne) Mutation() *MovimientoCajaMutation {
	return _u.mutation
}

// ClearEmpresa clears the "empresa" edge to the Empresa entity.
func (_u *MovimientoCajaUpdateOne) ClearEmpresa() *MovimientoCajaUpdateOne {
	_u.mutation.ClearEmpresa()
	return _u
}

// ClearPago clears the "pago" edge to the Pago entity.
func (_u *MovimientoCajaUpdateOne) ClearPago() *MovimientoCajaUpdateOne {
	_u.mutation.ClearPago()
	return _u
}

// ClearGasto clears the "gasto" edge to the Gasto entity.
func (_u *MovimientoCajaUpdateOne) ClearGasto() *MovimientoCajaUpdateOne {
	_u.mutation.ClearGasto()
	return _u
}

// Where appends a list predicates to the MovimientoCajaUpdate builder.
func (_u *MovimientoCajaUpdateOne) Where(ps ...predicate.MovimientoCaja) *MovimientoCajaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MovimientoCajaUpdateOne) Select(field string, fields ...string) *MovimientoCajaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MovimientoCaja entity.
func (_u *MovimientoCajaUpdateOne) Save(ctx context.Context) (*MovimientoCaja, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MovimientoCajaUpdateOne) SaveX(ctx context.Context) *MovimientoCaja {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MovimientoCajaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MovimientoCajaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MovimientoCajaUpdateOne) check() error {
	if v, ok := _u.mutation.Tipo(); ok {
		if err := movimientocaja.TipoValidator(v); err != nil {
			return &ValidationError{Name: "tipo", err: fmt.Errorf(`ent: validator failed for field "MovimientoCaja.tipo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Concepto(); ok {
		if err := movimientocaja.ConceptoValidator(v); err != nil {
			return &ValidationError{Name: "concepto", err: fmt.Errorf(`ent: validator failed for field "MovimientoCaja.concepto": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Moneda(); ok {
		if err := movimientocaja.MonedaValidator(v); err != nil {
			return &ValidationError{Name: "moneda", err: fmt.Errorf(`ent: validator failed for field "MovimientoCaja.moneda": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Metodo(); ok {
		if err := movimientocaja.MetodoValidator(v); err != nil {
			return &ValidationError{Name: "metodo", err: fmt.Errorf(`ent: validator failed for field "MovimientoCaja.metodo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Referencia(); ok {
		if err := movimientocaja.ReferenciaValidator(v); err != nil {
			return &ValidationError{Name: "referencia", err: fmt.Errorf(`ent: validator failed for field "MovimientoCaja.referencia": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Observaciones(); ok {
		if err := movimientocaja.ObservacionesValidator(v); err != nil {
			return &ValidationError{Name: "observaciones", err: fmt.Errorf(`ent: validator failed for field "MovimientoCaja.observaciones": %w`, err)}
		}
	}
	if _u.mutation.EmpresaCleared() && len(_u.mutation.EmpresaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MovimientoCaja.empresa"`)
	}
	return nil
}

func (_u *MovimientoCajaUpdateOne) sqlSave(ctx context.Context) (_node *MovimientoCaja, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(movimientocaja.Table, movimientocaja.Columns, sqlgraph.NewFieldSpec(movimientocaja.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MovimientoCaja.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, movimientocaja.FieldID)
		for _, f := range fields {
			if !movimientocaja.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != movimientocaja.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tipo(); ok {
		_spec.SetField(movimientocaja.FieldTipo, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Concepto(); ok {
		_spec.SetField(movimientocaja.FieldConcepto, field.TypeString, value)
	}
	if value, ok := _u.mutation.FechaMovimiento(); ok {
		_spec.SetField(movimientocaja.FieldFechaMovimiento, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Moneda(); ok {
		_spec.SetField(movimientocaja.FieldMoneda, field.TypeString, value)
	}
	if value, ok := _u.mutation.Monto(); ok {
		_spec.SetField(movimientocaja.FieldMonto, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMonto(); ok {
		_spec.AddField(movimientocaja.FieldMonto, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Metodo(); ok {
		_spec.SetField(movimientocaja.FieldMetodo, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Referencia(); ok {
		_spec.SetField(movimientocaja.FieldReferencia, field.TypeString, value)
	}
	if _u.mutation.ReferenciaCleared() {
		_spec.ClearField(movimientocaja.FieldReferencia, field.TypeString)
	}
	if value, ok := _u.mutation.Observaciones(); ok {
		_spec.SetField(movimientocaja.FieldObservaciones, field.TypeString, value)
	}
	if _u.mutation.ObservacionesCleared() {
		_spec.ClearField(movimientocaja.FieldObservaciones, field.TypeString)
	}
	if _u.mutation.EmpresaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   movimientocaja.EmpresaTable,
			Columns: []string{movimientocaja.EmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresa.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmpresaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   movimientocaja.EmpresaTable,
			Columns: []string{movimientocaja.EmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresa.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PagoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   movimientocaja.PagoTable,
			Columns: []string{movimientocaja.PagoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pago.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PagoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   movimientocaja.PagoTable,
			Columns: []string{movimientocaja.PagoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pago.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GastoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   movimientocaja.GastoTable,
			Columns: []string{movimientocaja.GastoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gasto.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GastoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   movimientocaja.GastoTable,
			Columns: []string{movimientocaja.GastoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gasto.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MovimientoCaja{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{movimientocaja.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
