// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"rentals-go/ent/empresa"
	"rentals-go/ent/gasto"
	"rentals-go/ent/movimientocaja"
	"rentals-go/ent/pago"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// MovimientoCaja is the model entity for the MovimientoCaja schema.
type MovimientoCaja struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreadoEn holds the value of the "creado_en" field.
	CreadoEn time.Time `json:"creado_en,omitempty"`
	// EmpresaID holds the value of the "empresa_id" field.
	EmpresaID int `json:"empresa_id,omitempty"`
	// PagoID holds the value of the "pago_id" field.
	PagoID *int `json:"pago_id,omitempty"`
	// GastoID holds the value of the "gasto_id" field.
	GastoID *int `json:"gasto_id,omitempty"`
	// Tipo holds the value of the "tipo" field.
	Tipo movimientocaja.Tipo `json:"tipo,omitempty"`
	// Concepto holds the value of the "concepto" field.
	Concepto string `json:"concepto,omitempty"`
	// FechaMovimiento holds the value of the "fecha_movimiento" field.
	FechaMovimiento time.Time `json:"fecha_movimiento,omitempty"`
	// Moneda holds the value of the "moneda" field.
	Moneda string `json:"moneda,omitempty"`
	// Monto holds the value of the "monto" field.
	Monto float64 `json:"monto,omitempty"`
	// Metodo holds the value of the "metodo" field.
	Metodo movimientocaja.Metodo `json:"metodo,omitempty"`
	// Referencia holds the value of the "referencia" field.
	Referencia *string `json:"referencia,omitempty"`
	// Observaciones holds the value of the "observaciones" field.
	Observaciones *string `json:"observaciones,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MovimientoCajaQuery when eager-loading is set.
	Edges        MovimientoCajaEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MovimientoCajaEdges holds the relations/edges for other nodes in the graph.
type MovimientoCajaEdges struct {
	// Empresa holds the value of the empresa edge.
	Empresa *Empresa `json:"empresa,omitempty"`
	// Pago holds the value of the pago edge.
	Pago *Pago `json:"pago,omitempty"`
	// Gasto holds the value of the gasto edge.
	Gasto *Gasto `json:"gasto,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// EmpresaOrErr returns the Empresa value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MovimientoCajaEdges) EmpresaOrErr() (*Empresa, error) {
	if e.Empresa != nil {
		return e.Empresa, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: empresa.Label}
	}
	return nil, &NotLoadedError{edge: "empresa"}
}

// PagoOrErr returns the Pago value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MovimientoCajaEdges) PagoOrErr() (*Pago, error) {
	if e.Pago != nil {
		return e.Pago, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: pago.Label}
	}
	return nil, &NotLoadedError{edge: "pago"}
}

// GastoOrErr returns the Gasto value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MovimientoCajaEdges) GastoOrErr() (*Gasto, error) {
	if e.Gasto != nil {
		return e.Gasto, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: gasto.Label}
	}
	return nil, &NotLoadedError{edge: "gasto"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MovimientoCaja) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case movimientocaja.FieldMonto:
			values[i] = new(sql.NullFloat64)
		case movimientocaja.FieldID, movimientocaja.FieldEmpresaID, movimientocaja.FieldPagoID, movimientocaja.FieldGastoID:
			values[i] = new(sql.NullInt64)
		case movimientocaja.FieldTipo, movimientocaja.FieldConcepto, movimientocaja.FieldMoneda, movimientocaja.FieldMetodo, movimientocaja.FieldReferencia, movimientocaja.FieldObservaciones:
			values[i] = new(sql.NullString)
		case movimientocaja.FieldCreadoEn, movimientocaja.FieldFechaMovimiento:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MovimientoCaja fields.
func (_m *MovimientoCaja) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case movimientocaja.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case movimientocaja.FieldCreadoEn:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field creado_en", values[i])
			} else if value.Valid {
				_m.CreadoEn = value.Time
			}
		case movimientocaja.FieldEmpresaID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field empresa_id", values[i])
			} else if value.Valid {
				_m.EmpresaID = int(value.Int64)
			}
		case movimientocaja.FieldPagoID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pago_id", values[i])
			} else if value.Valid {
				_m.PagoID = new(int)
				*_m.PagoID = int(value.Int64)
			}
		case movimientocaja.FieldGastoID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gasto_id", values[i])
			} else if value.Valid {
				_m.GastoID = new(int)
				*_m.GastoID = int(value.Int64)
			}
		case movimientocaja.FieldTipo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tipo", values[i])
			} else if value.Valid {
				_m.Tipo = movimientocaja.Tipo(value.String)
			}
		case movimientocaja.FieldConcepto:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field concepto", values[i])
			} else if value.Valid {
				_m.Concepto = value.String
			}
		case movimientocaja.FieldFechaMovimiento:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field fecha_movimiento", values[i])
			} else if value.Valid {
				_m.FechaMovimiento = value.Time
			}
		case movimientocaja.FieldMoneda:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field moneda", values[i])
			} else if value.Valid {
				_m.Moneda = value.String
			}
		case movimientocaja.FieldMonto:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monto", values[i])
			} else if value.Valid {
				_m.Monto = value.Float64
			}
		case movimientocaja.FieldMetodo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metodo", values[i])
			} else if value.Valid {
				_m.Metodo = movimientocaja.Metodo(value.String)
			}
		case movimientocaja.FieldReferencia:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field referencia", values[i])
			} else if value.Valid {
				_m.Referencia = new(string)
				*_m.Referencia = value.String
			}
		case movimientocaja.FieldObservaciones:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field observaciones", values[i])
			} else if value.Valid {
				_m.Observaciones = new(string)
				*_m.Observaciones = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MovimientoCaja.
// This includes values selected through modifiers, order, etc.
func (_m *MovimientoCaja) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEmpresa queries the "empresa" edge of the MovimientoCaja entity.
func (_m *MovimientoCaja) QueryEmpresa() *EmpresaQuery {
	return NewMovimientoCajaClient(_m.config).QueryEmpresa(_m)
}

// QueryPago queries the "pago" edge of the MovimientoCaja entity.
func (_m *MovimientoCaja) QueryPago() *PagoQuery {
	return NewMovimientoCajaClient(_m.config).QueryPago(_m)
}

// QueryGasto queries the "gasto" edge of the MovimientoCaja entity.
func (_m *MovimientoCaja) QueryGasto() *GastoQuery {
	return NewMovimientoCajaClient(_m.config).QueryGasto(_m)
}

// Update returns a builder for updating this MovimientoCaja.
// Note that you need to call MovimientoCaja.Unwrap() before calling this method if this MovimientoCaja
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MovimientoCaja) Update() *MovimientoCajaUpdateOne {
	return NewMovimientoCajaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MovimientoCaja entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MovimientoCaja) Unwrap() *MovimientoCaja {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MovimientoCaja is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MovimientoCaja) String() string {
	var builder strings.Builder
	builder.WriteString("MovimientoCaja(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("creado_en=")
	builder.WriteString(_m.CreadoEn.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("empresa_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmpresaID))
	builder.WriteString(", ")
	if v := _m.PagoID; v != nil {
		builder.WriteString("pago_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GastoID; v != nil {
		builder.WriteString("gasto_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("tipo=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tipo))
	builder.WriteString(", ")
	builder.WriteString("concepto=")
	builder.WriteString(_m.Concepto)
	builder.WriteString(", ")
	builder.WriteString("fecha_movimiento=")
	builder.WriteString(_m.FechaMovimiento.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("moneda=")
	builder.WriteString(_m.Moneda)
	builder.WriteString(", ")
	builder.WriteString("monto=")
	builder.WriteString(fmt.Sprintf("%v", _m.Monto))
	builder.WriteString(", ")
	builder.WriteString("metodo=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metodo))
	builder.WriteString(", ")
	if v := _m.Referencia; v != nil {
		builder.WriteString("referencia=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Observaciones; v != nil {
		builder.WriteString("observaciones=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// MovimientoCajas is a parsable slice of MovimientoCaja.
type MovimientoCajas []*MovimientoCaja
