// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rentals-go/ent/cargo"
	"rentals-go/ent/pago"
	"rentals-go/ent/pagoaplicacion"
	"rentals-go/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PagoAplicacionUpdate is the builder for updating PagoAplicacion entities.
type PagoAplicacionUpdate struct {
	config
	hooks    []Hook
	mutation *PagoAplicacionMutation
}

// Where appends a list predicates to the PagoAplicacionUpdate builder.
func (_u *PagoAplicacionUpdate) Where(ps ...predicate.PagoAplicacion) *PagoAplicacionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPagoID sets the "pago_id" field.
func (_u *PagoAplicacionUpdate) SetPagoID(v int) *PagoAplicacionUpdate {
	_u.mutation.SetPagoID(v)
	return _u
}

// SetNillablePagoID sets the "pago_id" field if the given value is not nil.
func (_u *PagoAplicacionUpdate) SetNillablePagoID(v *int) *PagoAplicacionUpdate {
	if v != nil {
		_u.SetPagoID(*v)
	}
	return _u
}

// SetCargoID sets the "cargo_id" field.
func (_u *PagoAplicacionUpdate) SetCargoID(v int) *PagoAplicacionUpdate {
	_u.mutation.SetCargoID(v)
	return _u
}

// SetNillableCargoID sets the "cargo_id" field if the given value is not nil.
func (_u *PagoAplicacionUpdate) SetNillableCargoID(v *int) *PagoAplicacionUpdate {
	if v != nil {
		_u.SetCargoID(*v)
	}
	return _u
}

// SetMoneda sets the "moneda" field.
func (_u *PagoAplicacionUpdate) SetMoneda(v string) *PagoAplicacionUpdate {
	_u.mutation.SetMoneda(v)
	return _u
}

// SetNillableMoneda sets the "moneda" field if the given value is not nil.
func (_u *PagoAplicacionUpdate) SetNillableMoneda(v *string) *PagoAplicacionUpdate {
	if v != nil {
		_u.SetMoneda(*v)
	}
	return _u
}

// SetMontoAplicado sets the "monto_aplicado" field.
func (_u *PagoAplicacionUpdate) SetMontoAplicado(v int64) *PagoAplicacionUpdate {
	_u.mutation.ResetMontoAplicado()
	_u.mutation.SetMontoAplicado(v)
	return _u
}

// SetNillableMontoAplicado sets the "monto_aplicado" field if the given value is not nil.
func (_u *PagoAplicacionUpdate) SetNillableMontoAplicado(v *int64) *PagoAplicacionUpdate {
	if v != nil {
		_u.SetMontoAplicado(*v)
	}
	return _u
}

// AddMontoAplicado adds value to the "monto_aplicado" field.
func (_u *PagoAplicacionUpdate) AddMontoAplicado(v int64) *PagoAplicacionUpdate {
	_u.mutation.AddMontoAplicado(v)
	return _u
}

// SetPago sets the "pago" edge to the Pago entity.
func (_u *PagoAplicacionUpdate) SetPago(v *Pago) *PagoAplicacionUpdate {
	return _u.SetPagoID(v.ID)
}

// SetCargo sets the "cargo" edge to the Cargo entity.
func (_u *PagoAplicacionUpdate) SetCargo(v *Cargo) *PagoAplicacionUpdate {
	return _u.SetCargoID(v.ID)
}

// Mutation returns the PagoAplicacionMutation object of the builder.
func (_u *PagoAplicacionUpdate) Mutation() *PagoAplicacionMutation {
	return _u.mutation
}

// ClearPago clears the "pago" edge to the Pago entity.
func (_u *PagoAplicacionUpdate) ClearPago() *PagoAplicacionUpdate {
	_u.mutation.ClearPago()
	return _u
}

// ClearCargo clears the "cargo" edge to the Cargo entity.
func (_u *PagoAplicacionUpdate) ClearCargo() *PagoAplicacionUpdate {
	_u.mutation.ClearCargo()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PagoAplicacionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PagoAplicacionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PagoAplicacionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PagoAplicacionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PagoAplicacionUpdate) check() error {
	if v, ok := _u.mutation.Moneda(); ok {
		if err := pagoaplicacion.MonedaValidator(v); err != nil {
			return &ValidationError{Name: "moneda", err: fmt.Errorf(`ent: validator failed for field "PagoAplicacion.moneda": %w`, err)}
		}
	}
	if _u.mutation.PagoCleared() && len(_u.mutation.PagoIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PagoAplicacion.pago"`)
	}
	if _u.mutation.CargoCleared() && len(_u.mutation.CargoIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PagoAplicacion.cargo"`)
	}
	return nil
}

func (_u *PagoAplicacionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pagoaplicacion.Table, pagoaplicacion.Columns, sqlgraph.NewFieldSpec(pagoaplicacion.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Moneda(); ok {
		_spec.SetField(pagoaplicacion.FieldMoneda, field.TypeString, value)
	}
	if value, ok := _u.mutation.MontoAplicado(); ok {
		_spec.SetField(pagoaplicacion.FieldMontoAplicado, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMontoAplicado(); ok {
		_spec.AddField(pagoaplicacion.FieldMontoAplicado, field.TypeInt64, value)
	}
	if _u.mutation.PagoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pagoaplicacion.PagoTable,
			Columns: []string{pagoaplicacion.PagoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pago.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PagoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pagoaplicacion.PagoTable,
			Columns: []string{pagoaplicacion.PagoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pago.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CargoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pagoaplicacion.CargoTable,
			Columns: []string{pagoaplicacion.CargoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cargo.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CargoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pagoaplicacion.CargoTable,
			Columns: []string{pagoaplicacion.CargoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cargo.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pagoaplicacion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PagoAplicacionUpdateOne is the builder for updating a single PagoAplicacion entity.
type PagoAplicacionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PagoAplicacionMutation
}

// SetPagoID sets the "pago_id" field.
func (_u *PagoAplicacionUpdateOne) SetPagoID(v int) *PagoAplicacionUpdateOne {
	_u.mutation.SetPagoID(v)
	return _u
}

// SetNillablePagoID sets the "pago_id" field if the given value is not nil.
func (_u *PagoAplicacionUpdateOne) SetNillablePagoID(v *int) *PagoAplicacionUpdateOne {
	if v != nil {
		_u.SetPagoID(*v)
	}
	return _u
}

// SetCargoID sets the "cargo_id" field.
func (_u *PagoAplicacionUpdateOne) SetCargoID(v int) *PagoAplicacionUpdateOne {
	_u.mutation.SetCargoID(v)
	return _u
}

// SetNillableCargoID sets the "cargo_id" field if the given value is not nil.
func (_u *PagoAplicacionUpdateOne) SetNillableCargoID(v *int) *PagoAplicacionUpdateOne {
	if v != nil {
		_u.SetCargoID(*v)
	}
	return _u
}

// SetMoneda sets the "moneda" field.
func (_u *PagoAplicacionUpdateOne) SetMoneda(v string) *PagoAplicacionUpdateOne {
	_u.mutation.SetMoneda(v)
	return _u
}

// SetNillableMoneda sets the "moneda" field if the given value is not nil.
func (_u *PagoAplicacionUpdateOne) SetNillableMoneda(v *string) *PagoAplicacionUpdateOne {
	if v != nil {
		_u.SetMoneda(*v)
	}
	return _u
}

// SetMontoAplicado sets the "monto_aplicado" field.
func (_u *PagoAplicacionUpdateOne) SetMontoAplicado(v int64) *PagoAplicacionUpdateOne {
	_u.mutation.ResetMontoAplicado()
	_u.mutation.SetMontoAplicado(v)
	return _u
}

// SetNillableMontoAplicado sets the "monto_aplicado" field if the given value is not nil.
func (_u *PagoAplicacionUpdateOne) SetNillableMontoAplicado(v *int64) *PagoAplicacionUpdateOne {
	if v != nil {
		_u.SetMontoAplicado(*v)
	}
	return _u
}

// AddMontoAplicado adds value to the "monto_aplicado" field.
func (_u *PagoAplicacionUpdateOne) AddMontoAplicado(v int64) *PagoAplicacionUpdateOne {
	_u.mutation.AddMontoAplicado(v)
	return _u
}

// SetPago sets the "pago" edge to the Pago entity.
func (_u *PagoAplicacionUpdateOne) SetPago(v *Pago) *PagoAplicacionUpdateOne {
	return _u.SetPagoID(v.ID)
}

// SetCargo sets the "cargo" edge to the Cargo entity.
func (_u *PagoAplicacionUpdateOne) SetCargo(v *Cargo) *PagoAplicacionUpdateOne {
	return _u.SetCargoID(v.ID)
}

// Mutation returns the PagoAplicacionMutation object of the builder.
func (_u *PagoAplicacionUpdateOne) Mutation() *PagoAplicacionMutation {
	return _u.mutation
}

// ClearPago clears the "pago" edge to the Pago entity.
func (_u *PagoAplicacionUpdateOne) ClearPago() *PagoAplicacionUpdateOne {
	_u.mutation.ClearPago()
	return _u
}

// ClearCargo clears the "cargo" edge to the Cargo entity.
func (_u *PagoAplicacionUpdateOne) ClearCargo() *PagoAplicacionUpdateOne {
	_u.mutation.ClearCargo()
	return _u
}

// Where appends a list predicates to the PagoAplicacionUpdate builder.
func (_u *PagoAplicacionUpdateOne) Where(ps ...predicate.PagoAplicacion) *PagoAplicacionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PagoAplicacionUpdateOne) Select(field string, fields ...string) *PagoAplicacionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PagoAplicacion entity.
func (_u *PagoAplicacionUpdateOne) Save(ctx context.Context) (*PagoAplicacion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PagoAplicacionUpdateOne) SaveX(ctx context.Context) *PagoAplicacion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PagoAplicacionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PagoAplicacionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PagoAplicacionUpdateOne) check() error {
	if v, ok := _u.mutation.Moneda(); ok {
		if err := pagoaplicacion.MonedaValidator(v); err != nil {
			return &ValidationError{Name: "moneda", err: fmt.Errorf(`ent: validator failed for field "PagoAplicacion.moneda": %w`, err)}
		}
	}
	if _u.mutation.PagoCleared() && len(_u.mutation.PagoIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PagoAplicacion.pago"`)
	}
	if _u.mutation.CargoCleared() && len(_u.mutation.CargoIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PagoAplicacion.cargo"`)
	}
	return nil
}

func (_u *PagoAplicacionUpdateOne) sqlSave(ctx context.Context) (_node *PagoAplicacion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pagoaplicacion.Table, pagoaplicacion.Columns, sqlgraph.NewFieldSpec(pagoaplicacion.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PagoAplicacion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pagoaplicacion.FieldID)
		for _, f := range fields {
			if !pagoaplicacion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pagoaplicacion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Moneda(); ok {
		_spec.SetField(pagoaplicacion.FieldMoneda, field.TypeString, value)
	}
	if value, ok := _u.mutation.MontoAplicado(); ok {
		_spec.SetField(pagoaplicacion.FieldMontoAplicado, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMontoAplicado(); ok {
		_spec.AddField(pagoaplicacion.FieldMontoAplicado, field.TypeInt64, value)
	}
	if _u.mutation.PagoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pagoaplicacion.PagoTable,
			Columns: []string{pagoaplicacion.PagoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pago.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PagoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pagoaplicacion.PagoTable,
			Columns: []string{pagoaplicacion.PagoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pago.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CargoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pagoaplicacion.CargoTable,
			Columns: []string{pagoaplicacion.CargoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cargo.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CargoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pagoaplicacion.CargoTable,
			Columns: []string{pagoaplicacion.CargoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cargo.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PagoAplicacion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pagoaplicacion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
