// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rentals-go/ent/cliente"
	"rentals-go/ent/contrato"
	"rentals-go/ent/empresa"
	"rentals-go/ent/movimientocaja"
	"rentals-go/ent/pago"
	"rentals-go/ent/pagoaplicacion"
	"rentals-go/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PagoUpdate is the builder for updating Pago entities.
type PagoUpdate struct {
	config
	hooks    []Hook
	mutation *PagoMutation
}

// Where appends a list predicates to the PagoUpdate builder.
func (_u *PagoUpdate) Where(ps ...predicate.Pago) *PagoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmpresaID sets the "empresa_id" field.
func (_u *PagoUpdate) SetEmpresaID(v int) *PagoUpdate {
	_u.mutation.SetEmpresaID(v)
	return _u
}

// SetNillableEmpresaID sets the "empresa_id" field if the given value is not nil.
func (_u *PagoUpdate) SetNillableEmpresaID(v *int) *PagoUpdate {
	if v != nil {
		_u.SetEmpresaID(*v)
	}
	return _u
}

// SetClienteID sets the "cliente_id" field.
func (_u *PagoUpdate) SetClienteID(v int) *PagoUpdate {
	_u.mutation.SetClienteID(v)
	return _u
}

// SetNillableClienteID sets the "cliente_id" field if the given value is not nil.
func (_u *PagoUpdate) SetNillableClienteID(v *int) *PagoUpdate {
	if v != nil {
		_u.SetClienteID(*v)
	}
	return _u
}

// ClearClienteID clears the value of the "cliente_id" field.
func (_u *PagoUpdate) ClearClienteID() *PagoUpdate {
	_u.mutation.ClearClienteID()
	return _u
}

// SetContratoID sets the "contrato_id" field.
func (_u *PagoUpdate) SetContratoID(v int) *PagoUpdate {
	_u.mutation.SetContratoID(v)
	return _u
}

// SetNillableContratoID sets the "contrato_id" field if the given value is not nil.
func (_u *PagoUpdate) SetNillableContratoID(v *int) *PagoUpdate {
	if v != nil {
		_u.SetContratoID(*v)
	}
	return _u
}

// ClearContratoID clears the value of the "contrato_id" field.
func (_u *PagoUpdate) ClearContratoID() *PagoUpdate {
	_u.mutation.ClearContratoID()
	return _u
}

// SetNumeroRecibo sets the "numero_recibo" field.
func (_u *PagoUpdate) SetNumeroRecibo(v string) *PagoUpdate {
	_u.mutation.SetNumeroRecibo(v)
	return _u
}

// SetNillableNumeroRecibo sets the "numero_recibo" field if the given value is not nil.
func (_u *PagoUpdate) SetNillableNumeroRecibo(v *string) *PagoUpdate {
	if v != nil {
		_u.SetNumeroRecibo(*v)
	}
	return _u
}

// SetFechaPago sets the "fecha_pago" field.
func (_u *PagoUpdate) SetFechaPago(v time.Time) *PagoUpdate {
	_u.mutation.SetFechaPago(v)
	return _u
}

// SetNillableFechaPago sets the "fecha_pago" field if the given value is not nil.
func (_u *PagoUpdate) SetNillableFechaPago(v *time.Time) *PagoUpdate {
	if v != nil {
		_u.SetFechaPago(*v)
	}
	return _u
}

// SetMoneda sets the "moneda" field.
func (_u *PagoUpdate) SetMoneda(v string) *PagoUpdate {
	_u.mutation.SetMoneda(v)
	return _u
}

// SetNillableMoneda sets the "moneda" field if the given value is not nil.
func (_u *PagoUpdate) SetNillableMoneda(v *string) *PagoUpdate {
	if v != nil {
		_u.SetMoneda(*v)
	}
	return _u
}

// SetMontoTotal sets the "monto_total" field.
func (_u *PagoUpdate) SetMontoTotal(v int64) *PagoUpdate {
	_u.mutation.ResetMontoTotal()
	_u.mutation.SetMontoTotal(v)
	return _u
}

// SetNillableMontoTotal sets the "monto_total" field if the given value is not nil.
func (_u *PagoUpdate) SetNillableMontoTotal(v *int64) *PagoUpdate {
	if v != nil {
		_u.SetMontoTotal(*v)
	}
	return _u
}

// AddMontoTotal adds value to the "monto_total" field.
func (_u *PagoUpdate) AddMontoTotal(v int64) *PagoUpdate {
	_u.mutation.AddMontoTotal(v)
	return _u
}

// SetMetodo sets the "metodo" field.
func (_u *PagoUpdate) SetMetodo(v pago.Metodo) *PagoUpdate {
	_u.mutation.SetMetodo(v)
	return _u
}

// SetNillableMetodo sets the "metodo" field if the given value is not nil.
func (_u *PagoUpdate) SetNillableMetodo(v *pago.Metodo) *PagoUpdate {
	if v != nil {
		_u.SetMetodo(*v)
	}
	return _u
}

// SetReferencia sets the "referencia" field.
func (_u *PagoUpdate) SetReferencia(v string) *PagoUpdate {
	_u.mutation.SetReferencia(v)
	return _u
}

// SetNillableReferencia sets the "referencia" field if the given value is not nil.
func (_u *PagoUpdate) SetNillableReferencia(v *string) *PagoUpdate {
	if v != nil {
		_u.SetReferencia(*v)
	}
	return _u
}

// ClearReferencia clears the value of the "referencia" field.
func (_u *PagoUpdate) ClearReferencia() *PagoUpdate {
	_u.mutation.ClearReferencia()
	return _u
}

// SetNotas sets the "notas" field.
func (_u *PagoUpdate) SetNotas(v string) *PagoUpdate {
	_u.mutation.SetNotas(v)
	return _u
}

// SetNillableNotas sets the "notas" field if the given value is not nil.
func (_u *PagoUpdate) SetNillableNotas(v *string) *PagoUpdate {
	if v != nil {
		_u.SetNotas(*v)
	}
	return _u
}

// ClearNotas clears the value of the "notas" field.
func (_u *PagoUpdate) ClearNotas() *PagoUpdate {
	_u.mutation.ClearNotas()
	return _u
}

// SetEstado sets the "estado" field.
func (_u *PagoUpdate) SetEstado(v pago.Estado) *PagoUpdate {
	_u.mutation.SetEstado(v)
	return _u
}

// SetNillableEstado sets the "estado" field if the given value is not nil.
func (_u *PagoUpdate) SetNillableEstado(v *pago.Estado) *PagoUpdate {
	if v != nil {
		_u.SetEstado(*v)
	}
	return _u
}

// SetEmpresa sets the "empresa" edge to the Empresa entity.
func (_u *PagoUpdate) SetEmpresa(v *Empresa) *PagoUpdate {
	return _u.SetEmpresaID(v.ID)
}

// SetCliente sets the "cliente" edge to the Cliente entity.
func (_u *PagoUpdate) SetCliente(v *Cliente) *PagoUpdate {
	return _u.SetClienteID(v.ID)
}

// SetContrato sets the "contrato" edge to the Contrato entity.
func (_u *PagoUpdate) SetContrato(v *Contrato) *PagoUpdate {
	return _u.SetContratoID(v.ID)
}

// AddAplicacioneIDs adds the "aplicaciones" edge to the PagoAplicacion entity by IDs.
func (_u *PagoUpdate) AddAplicacioneIDs(ids ...int) *PagoUpdate {
	_u.mutation.AddAplicacioneIDs(ids...)
	return _u
}

// AddAplicaciones adds the "aplicaciones" edges to the PagoAplicacion entity.
func (_u *PagoUpdate) AddAplicaciones(v ...*PagoAplicacion) *PagoUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAplicacioneIDs(ids...)
}

// AddMovimientosCajaIDs adds the "movimientos_caja" edge to the MovimientoCaja entity by IDs.
func (_u *PagoUpdate) AddMovimientosCajaIDs(ids ...int) *PagoUpdate {
	_u.mutation.AddMovimientosCajaIDs(ids...)
	return _u
}

// AddMovimientosCaja adds the "movimientos_caja" edges to the MovimientoCaja entity.
func (_u *PagoUpdate) AddMovimientosCaja(v ...*MovimientoCaja) *PagoUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMovimientosCajaIDs(ids...)
}

// Mutation returns the PagoMutation object of the builder.
func (_u *PagoUpdate) Mutation() *PagoMutation {
	return _u.mutation
}

// ClearEmpresa clears the "empresa" edge to the Empresa entity.
func (_u *PagoUpdate) ClearEmpresa() *PagoUpdate {
	_u.mutation.ClearEmpresa()
	return _u
}

// ClearCliente clears the "cliente" edge to the Cliente entity.
func (_u *PagoUpdate) ClearCliente() *PagoUpdate {
	_u.mutation.ClearCliente()
	return _u
}

// ClearContrato clears the "contrato" edge to the Contrato entity.
func (_u *PagoUpdate) ClearContrato() *PagoUpdate {
	_u.mutation.ClearContrato()
	return _u
}

// ClearAplicaciones clears all "aplicaciones" edges to the PagoAplicacion entity.
func (_u *PagoUpdate) ClearAplicaciones() *PagoUpdate {
	_u.mutation.ClearAplicaciones()
	return _u
}

// RemoveAplicacioneIDs removes the "aplicaciones" edge to PagoAplicacion entities by IDs.
func (_u *PagoUpdate) RemoveAplicacioneIDs(ids ...int) *PagoUpdate {
	_u.mutation.RemoveAplicacioneIDs(ids...)
	return _u
}

// RemoveAplicaciones removes "aplicaciones" edges to PagoAplicacion entities.
func (_u *PagoUpdate) RemoveAplicaciones(v ...*PagoAplicacion) *PagoUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAplicacioneIDs(ids...)
}

// ClearMovimientosCaja clears all "movimientos_caja" edges to the MovimientoCaja entity.
func (_u *PagoUpdate) ClearMovimientosCaja() *PagoUpdate {
	_u.mutation.ClearMovimientosCaja()
	return _u
}

// RemoveMovimientosCajaIDs removes the "movimientos_caja" edge to MovimientoCaja entities by IDs.
func (_u *PagoUpdate) RemoveMovimientosCajaIDs(ids ...int) *PagoUpdate {
	_u.mutation.RemoveMovimientosCajaIDs(ids...)
	return _u
}

// RemoveMovimientosCaja removes "movimientos_caja" edges to MovimientoCaja entities.
func (_u *PagoUpdate) RemoveMovimientosCaja(v ...*MovimientoCaja) *PagoUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMovimientosCajaIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PagoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PagoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PagoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PagoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PagoUpdate) check() error {
	if v, ok := _u.mutation.NumeroRecibo(); ok {
		if err := pago.NumeroReciboValidator(v); err != nil {
			return &ValidationError{Name: "numero_recibo", err: fmt.Errorf(`ent: validator failed for field "Pago.numero_recibo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Moneda(); ok {
		if err := pago.MonedaValidator(v); err != nil {
			return &ValidationError{Name: "moneda", err: fmt.Errorf(`ent: validator failed for field "Pago.moneda": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Metodo(); ok {
		if err := pago.MetodoValidator(v); err != nil {
			return &ValidationError{Name: "metodo", err: fmt.Errorf(`ent: validator failed for field "Pago.metodo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Referencia(); ok {
		if err := pago.ReferenciaValidator(v); err != nil {
			return &ValidationError{Name: "referencia", err: fmt.Errorf(`ent: validator failed for field "Pago.referencia": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Notas(); ok {
		if err := pago.NotasValidator(v); err != nil {
			return &ValidationError{Name: "notas", err: fmt.Errorf(`ent: validator failed for field "Pago.notas": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Estado(); ok {
		if err := pago.EstadoValidator(v); err != nil {
			return &ValidationError{Name: "estado", err: fmt.Errorf(`ent: validator failed for field "Pago.estado": %w`, err)}
		}
	}
	if _u.mutation.EmpresaCleared() && len(_u.mutation.EmpresaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Pago.empresa"`)
	}
	return nil
}

func (_u *PagoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pago.Table, pago.Columns, sqlgraph.NewFieldSpec(pago.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NumeroRecibo(); ok {
		_spec.SetField(pago.FieldNumeroRecibo, field.TypeString, value)
	}
	if value, ok := _u.mutation.FechaPago(); ok {
		_spec.SetField(pago.FieldFechaPago, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Moneda(); ok {
		_spec.SetField(pago.FieldMoneda, field.TypeString, value)
	}
	if value, ok := _u.mutation.MontoTotal(); ok {
		_spec.SetField(pago.FieldMontoTotal, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMontoTotal(); ok {
		_spec.AddField(pago.FieldMontoTotal, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Metodo(); ok {
		_spec.SetField(pago.FieldMetodo, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Referencia(); ok {
		_spec.SetField(pago.FieldReferencia, field.TypeString, value)
	}
	if _u.mutation.ReferenciaCleared() {
		_spec.ClearField(pago.FieldReferencia, field.TypeString)
	}
	if value, ok := _u.mutation.Notas(); ok {
		_spec.SetField(pago.FieldNotas, field.TypeString, value)
	}
	if _u.mutation.NotasCleared() {
		_spec.ClearField(pago.FieldNotas, field.TypeString)
	}
	if value, ok := _u.mutation.Estado(); ok {
		_spec.SetField(pago.FieldEstado, field.TypeEnum, value)
	}
	if _u.mutation.EmpresaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pago.EmpresaTable,
			Columns: []string{pago.EmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresa.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmpresaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pago.EmpresaTable,
			Columns: []string{pago.EmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresa.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClienteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pago.ClienteTable,
			Columns: []string{pago.ClienteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cliente.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClienteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pago.ClienteTable,
			Columns: []string{pago.ClienteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cliente.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContratoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pago.ContratoTable,
			Columns: []string{pago.ContratoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contrato.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContratoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pago.ContratoTable,
			Columns: []string{pago.ContratoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contrato.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AplicacionesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pago.AplicacionesTable,
			Columns: []string{pago.AplicacionesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pagoaplicacion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAplicacionesIDs(); len(nodes) > 0 && !_u.mutation.AplicacionesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pago.AplicacionesTable,
			Columns: []string{pago.AplicacionesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pagoaplicacion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AplicacionesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pago.AplicacionesTable,
			Columns: []string{pago.AplicacionesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pagoaplicacion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MovimientosCajaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pago.MovimientosCajaTable,
			Columns: []string{pago.MovimientosCajaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movimientocaja.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMovimientosCajaIDs(); len(nodes) > 0 && !_u.mutation.MovimientosCajaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pago.MovimientosCajaTable,
			Columns: []string{pago.MovimientosCajaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movimientocaja.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MovimientosCajaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pago.MovimientosCajaTable,
			Columns: []string{pago.MovimientosCajaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movimientocaja.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pago.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PagoUpdateOne is the builder for updating a single Pago entity.
type PagoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PagoMutation
}

// SetEmpresaID sets the "empresa_id" field.
func (_u *PagoUpdateOne) SetEmpresaID(v int) *PagoUpdateOne {
	_u.mutation.SetEmpresaID(v)
	return _u
}

// SetNillableEmpresaID sets the "empresa_id" field if the given value is not nil.
func (_u *PagoUpdateOne) SetNillableEmpresaID(v *int) *PagoUpdateOne {
	if v != nil {
		_u.SetEmpresaID(*v)
	}
	return _u
}

// SetClienteID sets the "cliente_id" field.
func (_u *PagoUpdateOne) SetClienteID(v int) *PagoUpdateOne {
	_u.mutation.SetClienteID(v)
	return _u
}

// SetNillableClienteID sets the "cliente_id" field if the given value is not nil.
func (_u *PagoUpdateOne) SetNillableClienteID(v *int) *PagoUpdateOne {
	if v != nil {
		_u.SetClienteID(*v)
	}
	return _u
}

// ClearClienteID clears the value of the "cliente_id" field.
func (_u *PagoUpdateOne) ClearClienteID() *PagoUpdateOne {
	_u.mutation.ClearClienteID()
	return _u
}

// SetContratoID sets the "contrato_id" field.
func (_u *PagoUpdateOne) SetContratoID(v int) *PagoUpdateOne {
	_u.mutation.SetContratoID(v)
	return _u
}

// SetNillableContratoID sets the "contrato_id" field if the given value is not nil.
func (_u *PagoUpdateOne) SetNillableContratoID(v *int) *PagoUpdateOne {
	if v != nil {
		_u.SetContratoID(*v)
	}
	return _u
}

// ClearContratoID clears the value of the "contrato_id" field.
func (_u *PagoUpdateOne) ClearContratoID() *PagoUpdateOne {
	_u.mutation.ClearContratoID()
	return _u
}

// SetNumeroRecibo sets the "numero_recibo" field.
func (_u *PagoUpdateOne) SetNumeroRecibo(v string) *PagoUpdateOne {
	_u.mutation.SetNumeroRecibo(v)
	return _u
}

// SetNillableNumeroRecibo sets the "numero_recibo" field if the given value is not nil.
func (_u *PagoUpdateOne) SetNillableNumeroRecibo(v *string) *PagoUpdateOne {
	if v != nil {
		_u.SetNumeroRecibo(*v)
	}
	return _u
}

// SetFechaPago sets the "fecha_pago" field.
func (_u *PagoUpdateOne) SetFechaPago(v time.Time) *PagoUpdateOne {
	_u.mutation.SetFechaPago(v)
	return _u
}

// SetNillableFechaPago sets the "fecha_pago" field if the given value is not nil.
func (_u *PagoUpdateOne) SetNillableFechaPago(v *time.Time) *PagoUpdateOne {
	if v != nil {
		_u.SetFechaPago(*v)
	}
	return _u
}

// SetMoneda sets the "moneda" field.
func (_u *PagoUpdateOne) SetMoneda(v string) *PagoUpdateOne {
	_u.mutation.SetMoneda(v)
	return _u
}

// SetNillableMoneda sets the "moneda" field if the given value is not nil.
func (_u *PagoUpdateOne) SetNillableMoneda(v *string) *PagoUpdateOne {
	if v != nil {
		_u.SetMoneda(*v)
	}
	return _u
}

// SetMontoTotal sets the "monto_total" field.
func (_u *PagoUpdateOne) SetMontoTotal(v int64) *PagoUpdateOne {
	_u.mutation.ResetMontoTotal()
	_u.mutation.SetMontoTotal(v)
	return _u
}

// SetNillableMontoTotal sets the "monto_total" field if the given value is not nil.
func (_u *PagoUpdateOne) SetNillableMontoTotal(v *int64) *PagoUpdateOne {
	if v != nil {
		_u.SetMontoTotal(*v)
	}
	return _u
}

// AddMontoTotal adds value to the "monto_total" field.
func (_u *PagoUpdateOne) AddMontoTotal(v int64) *PagoUpdateOne {
	_u.mutation.AddMontoTotal(v)
	return _u
}

// SetMetodo sets the "metodo" field.
func (_u *PagoUpdateOne) SetMetodo(v pago.Metodo) *PagoUpdateOne {
	_u.mutation.SetMetodo(v)
	return _u
}

// SetNillableMetodo sets the "metodo" field if the given value is not nil.
func (_u *PagoUpdateOne) SetNillableMetodo(v *pago.Metodo) *PagoUpdateOne {
	if v != nil {
		_u.SetMetodo(*v)
	}
	return _u
}

// SetReferencia sets the "referencia" field.
func (_u *PagoUpdateOne) SetReferencia(v string) *PagoUpdateOne {
	_u.mutation.SetReferencia(v)
	return _u
}

// SetNillableReferencia sets the "referencia" field if the given value is not nil.
func (_u *PagoUpdateOne) SetNillableReferencia(v *string) *PagoUpdateOne {
	if v != nil {
		_u.SetReferencia(*v)
	}
	return _u
}

// ClearReferencia clears the value of the "referencia" field.
func (_u *PagoUpdateOne) ClearReferencia() *PagoUpdateOne {
	_u.mutation.ClearReferencia()
	return _u
}

// SetNotas sets the "notas" field.
func (_u *PagoUpdateOne) SetNotas(v string) *PagoUpdateOne {
	_u.mutation.SetNotas(v)
	return _u
}

// SetNillableNotas sets the "notas" field if the given value is not nil.
func (_u *PagoUpdateOne) SetNillableNotas(v *string) *PagoUpdateOne {
	if v != nil {
		_u.SetNotas(*v)
	}
	return _u
}

// ClearNotas clears the value of the "notas" field.
func (_u *PagoUpdateOne) ClearNotas() *PagoUpdateOne {
	_u.mutation.ClearNotas()
	return _u
}

// SetEstado sets the "estado" field.
func (_u *PagoUpdateOne) SetEstado(v pago.Estado) *PagoUpdateOne {
	_u.mutation.SetEstado(v)
	return _u
}

// SetNillableEstado sets the "estado" field if the given value is not nil.
func (_u *PagoUpdateOne) SetNillableEstado(v *pago.Estado) *PagoUpdateOne {
	if v != nil {
		_u.SetEstado(*v)
	}
	return _u
}

// SetEmpresa sets the "empresa" edge to the Empresa entity.
func (_u *PagoUpdateOne) SetEmpresa(v *Empresa) *PagoUpdateOne {
	return _u.SetEmpresaID(v.ID)
}

// SetCliente sets the "cliente" edge to the Cliente entity.
func (_u *PagoUpdateOne) SetCliente(v *Cliente) *PagoUpdateOne {
	return _u.SetClienteID(v.ID)
}

// SetContrato sets the "contrato" edge to the Contrato entity.
func (_u *PagoUpdateOne) SetContrato(v *Contrato) *PagoUpdateOne {
	return _u.SetContratoID(v.ID)
}

// AddAplicacioneIDs adds the "aplicaciones" edge to the PagoAplicacion entity by IDs.
func (_u *PagoUpdateOne) AddAplicacioneIDs(ids ...int) *PagoUpdateOne {
	_u.mutation.AddAplicacioneIDs(ids...)
	return _u
}

// AddAplicaciones adds the "aplicaciones" edges to the PagoAplicacion entity.
func (_u *PagoUpdateOne) AddAplicaciones(v ...*PagoAplicacion) *PagoUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAplicacioneIDs(ids...)
}

// AddMovimientosCajaIDs adds the "movimientos_caja" edge to the MovimientoCaja entity by IDs.
func (_u *PagoUpdateOne) AddMovimientosCajaIDs(ids ...int) *PagoUpdateOne {
	_u.mutation.AddMovimientosCajaIDs(ids...)
	return _u
}

// AddMovimientosCaja adds the "movimientos_caja" edges to the MovimientoCaja entity.
func (_u *PagoUpdateOne) AddMovimientosCaja(v ...*MovimientoCaja) *PagoUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMovimientosCajaIDs(ids...)
}

// Mutation returns the PagoMutation object of the builder.
func (_u *PagoUpdateOne) Mutation() *PagoMutation {
	return _u.mutation
}

// ClearEmpresa clears the "empresa" edge to the Empresa entity.
func (_u *PagoUpdateOne) ClearEmpresa() *PagoUpdateOne {
	_u.mutation.ClearEmpresa()
	return _u
}

// ClearCliente clears the "cliente" edge to the Cliente entity.
func (_u *PagoUpdateOne) ClearCliente() *PagoUpdateOne {
	_u.mutation.ClearCliente()
	return _u
}

// ClearContrato clears the "contrato" edge to the Contrato entity.
func (_u *PagoUpdateOne) ClearContrato() *PagoUpdateOne {
	_u.mutation.ClearContrato()
	return _u
}

// ClearAplicaciones clears all "aplicaciones" edges to the PagoAplicacion entity.
func (_u *PagoUpdateOne) ClearAplicaciones() *PagoUpdateOne {
	_u.mutation.ClearAplicaciones()
	return _u
}

// RemoveAplicacioneIDs removes the "aplicaciones" edge to PagoAplicacion entities by IDs.
func (_u *PagoUpdateOne) RemoveAplicacioneIDs(ids ...int) *PagoUpdateOne {
	_u.mutation.RemoveAplicacioneIDs(ids...)
	return _u
}

// RemoveAplicaciones removes "aplicaciones" edges to PagoAplicacion entities.
func (_u *PagoUpdateOne) RemoveAplicaciones(v ...*PagoAplicacion) *PagoUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAplicacioneIDs(ids...)
}

// ClearMovimientosCaja clears all "movimientos_caja" edges to the MovimientoCaja entity.
func (_u *PagoUpdateOne) ClearMovimientosCaja() *PagoUpdateOne {
	_u.mutation.ClearMovimientosCaja()
	return _u
}

// RemoveMovimientosCajaIDs removes the "movimientos_caja" edge to MovimientoCaja entities by IDs.
func (_u *PagoUpdateOne) RemoveMovimientosCajaIDs(ids ...int) *PagoUpdateOne {
	_u.mutation.RemoveMovimientosCajaIDs(ids...)
	return _u
}

// RemoveMovimientosCaja removes "movimientos_caja" edges to MovimientoCaja entities.
func (_u *PagoUpdateOne) RemoveMovimientosCaja(v ...*MovimientoCaja) *PagoUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMovimientosCajaIDs(ids...)
}

// Where appends a list predicates to the PagoUpdate builder.
func (_u *PagoUpdateOne) Where(ps ...predicate.Pago) *PagoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PagoUpdateOne) Select(field string, fields ...string) *PagoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Pago entity.
func (_u *PagoUpdateOne) Save(ctx context.Context) (*Pago, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PagoUpdateOne) SaveX(ctx context.Context) *Pago {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PagoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PagoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PagoUpdateOne) check() error {
	if v, ok := _u.mutation.NumeroRecibo(); ok {
		if err := pago.NumeroReciboValidator(v); err != nil {
			return &ValidationError{Name: "numero_recibo", err: fmt.Errorf(`ent: validator failed for field "Pago.numero_recibo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Moneda(); ok {
		if err := pago.MonedaValidator(v); err != nil {
			return &ValidationError{Name: "moneda", err: fmt.Errorf(`ent: validator failed for field "Pago.moneda": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Metodo(); ok {
		if err := pago.MetodoValidator(v); err != nil {
			return &ValidationError{Name: "metodo", err: fmt.Errorf(`ent: validator failed for field "Pago.metodo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Referencia(); ok {
		if err := pago.ReferenciaValidator(v); err != nil {
			return &ValidationError{Name: "referencia", err: fmt.Errorf(`ent: validator failed for field "Pago.referencia": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Notas(); ok {
		if err := pago.NotasValidator(v); err != nil {
			return &ValidationError{Name: "notas", err: fmt.Errorf(`ent: validator failed for field "Pago.notas": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Estado(); ok {
		if err := pago.EstadoValidator(v); err != nil {
			return &ValidationError{Name: "estado", err: fmt.Errorf(`ent: validator failed for field "Pago.estado": %w`, err)}
		}
	}
	if _u.mutation.EmpresaCleared() && len(_u.mutation.EmpresaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Pago.empresa"`)
	}
	return nil
}

func (_u *PagoUpdateOne) sqlSave(ctx context.Context) (_node *Pago, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pago.Table, pago.Columns, sqlgraph.NewFieldSpec(pago.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pago.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pago.FieldID)
		for _, f := range fields {
			if !pago.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pago.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NumeroRecibo(); ok {
		_spec.SetField(pago.FieldNumeroRecibo, field.TypeString, value)
	}
	if value, ok := _u.mutation.FechaPago(); ok {
		_spec.SetField(pago.FieldFechaPago, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Moneda(); ok {
		_spec.SetField(pago.FieldMoneda, field.TypeString, value)
	}
	if value, ok := _u.mutation.MontoTotal(); ok {
		_spec.SetField(pago.FieldMontoTotal, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMontoTotal(); ok {
		_spec.AddField(pago.FieldMontoTotal, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Metodo(); ok {
		_spec.SetField(pago.FieldMetodo, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Referencia(); ok {
		_spec.SetField(pago.FieldReferencia, field.TypeString, value)
	}
	if _u.mutation.ReferenciaCleared() {
		_spec.ClearField(pago.FieldReferencia, field.TypeString)
	}
	if value, ok := _u.mutation.Notas(); ok {
		_spec.SetField(pago.FieldNotas, field.TypeString, value)
	}
	if _u.mutation.NotasCleared() {
		_spec.ClearField(pago.FieldNotas, field.TypeString)
	}
	if value, ok := _u.mutation.Estado(); ok {
		_spec.SetField(pago.FieldEstado, field.TypeEnum, value)
	}
	if _u.mutation.EmpresaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pago.EmpresaTable,
			Columns: []string{pago.EmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresa.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmpresaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pago.EmpresaTable,
			Columns: []string{pago.EmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresa.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClienteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pago.ClienteTable,
			Columns: []string{pago.ClienteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cliente.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClienteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pago.ClienteTable,
			Columns: []string{pago.ClienteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cliente.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContratoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pago.ContratoTable,
			Columns: []string{pago.ContratoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contrato.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContratoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pago.ContratoTable,
			Columns: []string{pago.ContratoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contrato.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AplicacionesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pago.AplicacionesTable,
			Columns: []string{pago.AplicacionesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pagoaplicacion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAplicacionesIDs(); len(nodes) > 0 && !_u.mutation.AplicacionesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pago.AplicacionesTable,
			Columns: []string{pago.AplicacionesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pagoaplicacion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AplicacionesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pago.AplicacionesTable,
			Columns: []string{pago.AplicacionesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pagoaplicacion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MovimientosCajaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pago.MovimientosCajaTable,
			Columns: []string{pago.MovimientosCajaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movimientocaja.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMovimientosCajaIDs(); len(nodes) > 0 && !_u.mutation.MovimientosCajaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pago.MovimientosCajaTable,
			Columns: []string{pago.MovimientosCajaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movimientocaja.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MovimientosCajaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pago.MovimientosCajaTable,
			Columns: []string{pago.MovimientosCajaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movimientocaja.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Pago{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pago.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
