// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rentals-go/ent/empresa"
	"rentals-go/ent/permiso"
	"rentals-go/ent/predicate"
	"rentals-go/ent/usuario"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PermisoUpdate is the builder for updating Permiso entities.
type PermisoUpdate struct {
	config
	hooks    []Hook
	mutation *PermisoMutation
}

// Where appends a list predicates to the PermisoUpdate builder.
func (_u *PermisoUpdate) Where(ps ...predicate.Permiso) *PermisoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmpresaID sets the "empresa_id" field.
func (_u *PermisoUpdate) SetEmpresaID(v int) *PermisoUpdate {
	_u.mutation.SetEmpresaID(v)
	return _u
}

// SetNillableEmpresaID sets the "empresa_id" field if the given value is not nil.
func (_u *PermisoUpdate) SetNillableEmpresaID(v *int) *PermisoUpdate {
	if v != nil {
		_u.SetEmpresaID(*v)
	}
	return _u
}

// SetUsuarioID sets the "usuario_id" field.
func (_u *PermisoUpdate) SetUsuarioID(v int) *PermisoUpdate {
	_u.mutation.SetUsuarioID(v)
	return _u
}

// SetNillableUsuarioID sets the "usuario_id" field if the given value is not nil.
func (_u *PermisoUpdate) SetNillableUsuarioID(v *int) *PermisoUpdate {
	if v != nil {
		_u.SetUsuarioID(*v)
	}
	return _u
}

// SetFecha sets the "fecha" field.
func (_u *PermisoUpdate) SetFecha(v time.Time) *PermisoUpdate {
	_u.mutation.SetFecha(v)
	return _u
}

// SetNillableFecha sets the "fecha" field if the given value is not nil.
func (_u *PermisoUpdate) SetNillableFecha(v *time.Time) *PermisoUpdate {
	if v != nil {
		_u.SetFecha(*v)
	}
	return _u
}

// SetMotivo sets the "motivo" field.
func (_u *PermisoUpdate) SetMotivo(v string) *PermisoUpdate {
	_u.mutation.SetMotivo(v)
	return _u
}

// SetNillableMotivo sets the "motivo" field if the given value is not nil.
func (_u *PermisoUpdate) SetNillableMotivo(v *string) *PermisoUpdate {
	if v != nil {
		_u.SetMotivo(*v)
	}
	return _u
}

// SetEstado sets the "estado" field.
func (_u *PermisoUpdate) SetEstado(v permiso.Estado) *PermisoUpdate {
	_u.mutation.SetEstado(v)
	return _u
}

// SetNillableEstado sets the "estado" field if the given value is not nil.
func (_u *PermisoUpdate) SetNillableEstado(v *permiso.Estado) *PermisoUpdate {
	if v != nil {
		_u.SetEstado(*v)
	}
	return _u
}

// SetRespuesta sets the "respuesta" field.
func (_u *PermisoUpdate) SetRespuesta(v string) *PermisoUpdate {
	_u.mutation.SetRespuesta(v)
	return _u
}

// SetNillableRespuesta sets the "respuesta" field if the given value is not nil.
func (_u *PermisoUpdate) SetNillableRespuesta(v *string) *PermisoUpdate {
	if v != nil {
		_u.SetRespuesta(*v)
	}
	return _u
}

// ClearRespuesta clears the value of the "respuesta" field.
func (_u *PermisoUpdate) ClearRespuesta() *PermisoUpdate {
	_u.mutation.ClearRespuesta()
	return _u
}

// SetEmpresa sets the "empresa" edge to the Empresa entity.
func (_u *PermisoUpdate) SetEmpresa(v *Empresa) *PermisoUpdate {
	return _u.SetEmpresaID(v.ID)
}

// SetUsuario sets the "usuario" edge to the Usuario entity.
func (_u *PermisoUpdate) SetUsuario(v *Usuario) *PermisoUpdate {
	return _u.SetUsuarioID(v.ID)
}

// Mutation returns the PermisoMutation object of the builder.
func (_u *PermisoUpdate) Mutation() *PermisoMutation {
	return _u.mutation
}

// ClearEmpresa clears the "empresa" edge to the Empresa entity.
func (_u *PermisoUpdate) ClearEmpresa() *PermisoUpdate {
	_u.mutation.ClearEmpresa()
	return _u
}

// ClearUsuario clears the "usuario" edge to the Usuario entity.
func (_u *PermisoUpdate) ClearUsuario() *PermisoUpdate {
	_u.mutation.ClearUsuario()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PermisoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PermisoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PermisoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PermisoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PermisoUpdate) check() error {
	if v, ok := _u.mutation.Motivo(); ok {
		if err := permiso.MotivoValidator(v); err != nil {
			return &ValidationError{Name: "motivo", err: fmt.Errorf(`ent: validator failed for field "Permiso.motivo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Estado(); ok {
		if err := permiso.EstadoValidator(v); err != nil {
			return &ValidationError{Name: "estado", err: fmt.Errorf(`ent: validator failed for field "Permiso.estado": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Respuesta(); ok {
		if err := permiso.RespuestaValidator(v); err != nil {
			return &ValidationError{Name: "respuesta", err: fmt.Errorf(`ent: validator failed for field "Permiso.respuesta": %w`, err)}
		}
	}
	if _u.mutation.EmpresaCleared() && len(_u.mutation.EmpresaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Permiso.empresa"`)
	}
	if _u.mutation.UsuarioCleared() && len(_u.mutation.UsuarioIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Permiso.usuario"`)
	}
	return nil
}

func (_u *PermisoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(permiso.Table, permiso.Columns, sqlgraph.NewFieldSpec(permiso.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Fecha(); ok {
		_spec.SetField(permiso.FieldFecha, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Motivo(); ok {
		_spec.SetField(permiso.FieldMotivo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Estado(); ok {
		_spec.SetField(permiso.FieldEstado, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Respuesta(); ok {
		_spec.SetField(permiso.FieldRespuesta, field.TypeString, value)
	}
	if _u.mutation.RespuestaCleared() {
		_spec.ClearField(permiso.FieldRespuesta, field.TypeString)
	}
	if _u.mutation.EmpresaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permiso.EmpresaTable,
			Columns: []string{permiso.EmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresa.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmpresaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permiso.EmpresaTable,
			Columns: []string{permiso.EmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresa.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsuarioCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permiso.UsuarioTable,
			Columns: []string{permiso.UsuarioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usuario.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsuarioIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permiso.UsuarioTable,
			Columns: []string{permiso.UsuarioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usuario.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permiso.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PermisoUpdateOne is the builder for updating a single Permiso entity.
type PermisoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PermisoMutation
}

// SetEmpresaID sets the "empresa_id" field.
func (_u *PermisoUpdateOne) SetEmpresaID(v int) *PermisoUpdateOne {
	_u.mutation.SetEmpresaID(v)
	return _u
}

// SetNillableEmpresaID sets the "empresa_id" field if the given value is not nil.
func (_u *PermisoUpdateOne) SetNillableEmpresaID(v *int) *PermisoUpdateOne {
	if v != nil {
		_u.SetEmpresaID(*v)
	}
	return _u
}

// SetUsuarioID sets the "usuario_id" field.
func (_u *PermisoUpdateOne) SetUsuarioID(v int) *PermisoUpdateOne {
	_u.mutation.SetUsuarioID(v)
	return _u
}

// SetNillableUsuarioID sets the "usuario_id" field if the given value is not nil.
func (_u *PermisoUpdateOne) SetNillableUsuarioID(v *int) *PermisoUpdateOne {
	if v != nil {
		_u.SetUsuarioID(*v)
	}
	return _u
}

// SetFecha sets the "fecha" field.
func (_u *PermisoUpdateOne) SetFecha(v time.Time) *PermisoUpdateOne {
	_u.mutation.SetFecha(v)
	return _u
}

// SetNillableFecha sets the "fecha" field if the given value is not nil.
func (_u *PermisoUpdateOne) SetNillableFecha(v *time.Time) *PermisoUpdateOne {
	if v != nil {
		_u.SetFecha(*v)
	}
	return _u
}

// SetMotivo sets the "motivo" field.
func (_u *PermisoUpdateOne) SetMotivo(v string) *PermisoUpdateOne {
	_u.mutation.SetMotivo(v)
	return _u
}

// SetNillableMotivo sets the "motivo" field if the given value is not nil.
func (_u *PermisoUpdateOne) SetNillableMotivo(v *string) *PermisoUpdateOne {
	if v != nil {
		_u.SetMotivo(*v)
	}
	return _u
}

// SetEstado sets the "estado" field.
func (_u *PermisoUpdateOne) SetEstado(v permiso.Estado) *PermisoUpdateOne {
	_u.mutation.SetEstado(v)
	return _u
}

// SetNillableEstado sets the "estado" field if the given value is not nil.
func (_u *PermisoUpdateOne) SetNillableEstado(v *permiso.Estado) *PermisoUpdateOne {
	if v != nil {
		_u.SetEstado(*v)
	}
	return _u
}

// SetRespuesta sets the "respuesta" field.
func (_u *PermisoUpdateOne) SetRespuesta(v string) *PermisoUpdateOne {
	_u.mutation.SetRespuesta(v)
	return _u
}

// SetNillableRespuesta sets the "respuesta" field if the given value is not nil.
func (_u *PermisoUpdateOne) SetNillableRespuesta(v *string) *PermisoUpdateOne {
	if v != nil {
		_u.SetRespuesta(*v)
	}
	return _u
}

// ClearRespuesta clears the value of the "respuesta" field.
func (_u *PermisoUpdateOne) ClearRespuesta() *PermisoUpdateOne {
	_u.mutation.ClearRespuesta()
	return _u
}

// SetEmpresa sets the "empresa" edge to the Empresa entity.
func (_u *PermisoUpdateOne) SetEmpresa(v *Empresa) *PermisoUpdateOne {
	return _u.SetEmpresaID(v.ID)
}

// SetUsuario sets the "usuario" edge to the Usuario entity.
func (_u *PermisoUpdateOne) SetUsuario(v *Usuario) *PermisoUpdateOne {
	return _u.SetUsuarioID(v.ID)
}

// Mutation returns the PermisoMutation object of the builder.
func (_u *PermisoUpdateOne) Mutation() *PermisoMutation {
	return _u.mutation
}

// ClearEmpresa clears the "empresa" edge to the Empresa entity.
func (_u *PermisoUpdateOne) ClearEmpresa() *PermisoUpdateOne {
	_u.mutation.ClearEmpresa()
	return _u
}

// ClearUsuario clears the "usuario" edge to the Usuario entity.
func (_u *PermisoUpdateOne) ClearUsuario() *PermisoUpdateOne {
	_u.mutation.ClearUsuario()
	return _u
}

// Where appends a list predicates to the PermisoUpdate builder.
func (_u *PermisoUpdateOne) Where(ps ...predicate.Permiso) *PermisoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PermisoUpdateOne) Select(field string, fields ...string) *PermisoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Permiso entity.
func (_u *PermisoUpdateOne) Save(ctx context.Context) (*Permiso, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PermisoUpdateOne) SaveX(ctx context.Context) *Permiso {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PermisoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PermisoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PermisoUpdateOne) check() error {
	if v, ok := _u.mutation.Motivo(); ok {
		if err := permiso.MotivoValidator(v); err != nil {
			return &ValidationError{Name: "motivo", err: fmt.Errorf(`ent: validator failed for field "Permiso.motivo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Estado(); ok {
		if err := permiso.EstadoValidator(v); err != nil {
			return &ValidationError{Name: "estado", err: fmt.Errorf(`ent: validator failed for field "Permiso.estado": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Respuesta(); ok {
		if err := permiso.RespuestaValidator(v); err != nil {
			return &ValidationError{Name: "respuesta", err: fmt.Errorf(`ent: validator failed for field "Permiso.respuesta": %w`, err)}
		}
	}
	if _u.mutation.EmpresaCleared() && len(_u.mutation.EmpresaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Permiso.empresa"`)
	}
	if _u.mutation.UsuarioCleared() && len(_u.mutation.UsuarioIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Permiso.usuario"`)
	}
	return nil
}

func (_u *PermisoUpdateOne) sqlSave(ctx context.Context) (_node *Permiso, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(permiso.Table, permiso.Columns, sqlgraph.NewFieldSpec(permiso.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Permiso.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, permiso.FieldID)
		for _, f := range fields {
			if !permiso.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != permiso.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Fecha(); ok {
		_spec.SetField(permiso.FieldFecha, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Motivo(); ok {
		_spec.SetField(permiso.FieldMotivo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Estado(); ok {
		_spec.SetField(permiso.FieldEstado, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Respuesta(); ok {
		_spec.SetField(permiso.FieldRespuesta, field.TypeString, value)
	}
	if _u.mutation.RespuestaCleared() {
		_spec.ClearField(permiso.FieldRespuesta, field.TypeString)
	}
	if _u.mutation.EmpresaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permiso.EmpresaTable,
			Columns: []string{permiso.EmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresa.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmpresaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permiso.EmpresaTable,
			Columns: []string{permiso.EmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresa.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsuarioCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permiso.UsuarioTable,
			Columns: []string{permiso.UsuarioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usuario.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsuarioIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permiso.UsuarioTable,
			Columns: []string{permiso.UsuarioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usuario.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Permiso{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permiso.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
