// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"rentals-go/ent/empresa"
	"rentals-go/ent/permiso"
	"rentals-go/ent/predicate"
	"rentals-go/ent/usuario"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PermisoQuery is the builder for querying Permiso entities.
type PermisoQuery struct {
	config
	ctx         *QueryContext
	order       []permiso.OrderOption
	inters      []Interceptor
	predicates  []predicate.Permiso
	withEmpresa *EmpresaQuery
	withUsuario *UsuarioQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PermisoQuery builder.
func (_q *PermisoQuery) Where(ps ...predicate.Permiso) *PermisoQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PermisoQuery) Limit(limit int) *PermisoQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PermisoQuery) Offset(offset int) *PermisoQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PermisoQuery) Unique(unique bool) *PermisoQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PermisoQuery) Order(o ...permiso.OrderOption) *PermisoQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryEmpresa chains the current query on the "empresa" edge.
func (_q *PermisoQuery) QueryEmpresa() *EmpresaQuery {
	query := (&EmpresaClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(permiso.Table, permiso.FieldID, selector),
			sqlgraph.To(empresa.Table, empresa.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, permiso.EmpresaTable, permiso.EmpresaColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUsuario chains the current query on the "usuario" edge.
func (_q *PermisoQuery) QueryUsuario() *UsuarioQuery {
	query := (&UsuarioClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(permiso.Table, permiso.FieldID, selector),
			sqlgraph.To(usuario.Table, usuario.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, permiso.UsuarioTable, permiso.UsuarioColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Permiso entity from the query.
// Returns a *NotFoundError when no Permiso was found.
func (_q *PermisoQuery) First(ctx context.Context) (*Permiso, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{permiso.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PermisoQuery) FirstX(ctx context.Context) *Permiso {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Permiso ID from the query.
// Returns a *NotFoundError when no Permiso ID was found.
func (_q *PermisoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{permiso.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PermisoQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Permiso entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Permiso entity is found.
// Returns a *NotFoundError when no Permiso entities are found.
func (_q *PermisoQuery) Only(ctx context.Context) (*Permiso, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{permiso.Label}
	default:
		return nil, &NotSingularError{permiso.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PermisoQuery) OnlyX(ctx context.Context) *Permiso {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Permiso ID in the query.
// Returns a *NotSingularError when more than one Permiso ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PermisoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{permiso.Label}
	default:
		err = &NotSingularError{permiso.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PermisoQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Permisos.
func (_q *PermisoQuery) All(ctx context.Context) ([]*Permiso, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Permiso, *PermisoQuery]()
	return withInterceptors[[]*Permiso](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PermisoQuery) AllX(ctx context.Context) []*Permiso {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Permiso IDs.
func (_q *PermisoQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(permiso.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PermisoQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PermisoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PermisoQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PermisoQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PermisoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PermisoQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PermisoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PermisoQuery) Clone() *PermisoQuery {
	if _q == nil {
		return nil
	}
	return &PermisoQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]permiso.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.Permiso{}, _q.predicates...),
		withEmpresa: _q.withEmpresa.Clone(),
		withUsuario: _q.withUsuario.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithEmpresa tells the query-builder to eager-load the nodes that are connected to
// the "empresa" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PermisoQuery) WithEmpresa(opts ...func(*EmpresaQuery)) *PermisoQuery {
	query := (&EmpresaClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEmpresa = query
	return _q
}

// WithUsuario tells the query-builder to eager-load the nodes that are connected to
// the "usuario" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PermisoQuery) WithUsuario(opts ...func(*UsuarioQuery)) *PermisoQuery {
	query := (&UsuarioClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUsuario = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreadoEn time.Time `json:"creado_en,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Permiso.Query().
//		GroupBy(permiso.FieldCreadoEn).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PermisoQuery) GroupBy(field string, fields ...string) *PermisoGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PermisoGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = permiso.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreadoEn time.Time `json:"creado_en,omitempty"`
//	}
//
//	client.Permiso.Query().
//		Select(permiso.FieldCreadoEn).
//		Scan(ctx, &v)
func (_q *PermisoQuery) Select(fields ...string) *PermisoSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PermisoSelect{PermisoQuery: _q}
	sbuild.label = permiso.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PermisoSelect configured with the given aggregations.
func (_q *PermisoQuery) Aggregate(fns ...AggregateFunc) *PermisoSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PermisoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !permiso.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PermisoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Permiso, error) {
	var (
		nodes       = []*Permiso{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withEmpresa != nil,
			_q.withUsuario != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Permiso).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Permiso{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withEmpresa; query != nil {
		if err := _q.loadEmpresa(ctx, query, nodes, nil,
			func(n *Permiso, e *Empresa) { n.Edges.Empresa = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUsuario; query != nil {
		if err := _q.loadUsuario(ctx, query, nodes, nil,
			func(n *Permiso, e *Usuario) { n.Edges.Usuario = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PermisoQuery) loadEmpresa(ctx context.Context, query *EmpresaQuery, nodes []*Permiso, init func(*Permiso), assign func(*Permiso, *Empresa)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Permiso)
	for i := range nodes {
		fk := nodes[i].EmpresaID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(empresa.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "empresa_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PermisoQuery) loadUsuario(ctx context.Context, query *UsuarioQuery, nodes []*Permiso, init func(*Permiso), assign func(*Permiso, *Usuario)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Permiso)
	for i := range nodes {
		fk := nodes[i].UsuarioID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(usuario.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "usuario_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PermisoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PermisoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(permiso.Table, permiso.Columns, sqlgraph.NewFieldSpec(permiso.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, permiso.FieldID)
		for i := range fields {
			if fields[i] != permiso.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withEmpresa != nil {
			_spec.Node.AddColumnOnce(permiso.FieldEmpresaID)
		}
		if _q.withUsuario != nil {
			_spec.Node.AddColumnOnce(permiso.FieldUsuarioID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PermisoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(permiso.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = permiso.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PermisoGroupBy is the group-by builder for Permiso entities.
type PermisoGroupBy struct {
	selector
	build *PermisoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PermisoGroupBy) Aggregate(fns ...AggregateFunc) *PermisoGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PermisoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PermisoQuery, *PermisoGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PermisoGroupBy) sqlScan(ctx context.Context, root *PermisoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PermisoSelect is the builder for selecting fields of Permiso entities.
type PermisoSelect struct {
	*PermisoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PermisoSelect) Aggregate(fns ...AggregateFunc) *PermisoSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PermisoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PermisoQuery, *PermisoSelect](ctx, _s.PermisoQuery, _s, _s.inters, v)
}

func (_s *PermisoSelect) sqlScan(ctx context.Context, root *PermisoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
