// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"rentals-go/ent/rol"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Rol is the model entity for the Rol schema.
type Rol struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Nombre holds the value of the "nombre" field.
	Nombre string `json:"nombre,omitempty"`
	// Descripcion holds the value of the "descripcion" field.
	Descripcion *string `json:"descripcion,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RolQuery when eager-loading is set.
	Edges        RolEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RolEdges holds the relations/edges for other nodes in the graph.
type RolEdges struct {
	// UsuariosEmpresa holds the value of the usuarios_empresa edge.
	UsuariosEmpresa []*EmpresaUsuario `json:"usuarios_empresa,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UsuariosEmpresaOrErr returns the UsuariosEmpresa value or an error if the edge
// was not loaded in eager-loading.
func (e RolEdges) UsuariosEmpresaOrErr() ([]*EmpresaUsuario, error) {
	if e.loadedTypes[0] {
		return e.UsuariosEmpresa, nil
	}
	return nil, &NotLoadedError{edge: "usuarios_empresa"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Rol) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rol.FieldID:
			values[i] = new(sql.NullInt64)
		case rol.FieldNombre, rol.FieldDescripcion:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Rol fields.
func (_m *Rol) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rol.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case rol.FieldNombre:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nombre", values[i])
			} else if value.Valid {
				_m.Nombre = value.String
			}
		case rol.FieldDescripcion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field descripcion", values[i])
			} else if value.Valid {
				_m.Descripcion = new(string)
				*_m.Descripcion = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Rol.
// This includes values selected through modifiers, order, etc.
func (_m *Rol) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsuariosEmpresa queries the "usuarios_empresa" edge of the Rol entity.
func (_m *Rol) QueryUsuariosEmpresa() *EmpresaUsuarioQuery {
	return NewRolClient(_m.config).QueryUsuariosEmpresa(_m)
}

// Update returns a builder for updating this Rol.
// Note that you need to call Rol.Unwrap() before calling this method if this Rol
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Rol) Update() *RolUpdateOne {
	return NewRolClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Rol entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Rol) Unwrap() *Rol {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Rol is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Rol) String() string {
	var builder strings.Builder
	builder.WriteString("Rol(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("nombre=")
	builder.WriteString(_m.Nombre)
	builder.WriteString(", ")
	if v := _m.Descripcion; v != nil {
		builder.WriteString("descripcion=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// Rols is a parsable slice of Rol.
type Rols []*Rol
