// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rentals-go/ent/empresausuario"
	"rentals-go/ent/predicate"
	"rentals-go/ent/rol"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RolUpdate is the builder for updating Rol entities.
type RolUpdate struct {
	config
	hooks    []Hook
	mutation *RolMutation
}

// Where appends a list predicates to the RolUpdate builder.
func (_u *RolUpdate) Where(ps ...predicate.Rol) *RolUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNombre sets the "nombre" field.
func (_u *RolUpdate) SetNombre(v string) *RolUpdate {
	_u.mutation.SetNombre(v)
	return _u
}

// SetNillableNombre sets the "nombre" field if the given value is not nil.
func (_u *RolUpdate) SetNillableNombre(v *string) *RolUpdate {
	if v != nil {
		_u.SetNombre(*v)
	}
	return _u
}

// SetDescripcion sets the "descripcion" field.
func (_u *RolUpdate) SetDescripcion(v string) *RolUpdate {
	_u.mutation.SetDescripcion(v)
	return _u
}

// SetNillableDescripcion sets the "descripcion" field if the given value is not nil.
func (_u *RolUpdate) SetNillableDescripcion(v *string) *RolUpdate {
	if v != nil {
		_u.SetDescripcion(*v)
	}
	return _u
}

// ClearDescripcion clears the value of the "descripcion" field.
func (_u *RolUpdate) ClearDescripcion() *RolUpdate {
	_u.mutation.ClearDescripcion()
	return _u
}

// AddUsuariosEmpresaIDs adds the "usuarios_empresa" edge to the EmpresaUsuario entity by IDs.
func (_u *RolUpdate) AddUsuariosEmpresaIDs(ids ...int) *RolUpdate {
	_u.mutation.AddUsuariosEmpresaIDs(ids...)
	return _u
}

// AddUsuariosEmpresa adds the "usuarios_empresa" edges to the EmpresaUsuario entity.
func (_u *RolUpdate) AddUsuariosEmpresa(v ...*EmpresaUsuario) *RolUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsuariosEmpresaIDs(ids...)
}

// Mutation returns the RolMutation object of the builder.
func (_u *RolUpdate) Mutation() *RolMutation {
	return _u.mutation
}

// ClearUsuariosEmpresa clears all "usuarios_empresa" edges to the EmpresaUsuario entity.
func (_u *RolUpdate) ClearUsuariosEmpresa() *RolUpdate {
	_u.mutation.ClearUsuariosEmpresa()
	return _u
}

// RemoveUsuariosEmpresaIDs removes the "usuarios_empresa" edge to EmpresaUsuario entities by IDs.
func (_u *RolUpdate) RemoveUsuariosEmpresaIDs(ids ...int) *RolUpdate {
	_u.mutation.RemoveUsuariosEmpresaIDs(ids...)
	return _u
}

// RemoveUsuariosEmpresa removes "usuarios_empresa" edges to EmpresaUsuario entities.
func (_u *RolUpdate) RemoveUsuariosEmpresa(v ...*EmpresaUsuario) *RolUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsuariosEmpresaIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RolUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RolUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RolUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RolUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RolUpdate) check() error {
	if v, ok := _u.mutation.Nombre(); ok {
		if err := rol.NombreValidator(v); err != nil {
			return &ValidationError{Name: "nombre", err: fmt.Errorf(`ent: validator failed for field "Rol.nombre": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Descripcion(); ok {
		if err := rol.DescripcionValidator(v); err != nil {
			return &ValidationError{Name: "descripcion", err: fmt.Errorf(`ent: validator failed for field "Rol.descripcion": %w`, err)}
		}
	}
	return nil
}

func (_u *RolUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rol.Table, rol.Columns, sqlgraph.NewFieldSpec(rol.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Nombre(); ok {
		_spec.SetField(rol.FieldNombre, field.TypeString, value)
	}
	if value, ok := _u.mutation.Descripcion(); ok {
		_spec.SetField(rol.FieldDescripcion, field.TypeString, value)
	}
	if _u.mutation.DescripcionCleared() {
		_spec.ClearField(rol.FieldDescripcion, field.TypeString)
	}
	if _u.mutation.UsuariosEmpresaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rol.UsuariosEmpresaTable,
			Columns: []string{rol.UsuariosEmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresausuario.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsuariosEmpresaIDs(); len(nodes) > 0 && !_u.mutation.UsuariosEmpresaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rol.UsuariosEmpresaTable,
			Columns: []string{rol.UsuariosEmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresausuario.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsuariosEmpresaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rol.UsuariosEmpresaTable,
			Columns: []string{rol.UsuariosEmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresausuario.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rol.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RolUpdateOne is the builder for updating a single Rol entity.
type RolUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RolMutation
}

// SetNombre sets the "nombre" field.
func (_u *RolUpdateOne) SetNombre(v string) *RolUpdateOne {
	_u.mutation.SetNombre(v)
	return _u
}

// SetNillableNombre sets the "nombre" field if the given value is not nil.
func (_u *RolUpdateOne) SetNillableNombre(v *string) *RolUpdateOne {
	if v != nil {
		_u.SetNombre(*v)
	}
	return _u
}

// SetDescripcion sets the "descripcion" field.
func (_u *RolUpdateOne) SetDescripcion(v string) *RolUpdateOne {
	_u.mutation.SetDescripcion(v)
	return _u
}

// SetNillableDescripcion sets the "descripcion" field if the given value is not nil.
func (_u *RolUpdateOne) SetNillableDescripcion(v *string) *RolUpdateOne {
	if v != nil {
		_u.SetDescripcion(*v)
	}
	return _u
}

// ClearDescripcion clears the value of the "descripcion" field.
func (_u *RolUpdateOne) ClearDescripcion() *RolUpdateOne {
	_u.mutation.ClearDescripcion()
	return _u
}

// AddUsuariosEmpresaIDs adds the "usuarios_empresa" edge to the EmpresaUsuario entity by IDs.
func (_u *RolUpdateOne) AddUsuariosEmpresaIDs(ids ...int) *RolUpdateOne {
	_u.mutation.AddUsuariosEmpresaIDs(ids...)
	return _u
}

// AddUsuariosEmpresa adds the "usuarios_empresa" edges to the EmpresaUsuario entity.
func (_u *RolUpdateOne) AddUsuariosEmpresa(v ...*EmpresaUsuario) *RolUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsuariosEmpresaIDs(ids...)
}

// Mutation returns the RolMutation object of the builder.
func (_u *RolUpdateOne) Mutation() *RolMutation {
	return _u.mutation
}

// ClearUsuariosEmpresa clears all "usuarios_empresa" edges to the EmpresaUsuario entity.
func (_u *RolUpdateOne) ClearUsuariosEmpresa() *RolUpdateOne {
	_u.mutation.ClearUsuariosEmpresa()
	return _u
}

// RemoveUsuariosEmpresaIDs removes the "usuarios_empresa" edge to EmpresaUsuario entities by IDs.
func (_u *RolUpdateOne) RemoveUsuariosEmpresaIDs(ids ...int) *RolUpdateOne {
	_u.mutation.RemoveUsuariosEmpresaIDs(ids...)
	return _u
}

// RemoveUsuariosEmpresa removes "usuarios_empresa" edges to EmpresaUsuario entities.
func (_u *RolUpdateOne) RemoveUsuariosEmpresa(v ...*EmpresaUsuario) *RolUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsuariosEmpresaIDs(ids...)
}

// Where appends a list predicates to the RolUpdate builder.
func (_u *RolUpdateOne) Where(ps ...predicate.Rol) *RolUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RolUpdateOne) Select(field string, fields ...string) *RolUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Rol entity.
func (_u *RolUpdateOne) Save(ctx context.Context) (*Rol, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RolUpdateOne) SaveX(ctx context.Context) *Rol {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RolUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RolUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RolUpdateOne) check() error {
	if v, ok := _u.mutation.Nombre(); ok {
		if err := rol.NombreValidator(v); err != nil {
			return &ValidationError{Name: "nombre", err: fmt.Errorf(`ent: validator failed for field "Rol.nombre": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Descripcion(); ok {
		if err := rol.DescripcionValidator(v); err != nil {
			return &ValidationError{Name: "descripcion", err: fmt.Errorf(`ent: validator failed for field "Rol.descripcion": %w`, err)}
		}
	}
	return nil
}

func (_u *RolUpdateOne) sqlSave(ctx context.Context) (_node *Rol, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rol.Table, rol.Columns, sqlgraph.NewFieldSpec(rol.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Rol.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rol.FieldID)
		for _, f := range fields {
			if !rol.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rol.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Nombre(); ok {
		_spec.SetField(rol.FieldNombre, field.TypeString, value)
	}
	if value, ok := _u.mutation.Descripcion(); ok {
		_spec.SetField(rol.FieldDescripcion, field.TypeString, value)
	}
	if _u.mutation.DescripcionCleared() {
		_spec.ClearField(rol.FieldDescripcion, field.TypeString)
	}
	if _u.mutation.UsuariosEmpresaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rol.UsuariosEmpresaTable,
			Columns: []string{rol.UsuariosEmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresausuario.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsuariosEmpresaIDs(); len(nodes) > 0 && !_u.mutation.UsuariosEmpresaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rol.UsuariosEmpresaTable,
			Columns: []string{rol.UsuariosEmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresausuario.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsuariosEmpresaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rol.UsuariosEmpresaTable,
			Columns: []string{rol.UsuariosEmpresaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresausuario.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Rol{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rol.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
