// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rentals-go/ent/gasto"
	"rentals-go/ent/tipopago"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TipoPagoCreate is the builder for creating a TipoPago entity.
type TipoPagoCreate struct {
	config
	mutation *TipoPagoMutation
	hooks    []Hook
}

// SetNombre sets the "nombre" field.
func (_c *TipoPagoCreate) SetNombre(v string) *TipoPagoCreate {
	_c.mutation.SetNombre(v)
	return _c
}

// AddGastoIDs adds the "gastos" edge to the Gasto entity by IDs.
func (_c *TipoPagoCreate) AddGastoIDs(ids ...int) *TipoPagoCreate {
	_c.mutation.AddGastoIDs(ids...)
	return _c
}

// AddGastos adds the "gastos" edges to the Gasto entity.
func (_c *TipoPagoCreate) AddGastos(v ...*Gasto) *TipoPagoCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGastoIDs(ids...)
}

// Mutation returns the TipoPagoMutation object of the builder.
func (_c *TipoPagoCreate) Mutation() *TipoPagoMutation {
	return _c.mutation
}

// Save creates the TipoPago in the database.
func (_c *TipoPagoCreate) Save(ctx context.Context) (*TipoPago, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TipoPagoCreate) SaveX(ctx context.Context) *TipoPago {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TipoPagoCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TipoPagoCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TipoPagoCreate) check() error {
	if _, ok := _c.mutation.Nombre(); !ok {
		return &ValidationError{Name: "nombre", err: errors.New(`ent: missing required field "TipoPago.nombre"`)}
	}
	if v, ok := _c.mutation.Nombre(); ok {
		if err := tipopago.NombreValidator(v); err != nil {
			return &ValidationError{Name: "nombre", err: fmt.Errorf(`ent: validator failed for field "TipoPago.nombre": %w`, err)}
		}
	}
	return nil
}

func (_c *TipoPagoCreate) sqlSave(ctx context.Context) (*TipoPago, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TipoPagoCreate) createSpec() (*TipoPago, *sqlgraph.CreateSpec) {
	var (
		_node = &TipoPago{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tipopago.Table, sqlgraph.NewFieldSpec(tipopago.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Nombre(); ok {
		_spec.SetField(tipopago.FieldNombre, field.TypeString, value)
		_node.Nombre = value
	}
	if nodes := _c.mutation.GastosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tipopago.GastosTable,
			Columns: []string{tipopago.GastosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gasto.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TipoPagoCreateBulk is the builder for creating many TipoPago entities in bulk.
type TipoPagoCreateBulk struct {
	config
	err      error
	builders []*TipoPagoCreate
}

// Save creates the TipoPago entities in the database.
func (_c *TipoPagoCreateBulk) Save(ctx context.Context) ([]*TipoPago, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TipoPago, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TipoPagoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TipoPagoCreateBulk) SaveX(ctx context.Context) []*TipoPago {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TipoPagoCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TipoPagoCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
