// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rentals-go/ent/contrato"
	"rentals-go/ent/gasto"
	"rentals-go/ent/predicate"
	"rentals-go/ent/propiedad"
	"rentals-go/ent/serviciomedicion"
	"rentals-go/ent/unidad"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UnidadUpdate is the builder for updating Unidad entities.
type UnidadUpdate struct {
	config
	hooks    []Hook
	mutation *UnidadMutation
}

// Where appends a list predicates to the UnidadUpdate builder.
func (_u *UnidadUpdate) Where(ps ...predicate.Unidad) *UnidadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetActualizadoEn sets the "actualizado_en" field.
func (_u *UnidadUpdate) SetActualizadoEn(v time.Time) *UnidadUpdate {
	_u.mutation.SetActualizadoEn(v)
	return _u
}

// SetPropiedadID sets the "propiedad_id" field.
func (_u *UnidadUpdate) SetPropiedadID(v int) *UnidadUpdate {
	_u.mutation.SetPropiedadID(v)
	return _u
}

// SetNillablePropiedadID sets the "propiedad_id" field if the given value is not nil.
func (_u *UnidadUpdate) SetNillablePropiedadID(v *int) *UnidadUpdate {
	if v != nil {
		_u.SetPropiedadID(*v)
	}
	return _u
}

// SetCodigo sets the "codigo" field.
func (_u *UnidadUpdate) SetCodigo(v string) *UnidadUpdate {
	_u.mutation.SetCodigo(v)
	return _u
}

// SetNillableCodigo sets the "codigo" field if the given value is not nil.
func (_u *UnidadUpdate) SetNillableCodigo(v *string) *UnidadUpdate {
	if v != nil {
		_u.SetCodigo(*v)
	}
	return _u
}

// SetNombre sets the "nombre" field.
func (_u *UnidadUpdate) SetNombre(v string) *UnidadUpdate {
	_u.mutation.SetNombre(v)
	return _u
}

// SetNillableNombre sets the "nombre" field if the given value is not nil.
func (_u *UnidadUpdate) SetNillableNombre(v *string) *UnidadUpdate {
	if v != nil {
		_u.SetNombre(*v)
	}
	return _u
}

// ClearNombre clears the value of the "nombre" field.
func (_u *UnidadUpdate) ClearNombre() *UnidadUpdate {
	_u.mutation.ClearNombre()
	return _u
}

// SetTipo sets the "tipo" field.
func (_u *UnidadUpdate) SetTipo(v unidad.Tipo) *UnidadUpdate {
	_u.mutation.SetTipo(v)
	return _u
}

// SetNillableTipo sets the "tipo" field if the given value is not nil.
func (_u *UnidadUpdate) SetNillableTipo(v *unidad.Tipo) *UnidadUpdate {
	if v != nil {
		_u.SetTipo(*v)
	}
	return _u
}

// SetNumeroPiso sets the "numero_piso" field.
func (_u *UnidadUpdate) SetNumeroPiso(v int) *UnidadUpdate {
	_u.mutation.ResetNumeroPiso()
	_u.mutation.SetNumeroPiso(v)
	return _u
}

// SetNillableNumeroPiso sets the "numero_piso" field if the given value is not nil.
func (_u *UnidadUpdate) SetNillableNumeroPiso(v *int) *UnidadUpdate {
	if v != nil {
		_u.SetNumeroPiso(*v)
	}
	return _u
}

// AddNumeroPiso adds value to the "numero_piso" field.
func (_u *UnidadUpdate) AddNumeroPiso(v int) *UnidadUpdate {
	_u.mutation.AddNumeroPiso(v)
	return _u
}

// ClearNumeroPiso clears the value of the "numero_piso" field.
func (_u *UnidadUpdate) ClearNumeroPiso() *UnidadUpdate {
	_u.mutation.ClearNumeroPiso()
	return _u
}

// SetDormitorios sets the "dormitorios" field.
func (_u *UnidadUpdate) SetDormitorios(v int) *UnidadUpdate {
	_u.mutation.ResetDormitorios()
	_u.mutation.SetDormitorios(v)
	return _u
}

// SetNillableDormitorios sets the "dormitorios" field if the given value is not nil.
func (_u *UnidadUpdate) SetNillableDormitorios(v *int) *UnidadUpdate {
	if v != nil {
		_u.SetDormitorios(*v)
	}
	return _u
}

// AddDormitorios adds value to the "dormitorios" field.
func (_u *UnidadUpdate) AddDormitorios(v int) *UnidadUpdate {
	_u.mutation.AddDormitorios(v)
	return _u
}

// SetBanos sets the "banos" field.
func (_u *UnidadUpdate) SetBanos(v int) *UnidadUpdate {
	_u.mutation.ResetBanos()
	_u.mutation.SetBanos(v)
	return _u
}

// SetNillableBanos sets the "banos" field if the given value is not nil.
func (_u *UnidadUpdate) SetNillableBanos(v *int) *UnidadUpdate {
	if v != nil {
		_u.SetBanos(*v)
	}
	return _u
}

// AddBanos adds value to the "banos" field.
func (_u *UnidadUpdate) AddBanos(v int) *UnidadUpdate {
	_u.mutation.AddBanos(v)
	return _u
}

// SetAreaM2 sets the "area_m2" field.
func (_u *UnidadUpdate) SetAreaM2(v float64) *UnidadUpdate {
	_u.mutation.ResetAreaM2()
	_u.mutation.SetAreaM2(v)
	return _u
}

// SetNillableAreaM2 sets the "area_m2" field if the given value is not nil.
func (_u *UnidadUpdate) SetNillableAreaM2(v *float64) *UnidadUpdate {
	if v != nil {
		_u.SetAreaM2(*v)
	}
	return _u
}

// AddAreaM2 adds value to the "area_m2" field.
func (_u *UnidadUpdate) AddAreaM2(v float64) *UnidadUpdate {
	_u.mutation.AddAreaM2(v)
	return _u
}

// ClearAreaM2 clears the value of the "area_m2" field.
func (_u *UnidadUpdate) ClearAreaM2() *UnidadUpdate {
	_u.mutation.ClearAreaM2()
	return _u
}

// SetCapacidad sets the "capacidad" field.
func (_u *UnidadUpdate) SetCapacidad(v int) *UnidadUpdate {
	_u.mutation.ResetCapacidad()
	_u.mutation.SetCapacidad(v)
	return _u
}

// SetNillableCapacidad sets the "capacidad" field if the given value is not nil.
func (_u *UnidadUpdate) SetNillableCapacidad(v *int) *UnidadUpdate {
	if v != nil {
		_u.SetCapacidad(*v)
	}
	return _u
}

// AddCapacidad adds value to the "capacidad" field.
func (_u *UnidadUpdate) AddCapacidad(v int) *UnidadUpdate {
	_u.mutation.AddCapacidad(v)
	return _u
}

// SetMoneda sets the "moneda" field.
func (_u *UnidadUpdate) SetMoneda(v string) *UnidadUpdate {
	_u.mutation.SetMoneda(v)
	return _u
}

// SetNillableMoneda sets the "moneda" field if the given value is not nil.
func (_u *UnidadUpdate) SetNillableMoneda(v *string) *UnidadUpdate {
	if v != nil {
		_u.SetMoneda(*v)
	}
	return _u
}

// SetPrecioBase sets the "precio_base" field.
func (_u *UnidadUpdate) SetPrecioBase(v int64) *UnidadUpdate {
	_u.mutation.ResetPrecioBase()
	_u.mutation.SetPrecioBase(v)
	return _u
}

// SetNillablePrecioBase sets the "precio_base" field if the given value is not nil.
func (_u *UnidadUpdate) SetNillablePrecioBase(v *int64) *UnidadUpdate {
	if v != nil {
		_u.SetPrecioBase(*v)
	}
	return _u
}

// AddPrecioBase adds value to the "precio_base" field.
func (_u *UnidadUpdate) AddPrecioBase(v int64) *UnidadUpdate {
	_u.mutation.AddPrecioBase(v)
	return _u
}

// SetDepositoRequerido sets the "deposito_requerido" field.
func (_u *UnidadUpdate) SetDepositoRequerido(v int64) *UnidadUpdate {
	_u.mutation.ResetDepositoRequerido()
	_u.mutation.SetDepositoRequerido(v)
	return _u
}

// SetNillableDepositoRequerido sets the "deposito_requerido" field if the given value is not nil.
func (_u *UnidadUpdate) SetNillableDepositoRequerido(v *int64) *UnidadUpdate {
	if v != nil {
		_u.SetDepositoRequerido(*v)
	}
	return _u
}

// AddDepositoRequerido adds value to the "deposito_requerido" field.
func (_u *UnidadUpdate) AddDepositoRequerido(v int64) *UnidadUpdate {
	_u.mutation.AddDepositoRequerido(v)
	return _u
}

// SetIncluyeAgua sets the "incluye_agua" field.
func (_u *UnidadUpdate) SetIncluyeAgua(v bool) *UnidadUpdate {
	_u.mutation.SetIncluyeAgua(v)
	return _u
}

// SetNillableIncluyeAgua sets the "incluye_agua" field if the given value is not nil.
func (_u *UnidadUpdate) SetNillableIncluyeAgua(v *bool) *UnidadUpdate {
	if v != nil {
		_u.SetIncluyeAgua(*v)
	}
	return _u
}

// SetIncluyeLuz sets the "incluye_luz" field.
func (_u *UnidadUpdate) SetIncluyeLuz(v bool) *UnidadUpdate {
	_u.mutation.SetIncluyeLuz(v)
	return _u
}

// SetNillableIncluyeLuz sets the "incluye_luz" field if the given value is not nil.
func (_u *UnidadUpdate) SetNillableIncluyeLuz(v *bool) *UnidadUpdate {
	if v != nil {
		_u.SetIncluyeLuz(*v)
	}
	return _u
}

// SetIncluyeInternet sets the "incluye_internet" field.
func (_u *UnidadUpdate) SetIncluyeInternet(v bool) *UnidadUpdate {
	_u.mutation.SetIncluyeInternet(v)
	return _u
}

// SetNillableIncluyeInternet sets the "incluye_internet" field if the given value is not nil.
func (_u *UnidadUpdate) SetNillableIncluyeInternet(v *bool) *UnidadUpdate {
	if v != nil {
		_u.SetIncluyeInternet(*v)
	}
	return _u
}

// SetNotas sets the "notas" field.
func (_u *UnidadUpdate) SetNotas(v string) *UnidadUpdate {
	_u.mutation.SetNotas(v)
	return _u
}

// SetNillableNotas sets the "notas" field if the given value is not nil.
func (_u *UnidadUpdate) SetNillableNotas(v *string) *UnidadUpdate {
	if v != nil {
		_u.SetNotas(*v)
	}
	return _u
}

// ClearNotas clears the value of the "notas" field.
func (_u *UnidadUpdate) ClearNotas() *UnidadUpdate {
	_u.mutation.ClearNotas()
	return _u
}

// SetEstado sets the "estado" field.
func (_u *UnidadUpdate) SetEstado(v unidad.Estado) *UnidadUpdate {
	_u.mutation.SetEstado(v)
	return _u
}

// SetNillableEstado sets the "estado" field if the given value is not nil.
func (_u *UnidadUpdate) SetNillableEstado(v *unidad.Estado) *UnidadUpdate {
	if v != nil {
		_u.SetEstado(*v)
	}
	return _u
}

// SetPropiedad sets the "propiedad" edge to the Propiedad entity.
func (_u *UnidadUpdate) SetPropiedad(v *Propiedad) *UnidadUpdate {
	return _u.SetPropiedadID(v.ID)
}

// AddContratoIDs adds the "contratos" edge to the Contrato entity by IDs.
func (_u *UnidadUpdate) AddContratoIDs(ids ...int) *UnidadUpdate {
	_u.mutation.AddContratoIDs(ids...)
	return _u
}

// AddContratos adds the "contratos" edges to the Contrato entity.
func (_u *UnidadUpdate) AddContratos(v ...*Contrato) *UnidadUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContratoIDs(ids...)
}

// AddServicioMedicioneIDs adds the "servicio_mediciones" edge to the ServicioMedicion entity by IDs.
func (_u *UnidadUpdate) AddServicioMedicioneIDs(ids ...int) *UnidadUpdate {
	_u.mutation.AddServicioMedicioneIDs(ids...)
	return _u
}

// AddServicioMediciones adds the "servicio_mediciones" edges to the ServicioMedicion entity.
func (_u *UnidadUpdate) AddServicioMediciones(v ...*ServicioMedicion) *UnidadUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddServicioMedicioneIDs(ids...)
}

// AddGastoIDs adds the "gastos" edge to the Gasto entity by IDs.
func (_u *UnidadUpdate) AddGastoIDs(ids ...int) *UnidadUpdate {
	_u.mutation.AddGastoIDs(ids...)
	return _u
}

// AddGastos adds the "gastos" edges to the Gasto entity.
func (_u *UnidadUpdate) AddGastos(v ...*Gasto) *UnidadUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGastoIDs(ids...)
}

// Mutation returns the UnidadMutation object of the builder.
func (_u *UnidadUpdate) Mutation() *UnidadMutation {
	return _u.mutation
}

// ClearPropiedad clears the "propiedad" edge to the Propiedad entity.
func (_u *UnidadUpdate) ClearPropiedad() *UnidadUpdate {
	_u.mutation.ClearPropiedad()
	return _u
}

// ClearContratos clears all "contratos" edges to the Contrato entity.
func (_u *UnidadUpdate) ClearContratos() *UnidadUpdate {
	_u.mutation.ClearContratos()
	return _u
}

// RemoveContratoIDs removes the "contratos" edge to Contrato entities by IDs.
func (_u *UnidadUpdate) RemoveContratoIDs(ids ...int) *UnidadUpdate {
	_u.mutation.RemoveContratoIDs(ids...)
	return _u
}

// RemoveContratos removes "contratos" edges to Contrato entities.
func (_u *UnidadUpdate) RemoveContratos(v ...*Contrato) *UnidadUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContratoIDs(ids...)
}

// ClearServicioMediciones clears all "servicio_mediciones" edges to the ServicioMedicion entity.
func (_u *UnidadUpdate) ClearServicioMediciones() *UnidadUpdate {
	_u.mutation.ClearServicioMediciones()
	return _u
}

// RemoveServicioMedicioneIDs removes the "servicio_mediciones" edge to ServicioMedicion entities by IDs.
func (_u *UnidadUpdate) RemoveServicioMedicioneIDs(ids ...int) *UnidadUpdate {
	_u.mutation.RemoveServicioMedicioneIDs(ids...)
	return _u
}

// RemoveServicioMediciones removes "servicio_mediciones" edges to ServicioMedicion entities.
func (_u *UnidadUpdate) RemoveServicioMediciones(v ...*ServicioMedicion) *UnidadUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveServicioMedicioneIDs(ids...)
}

// ClearGastos clears all "gastos" edges to the Gasto entity.
func (_u *UnidadUpdate) ClearGastos() *UnidadUpdate {
	_u.mutation.ClearGastos()
	return _u
}

// RemoveGastoIDs removes the "gastos" edge to Gasto entities by IDs.
func (_u *UnidadUpdate) RemoveGastoIDs(ids ...int) *UnidadUpdate {
	_u.mutation.RemoveGastoIDs(ids...)
	return _u
}

// RemoveGastos removes "gastos" edges to Gasto entities.
func (_u *UnidadUpdate) RemoveGastos(v ...*Gasto) *UnidadUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGastoIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UnidadUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UnidadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UnidadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UnidadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UnidadUpdate) defaults() {
	if _, ok := _u.mutation.ActualizadoEn(); !ok {
		v := unidad.UpdateDefaultActualizadoEn()
		_u.mutation.SetActualizadoEn(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UnidadUpdate) check() error {
	if v, ok := _u.mutation.Codigo(); ok {
		if err := unidad.CodigoValidator(v); err != nil {
			return &ValidationError{Name: "codigo", err: fmt.Errorf(`ent: validator failed for field "Unidad.codigo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nombre(); ok {
		if err := unidad.NombreValidator(v); err != nil {
			return &ValidationError{Name: "nombre", err: fmt.Errorf(`ent: validator failed for field "Unidad.nombre": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Tipo(); ok {
		if err := unidad.TipoValidator(v); err != nil {
			return &ValidationError{Name: "tipo", err: fmt.Errorf(`ent: validator failed for field "Unidad.tipo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Dormitorios(); ok {
		if err := unidad.DormitoriosValidator(v); err != nil {
			return &ValidationError{Name: "dormitorios", err: fmt.Errorf(`ent: validator failed for field "Unidad.dormitorios": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Banos(); ok {
		if err := unidad.BanosValidator(v); err != nil {
			return &ValidationError{Name: "banos", err: fmt.Errorf(`ent: validator failed for field "Unidad.banos": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Capacidad(); ok {
		if err := unidad.CapacidadValidator(v); err != nil {
			return &ValidationError{Name: "capacidad", err: fmt.Errorf(`ent: validator failed for field "Unidad.capacidad": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Moneda(); ok {
		if err := unidad.MonedaValidator(v); err != nil {
			return &ValidationError{Name: "moneda", err: fmt.Errorf(`ent: validator failed for field "Unidad.moneda": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Notas(); ok {
		if err := unidad.NotasValidator(v); err != nil {
			return &ValidationError{Name: "notas", err: fmt.Errorf(`ent: validator failed for field "Unidad.notas": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Estado(); ok {
		if err := unidad.EstadoValidator(v); err != nil {
			return &ValidationError{Name: "estado", err: fmt.Errorf(`ent: validator failed for field "Unidad.estado": %w`, err)}
		}
	}
	if _u.mutation.PropiedadCleared() && len(_u.mutation.PropiedadIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Unidad.propiedad"`)
	}
	return nil
}

func (_u *UnidadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(unidad.Table, unidad.Columns, sqlgraph.NewFieldSpec(unidad.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActualizadoEn(); ok {
		_spec.SetField(unidad.FieldActualizadoEn, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Codigo(); ok {
		_spec.SetField(unidad.FieldCodigo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nombre(); ok {
		_spec.SetField(unidad.FieldNombre, field.TypeString, value)
	}
	if _u.mutation.NombreCleared() {
		_spec.ClearField(unidad.FieldNombre, field.TypeString)
	}
	if value, ok := _u.mutation.Tipo(); ok {
		_spec.SetField(unidad.FieldTipo, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NumeroPiso(); ok {
		_spec.SetField(unidad.FieldNumeroPiso, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNumeroPiso(); ok {
		_spec.AddField(unidad.FieldNumeroPiso, field.TypeInt, value)
	}
	if _u.mutation.NumeroPisoCleared() {
		_spec.ClearField(unidad.FieldNumeroPiso, field.TypeInt)
	}
	if value, ok := _u.mutation.Dormitorios(); ok {
		_spec.SetField(unidad.FieldDormitorios, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDormitorios(); ok {
		_spec.AddField(unidad.FieldDormitorios, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Banos(); ok {
		_spec.SetField(unidad.FieldBanos, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBanos(); ok {
		_spec.AddField(unidad.FieldBanos, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AreaM2(); ok {
		_spec.SetField(unidad.FieldAreaM2, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAreaM2(); ok {
		_spec.AddField(unidad.FieldAreaM2, field.TypeFloat64, value)
	}
	if _u.mutation.AreaM2Cleared() {
		_spec.ClearField(unidad.FieldAreaM2, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Capacidad(); ok {
		_spec.SetField(unidad.FieldCapacidad, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapacidad(); ok {
		_spec.AddField(unidad.FieldCapacidad, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Moneda(); ok {
		_spec.SetField(unidad.FieldMoneda, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrecioBase(); ok {
		_spec.SetField(unidad.FieldPrecioBase, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrecioBase(); ok {
		_spec.AddField(unidad.FieldPrecioBase, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DepositoRequerido(); ok {
		_spec.SetField(unidad.FieldDepositoRequerido, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDepositoRequerido(); ok {
		_spec.AddField(unidad.FieldDepositoRequerido, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IncluyeAgua(); ok {
		_spec.SetField(unidad.FieldIncluyeAgua, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IncluyeLuz(); ok {
		_spec.SetField(unidad.FieldIncluyeLuz, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IncluyeInternet(); ok {
		_spec.SetField(unidad.FieldIncluyeInternet, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notas(); ok {
		_spec.SetField(unidad.FieldNotas, field.TypeString, value)
	}
	if _u.mutation.NotasCleared() {
		_spec.ClearField(unidad.FieldNotas, field.TypeString)
	}
	if value, ok := _u.mutation.Estado(); ok {
		_spec.SetField(unidad.FieldEstado, field.TypeEnum, value)
	}
	if _u.mutation.PropiedadCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unidad.PropiedadTable,
			Columns: []string{unidad.PropiedadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propiedad.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PropiedadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unidad.PropiedadTable,
			Columns: []string{unidad.PropiedadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propiedad.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContratosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.ContratosTable,
			Columns: []string{unidad.ContratosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contrato.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContratosIDs(); len(nodes) > 0 && !_u.mutation.ContratosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.ContratosTable,
			Columns: []string{unidad.ContratosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contrato.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContratosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.ContratosTable,
			Columns: []string{unidad.ContratosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contrato.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ServicioMedicionesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.ServicioMedicionesTable,
			Columns: []string{unidad.ServicioMedicionesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviciomedicion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedServicioMedicionesIDs(); len(nodes) > 0 && !_u.mutation.ServicioMedicionesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.ServicioMedicionesTable,
			Columns: []string{unidad.ServicioMedicionesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviciomedicion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServicioMedicionesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.ServicioMedicionesTable,
			Columns: []string{unidad.ServicioMedicionesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviciomedicion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GastosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.GastosTable,
			Columns: []string{unidad.GastosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gasto.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGastosIDs(); len(nodes) > 0 && !_u.mutation.GastosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.GastosTable,
			Columns: []string{unidad.GastosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gasto.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GastosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.GastosTable,
			Columns: []string{unidad.GastosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gasto.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{unidad.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UnidadUpdateOne is the builder for updating a single Unidad entity.
type UnidadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UnidadMutation
}

// SetActualizadoEn sets the "actualizado_en" field.
func (_u *UnidadUpdateOne) SetActualizadoEn(v time.Time) *UnidadUpdateOne {
	_u.mutation.SetActualizadoEn(v)
	return _u
}

// SetPropiedadID sets the "propiedad_id" field.
func (_u *UnidadUpdateOne) SetPropiedadID(v int) *UnidadUpdateOne {
	_u.mutation.SetPropiedadID(v)
	return _u
}

// SetNillablePropiedadID sets the "propiedad_id" field if the given value is not nil.
func (_u *UnidadUpdateOne) SetNillablePropiedadID(v *int) *UnidadUpdateOne {
	if v != nil {
		_u.SetPropiedadID(*v)
	}
	return _u
}

// SetCodigo sets the "codigo" field.
func (_u *UnidadUpdateOne) SetCodigo(v string) *UnidadUpdateOne {
	_u.mutation.SetCodigo(v)
	return _u
}

// SetNillableCodigo sets the "codigo" field if the given value is not nil.
func (_u *UnidadUpdateOne) SetNillableCodigo(v *string) *UnidadUpdateOne {
	if v != nil {
		_u.SetCodigo(*v)
	}
	return _u
}

// SetNombre sets the "nombre" field.
func (_u *UnidadUpdateOne) SetNombre(v string) *UnidadUpdateOne {
	_u.mutation.SetNombre(v)
	return _u
}

// SetNillableNombre sets the "nombre" field if the given value is not nil.
func (_u *UnidadUpdateOne) SetNillableNombre(v *string) *UnidadUpdateOne {
	if v != nil {
		_u.SetNombre(*v)
	}
	return _u
}

// ClearNombre clears the value of the "nombre" field.
func (_u *UnidadUpdateOne) ClearNombre() *UnidadUpdateOne {
	_u.mutation.ClearNombre()
	return _u
}

// SetTipo sets the "tipo" field.
func (_u *UnidadUpdateOne) SetTipo(v unidad.Tipo) *UnidadUpdateOne {
	_u.mutation.SetTipo(v)
	return _u
}

// SetNillableTipo sets the "tipo" field if the given value is not nil.
func (_u *UnidadUpdateOne) SetNillableTipo(v *unidad.Tipo) *UnidadUpdateOne {
	if v != nil {
		_u.SetTipo(*v)
	}
	return _u
}

// SetNumeroPiso sets the "numero_piso" field.
func (_u *UnidadUpdateOne) SetNumeroPiso(v int) *UnidadUpdateOne {
	_u.mutation.ResetNumeroPiso()
	_u.mutation.SetNumeroPiso(v)
	return _u
}

// SetNillableNumeroPiso sets the "numero_piso" field if the given value is not nil.
func (_u *UnidadUpdateOne) SetNillableNumeroPiso(v *int) *UnidadUpdateOne {
	if v != nil {
		_u.SetNumeroPiso(*v)
	}
	return _u
}

// AddNumeroPiso adds value to the "numero_piso" field.
func (_u *UnidadUpdateOne) AddNumeroPiso(v int) *UnidadUpdateOne {
	_u.mutation.AddNumeroPiso(v)
	return _u
}

// ClearNumeroPiso clears the value of the "numero_piso" field.
func (_u *UnidadUpdateOne) ClearNumeroPiso() *UnidadUpdateOne {
	_u.mutation.ClearNumeroPiso()
	return _u
}

// SetDormitorios sets the "dormitorios" field.
func (_u *UnidadUpdateOne) SetDormitorios(v int) *UnidadUpdateOne {
	_u.mutation.ResetDormitorios()
	_u.mutation.SetDormitorios(v)
	return _u
}

// SetNillableDormitorios sets the "dormitorios" field if the given value is not nil.
func (_u *UnidadUpdateOne) SetNillableDormitorios(v *int) *UnidadUpdateOne {
	if v != nil {
		_u.SetDormitorios(*v)
	}
	return _u
}

// AddDormitorios adds value to the "dormitorios" field.
func (_u *UnidadUpdateOne) AddDormitorios(v int) *UnidadUpdateOne {
	_u.mutation.AddDormitorios(v)
	return _u
}

// SetBanos sets the "banos" field.
func (_u *UnidadUpdateOne) SetBanos(v int) *UnidadUpdateOne {
	_u.mutation.ResetBanos()
	_u.mutation.SetBanos(v)
	return _u
}

// SetNillableBanos sets the "banos" field if the given value is not nil.
func (_u *UnidadUpdateOne) SetNillableBanos(v *int) *UnidadUpdateOne {
	if v != nil {
		_u.SetBanos(*v)
	}
	return _u
}

// AddBanos adds value to the "banos" field.
func (_u *UnidadUpdateOne) AddBanos(v int) *UnidadUpdateOne {
	_u.mutation.AddBanos(v)
	return _u
}

// SetAreaM2 sets the "area_m2" field.
func (_u *UnidadUpdateOne) SetAreaM2(v float64) *UnidadUpdateOne {
	_u.mutation.ResetAreaM2()
	_u.mutation.SetAreaM2(v)
	return _u
}

// SetNillableAreaM2 sets the "area_m2" field if the given value is not nil.
func (_u *UnidadUpdateOne) SetNillableAreaM2(v *float64) *UnidadUpdateOne {
	if v != nil {
		_u.SetAreaM2(*v)
	}
	return _u
}

// AddAreaM2 adds value to the "area_m2" field.
func (_u *UnidadUpdateOne) AddAreaM2(v float64) *UnidadUpdateOne {
	_u.mutation.AddAreaM2(v)
	return _u
}

// ClearAreaM2 clears the value of the "area_m2" field.
func (_u *UnidadUpdateOne) ClearAreaM2() *UnidadUpdateOne {
	_u.mutation.ClearAreaM2()
	return _u
}

// SetCapacidad sets the "capacidad" field.
func (_u *UnidadUpdateOne) SetCapacidad(v int) *UnidadUpdateOne {
	_u.mutation.ResetCapacidad()
	_u.mutation.SetCapacidad(v)
	return _u
}

// SetNillableCapacidad sets the "capacidad" field if the given value is not nil.
func (_u *UnidadUpdateOne) SetNillableCapacidad(v *int) *UnidadUpdateOne {
	if v != nil {
		_u.SetCapacidad(*v)
	}
	return _u
}

// AddCapacidad adds value to the "capacidad" field.
func (_u *UnidadUpdateOne) AddCapacidad(v int) *UnidadUpdateOne {
	_u.mutation.AddCapacidad(v)
	return _u
}

// SetMoneda sets the "moneda" field.
func (_u *UnidadUpdateOne) SetMoneda(v string) *UnidadUpdateOne {
	_u.mutation.SetMoneda(v)
	return _u
}

// SetNillableMoneda sets the "moneda" field if the given value is not nil.
func (_u *UnidadUpdateOne) SetNillableMoneda(v *string) *UnidadUpdateOne {
	if v != nil {
		_u.SetMoneda(*v)
	}
	return _u
}

// SetPrecioBase sets the "precio_base" field.
func (_u *UnidadUpdateOne) SetPrecioBase(v int64) *UnidadUpdateOne {
	_u.mutation.ResetPrecioBase()
	_u.mutation.SetPrecioBase(v)
	return _u
}

// SetNillablePrecioBase sets the "precio_base" field if the given value is not nil.
func (_u *UnidadUpdateOne) SetNillablePrecioBase(v *int64) *UnidadUpdateOne {
	if v != nil {
		_u.SetPrecioBase(*v)
	}
	return _u
}

// AddPrecioBase adds value to the "precio_base" field.
func (_u *UnidadUpdateOne) AddPrecioBase(v int64) *UnidadUpdateOne {
	_u.mutation.AddPrecioBase(v)
	return _u
}

// SetDepositoRequerido sets the "deposito_requerido" field.
func (_u *UnidadUpdateOne) SetDepositoRequerido(v int64) *UnidadUpdateOne {
	_u.mutation.ResetDepositoRequerido()
	_u.mutation.SetDepositoRequerido(v)
	return _u
}

// SetNillableDepositoRequerido sets the "deposito_requerido" field if the given value is not nil.
func (_u *UnidadUpdateOne) SetNillableDepositoRequerido(v *int64) *UnidadUpdateOne {
	if v != nil {
		_u.SetDepositoRequerido(*v)
	}
	return _u
}

// AddDepositoRequerido adds value to the "deposito_requerido" field.
func (_u *UnidadUpdateOne) AddDepositoRequerido(v int64) *UnidadUpdateOne {
	_u.mutation.AddDepositoRequerido(v)
	return _u
}

// SetIncluyeAgua sets the "incluye_agua" field.
func (_u *UnidadUpdateOne) SetIncluyeAgua(v bool) *UnidadUpdateOne {
	_u.mutation.SetIncluyeAgua(v)
	return _u
}

// SetNillableIncluyeAgua sets the "incluye_agua" field if the given value is not nil.
func (_u *UnidadUpdateOne) SetNillableIncluyeAgua(v *bool) *UnidadUpdateOne {
	if v != nil {
		_u.SetIncluyeAgua(*v)
	}
	return _u
}

// SetIncluyeLuz sets the "incluye_luz" field.
func (_u *UnidadUpdateOne) SetIncluyeLuz(v bool) *UnidadUpdateOne {
	_u.mutation.SetIncluyeLuz(v)
	return _u
}

// SetNillableIncluyeLuz sets the "incluye_luz" field if the given value is not nil.
func (_u *UnidadUpdateOne) SetNillableIncluyeLuz(v *bool) *UnidadUpdateOne {
	if v != nil {
		_u.SetIncluyeLuz(*v)
	}
	return _u
}

// SetIncluyeInternet sets the "incluye_internet" field.
func (_u *UnidadUpdateOne) SetIncluyeInternet(v bool) *UnidadUpdateOne {
	_u.mutation.SetIncluyeInternet(v)
	return _u
}

// SetNillableIncluyeInternet sets the "incluye_internet" field if the given value is not nil.
func (_u *UnidadUpdateOne) SetNillableIncluyeInternet(v *bool) *UnidadUpdateOne {
	if v != nil {
		_u.SetIncluyeInternet(*v)
	}
	return _u
}

// SetNotas sets the "notas" field.
func (_u *UnidadUpdateOne) SetNotas(v string) *UnidadUpdateOne {
	_u.mutation.SetNotas(v)
	return _u
}

// SetNillableNotas sets the "notas" field if the given value is not nil.
func (_u *UnidadUpdateOne) SetNillableNotas(v *string) *UnidadUpdateOne {
	if v != nil {
		_u.SetNotas(*v)
	}
	return _u
}

// ClearNotas clears the value of the "notas" field.
func (_u *UnidadUpdateOne) ClearNotas() *UnidadUpdateOne {
	_u.mutation.ClearNotas()
	return _u
}

// SetEstado sets the "estado" field.
func (_u *UnidadUpdateOne) SetEstado(v unidad.Estado) *UnidadUpdateOne {
	_u.mutation.SetEstado(v)
	return _u
}

// SetNillableEstado sets the "estado" field if the given value is not nil.
func (_u *UnidadUpdateOne) SetNillableEstado(v *unidad.Estado) *UnidadUpdateOne {
	if v != nil {
		_u.SetEstado(*v)
	}
	return _u
}

// SetPropiedad sets the "propiedad" edge to the Propiedad entity.
func (_u *UnidadUpdateOne) SetPropiedad(v *Propiedad) *UnidadUpdateOne {
	return _u.SetPropiedadID(v.ID)
}

// AddContratoIDs adds the "contratos" edge to the Contrato entity by IDs.
func (_u *UnidadUpdateOne) AddContratoIDs(ids ...int) *UnidadUpdateOne {
	_u.mutation.AddContratoIDs(ids...)
	return _u
}

// AddContratos adds the "contratos" edges to the Contrato entity.
func (_u *UnidadUpdateOne) AddContratos(v ...*Contrato) *UnidadUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContratoIDs(ids...)
}

// AddServicioMedicioneIDs adds the "servicio_mediciones" edge to the ServicioMedicion entity by IDs.
func (_u *UnidadUpdateOne) AddServicioMedicioneIDs(ids ...int) *UnidadUpdateOne {
	_u.mutation.AddServicioMedicioneIDs(ids...)
	return _u
}

// AddServicioMediciones adds the "servicio_mediciones" edges to the ServicioMedicion entity.
func (_u *UnidadUpdateOne) AddServicioMediciones(v ...*ServicioMedicion) *UnidadUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddServicioMedicioneIDs(ids...)
}

// AddGastoIDs adds the "gastos" edge to the Gasto entity by IDs.
func (_u *UnidadUpdateOne) AddGastoIDs(ids ...int) *UnidadUpdateOne {
	_u.mutation.AddGastoIDs(ids...)
	return _u
}

// AddGastos adds the "gastos" edges to the Gasto entity.
func (_u *UnidadUpdateOne) AddGastos(v ...*Gasto) *UnidadUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGastoIDs(ids...)
}

// Mutation returns the UnidadMutation object of the builder.
func (_u *UnidadUpdateOne) Mutation() *UnidadMutation {
	return _u.mutation
}

// ClearPropiedad clears the "propiedad" edge to the Propiedad entity.
func (_u *UnidadUpdateOne) ClearPropiedad() *UnidadUpdateOne {
	_u.mutation.ClearPropiedad()
	return _u
}

// ClearContratos clears all "contratos" edges to the Contrato entity.
func (_u *UnidadUpdateOne) ClearContratos() *UnidadUpdateOne {
	_u.mutation.ClearContratos()
	return _u
}

// RemoveContratoIDs removes the "contratos" edge to Contrato entities by IDs.
func (_u *UnidadUpdateOne) RemoveContratoIDs(ids ...int) *UnidadUpdateOne {
	_u.mutation.RemoveContratoIDs(ids...)
	return _u
}

// RemoveContratos removes "contratos" edges to Contrato entities.
func (_u *UnidadUpdateOne) RemoveContratos(v ...*Contrato) *UnidadUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContratoIDs(ids...)
}

// ClearServicioMediciones clears all "servicio_mediciones" edges to the ServicioMedicion entity.
func (_u *UnidadUpdateOne) ClearServicioMediciones() *UnidadUpdateOne {
	_u.mutation.ClearServicioMediciones()
	return _u
}

// RemoveServicioMedicioneIDs removes the "servicio_mediciones" edge to ServicioMedicion entities by IDs.
func (_u *UnidadUpdateOne) RemoveServicioMedicioneIDs(ids ...int) *UnidadUpdateOne {
	_u.mutation.RemoveServicioMedicioneIDs(ids...)
	return _u
}

// RemoveServicioMediciones removes "servicio_mediciones" edges to ServicioMedicion entities.
func (_u *UnidadUpdateOne) RemoveServicioMediciones(v ...*ServicioMedicion) *UnidadUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveServicioMedicioneIDs(ids...)
}

// ClearGastos clears all "gastos" edges to the Gasto entity.
func (_u *UnidadUpdateOne) ClearGastos() *UnidadUpdateOne {
	_u.mutation.ClearGastos()
	return _u
}

// RemoveGastoIDs removes the "gastos" edge to Gasto entities by IDs.
func (_u *UnidadUpdateOne) RemoveGastoIDs(ids ...int) *UnidadUpdateOne {
	_u.mutation.RemoveGastoIDs(ids...)
	return _u
}

// RemoveGastos removes "gastos" edges to Gasto entities.
func (_u *UnidadUpdateOne) RemoveGastos(v ...*Gasto) *UnidadUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGastoIDs(ids...)
}

// Where appends a list predicates to the UnidadUpdate builder.
func (_u *UnidadUpdateOne) Where(ps ...predicate.Unidad) *UnidadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UnidadUpdateOne) Select(field string, fields ...string) *UnidadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Unidad entity.
func (_u *UnidadUpdateOne) Save(ctx context.Context) (*Unidad, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UnidadUpdateOne) SaveX(ctx context.Context) *Unidad {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UnidadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UnidadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UnidadUpdateOne) defaults() {
	if _, ok := _u.mutation.ActualizadoEn(); !ok {
		v := unidad.UpdateDefaultActualizadoEn()
		_u.mutation.SetActualizadoEn(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UnidadUpdateOne) check() error {
	if v, ok := _u.mutation.Codigo(); ok {
		if err := unidad.CodigoValidator(v); err != nil {
			return &ValidationError{Name: "codigo", err: fmt.Errorf(`ent: validator failed for field "Unidad.codigo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nombre(); ok {
		if err := unidad.NombreValidator(v); err != nil {
			return &ValidationError{Name: "nombre", err: fmt.Errorf(`ent: validator failed for field "Unidad.nombre": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Tipo(); ok {
		if err := unidad.TipoValidator(v); err != nil {
			return &ValidationError{Name: "tipo", err: fmt.Errorf(`ent: validator failed for field "Unidad.tipo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Dormitorios(); ok {
		if err := unidad.DormitoriosValidator(v); err != nil {
			return &ValidationError{Name: "dormitorios", err: fmt.Errorf(`ent: validator failed for field "Unidad.dormitorios": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Banos(); ok {
		if err := unidad.BanosValidator(v); err != nil {
			return &ValidationError{Name: "banos", err: fmt.Errorf(`ent: validator failed for field "Unidad.banos": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Capacidad(); ok {
		if err := unidad.CapacidadValidator(v); err != nil {
			return &ValidationError{Name: "capacidad", err: fmt.Errorf(`ent: validator failed for field "Unidad.capacidad": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Moneda(); ok {
		if err := unidad.MonedaValidator(v); err != nil {
			return &ValidationError{Name: "moneda", err: fmt.Errorf(`ent: validator failed for field "Unidad.moneda": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Notas(); ok {
		if err := unidad.NotasValidator(v); err != nil {
			return &ValidationError{Name: "notas", err: fmt.Errorf(`ent: validator failed for field "Unidad.notas": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Estado(); ok {
		if err := unidad.EstadoValidator(v); err != nil {
			return &ValidationError{Name: "estado", err: fmt.Errorf(`ent: validator failed for field "Unidad.estado": %w`, err)}
		}
	}
	if _u.mutation.PropiedadCleared() && len(_u.mutation.PropiedadIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Unidad.propiedad"`)
	}
	return nil
}

func (_u *UnidadUpdateOne) sqlSave(ctx context.Context) (_node *Unidad, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(unidad.Table, unidad.Columns, sqlgraph.NewFieldSpec(unidad.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Unidad.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, unidad.FieldID)
		for _, f := range fields {
			if !unidad.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != unidad.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActualizadoEn(); ok {
		_spec.SetField(unidad.FieldActualizadoEn, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Codigo(); ok {
		_spec.SetField(unidad.FieldCodigo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nombre(); ok {
		_spec.SetField(unidad.FieldNombre, field.TypeString, value)
	}
	if _u.mutation.NombreCleared() {
		_spec.ClearField(unidad.FieldNombre, field.TypeString)
	}
	if value, ok := _u.mutation.Tipo(); ok {
		_spec.SetField(unidad.FieldTipo, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NumeroPiso(); ok {
		_spec.SetField(unidad.FieldNumeroPiso, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNumeroPiso(); ok {
		_spec.AddField(unidad.FieldNumeroPiso, field.TypeInt, value)
	}
	if _u.mutation.NumeroPisoCleared() {
		_spec.ClearField(unidad.FieldNumeroPiso, field.TypeInt)
	}
	if value, ok := _u.mutation.Dormitorios(); ok {
		_spec.SetField(unidad.FieldDormitorios, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDormitorios(); ok {
		_spec.AddField(unidad.FieldDormitorios, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Banos(); ok {
		_spec.SetField(unidad.FieldBanos, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBanos(); ok {
		_spec.AddField(unidad.FieldBanos, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AreaM2(); ok {
		_spec.SetField(unidad.FieldAreaM2, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAreaM2(); ok {
		_spec.AddField(unidad.FieldAreaM2, field.TypeFloat64, value)
	}
	if _u.mutation.AreaM2Cleared() {
		_spec.ClearField(unidad.FieldAreaM2, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Capacidad(); ok {
		_spec.SetField(unidad.FieldCapacidad, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapacidad(); ok {
		_spec.AddField(unidad.FieldCapacidad, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Moneda(); ok {
		_spec.SetField(unidad.FieldMoneda, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrecioBase(); ok {
		_spec.SetField(unidad.FieldPrecioBase, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrecioBase(); ok {
		_spec.AddField(unidad.FieldPrecioBase, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DepositoRequerido(); ok {
		_spec.SetField(unidad.FieldDepositoRequerido, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDepositoRequerido(); ok {
		_spec.AddField(unidad.FieldDepositoRequerido, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IncluyeAgua(); ok {
		_spec.SetField(unidad.FieldIncluyeAgua, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IncluyeLuz(); ok {
		_spec.SetField(unidad.FieldIncluyeLuz, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IncluyeInternet(); ok {
		_spec.SetField(unidad.FieldIncluyeInternet, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notas(); ok {
		_spec.SetField(unidad.FieldNotas, field.TypeString, value)
	}
	if _u.mutation.NotasCleared() {
		_spec.ClearField(unidad.FieldNotas, field.TypeString)
	}
	if value, ok := _u.mutation.Estado(); ok {
		_spec.SetField(unidad.FieldEstado, field.TypeEnum, value)
	}
	if _u.mutation.PropiedadCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unidad.PropiedadTable,
			Columns: []string{unidad.PropiedadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propiedad.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PropiedadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unidad.PropiedadTable,
			Columns: []string{unidad.PropiedadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propiedad.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContratosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.ContratosTable,
			Columns: []string{unidad.ContratosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contrato.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContratosIDs(); len(nodes) > 0 && !_u.mutation.ContratosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.ContratosTable,
			Columns: []string{unidad.ContratosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contrato.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContratosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.ContratosTable,
			Columns: []string{unidad.ContratosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contrato.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ServicioMedicionesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.ServicioMedicionesTable,
			Columns: []string{unidad.ServicioMedicionesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviciomedicion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedServicioMedicionesIDs(); len(nodes) > 0 && !_u.mutation.ServicioMedicionesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.ServicioMedicionesTable,
			Columns: []string{unidad.ServicioMedicionesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviciomedicion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServicioMedicionesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.ServicioMedicionesTable,
			Columns: []string{unidad.ServicioMedicionesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviciomedicion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GastosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.GastosTable,
			Columns: []string{unidad.GastosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gasto.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGastosIDs(); len(nodes) > 0 && !_u.mutation.GastosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.GastosTable,
			Columns: []string{unidad.GastosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gasto.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GastosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unidad.GastosTable,
			Columns: []string{unidad.GastosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gasto.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Unidad{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{unidad.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
