// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rentals-go/ent/empresausuario"
	"rentals-go/ent/predicate"
	"rentals-go/ent/usuario"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UsuarioUpdate is the builder for updating Usuario entities.
type UsuarioUpdate struct {
	config
	hooks    []Hook
	mutation *UsuarioMutation
}

// Where appends a list predicates to the UsuarioUpdate builder.
func (_u *UsuarioUpdate) Where(ps ...predicate.Usuario) *UsuarioUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetActualizadoEn sets the "actualizado_en" field.
func (_u *UsuarioUpdate) SetActualizadoEn(v time.Time) *UsuarioUpdate {
	_u.mutation.SetActualizadoEn(v)
	return _u
}

// SetNombres sets the "nombres" field.
func (_u *UsuarioUpdate) SetNombres(v string) *UsuarioUpdate {
	_u.mutation.SetNombres(v)
	return _u
}

// SetNillableNombres sets the "nombres" field if the given value is not nil.
func (_u *UsuarioUpdate) SetNillableNombres(v *string) *UsuarioUpdate {
	if v != nil {
		_u.SetNombres(*v)
	}
	return _u
}

// SetApellidos sets the "apellidos" field.
func (_u *UsuarioUpdate) SetApellidos(v string) *UsuarioUpdate {
	_u.mutation.SetApellidos(v)
	return _u
}

// SetNillableApellidos sets the "apellidos" field if the given value is not nil.
func (_u *UsuarioUpdate) SetNillableApellidos(v *string) *UsuarioUpdate {
	if v != nil {
		_u.SetApellidos(*v)
	}
	return _u
}

// ClearApellidos clears the value of the "apellidos" field.
func (_u *UsuarioUpdate) ClearApellidos() *UsuarioUpdate {
	_u.mutation.ClearApellidos()
	return _u
}

// SetCorreo sets the "correo" field.
func (_u *UsuarioUpdate) SetCorreo(v string) *UsuarioUpdate {
	_u.mutation.SetCorreo(v)
	return _u
}

// SetNillableCorreo sets the "correo" field if the given value is not nil.
func (_u *UsuarioUpdate) SetNillableCorreo(v *string) *UsuarioUpdate {
	if v != nil {
		_u.SetCorreo(*v)
	}
	return _u
}

// SetTelefono sets the "telefono" field.
func (_u *UsuarioUpdate) SetTelefono(v string) *UsuarioUpdate {
	_u.mutation.SetTelefono(v)
	return _u
}

// SetNillableTelefono sets the "telefono" field if the given value is not nil.
func (_u *UsuarioUpdate) SetNillableTelefono(v *string) *UsuarioUpdate {
	if v != nil {
		_u.SetTelefono(*v)
	}
	return _u
}

// ClearTelefono clears the value of the "telefono" field.
func (_u *UsuarioUpdate) ClearTelefono() *UsuarioUpdate {
	_u.mutation.ClearTelefono()
	return _u
}

// SetHashContrasena sets the "hash_contrasena" field.
func (_u *UsuarioUpdate) SetHashContrasena(v string) *UsuarioUpdate {
	_u.mutation.SetHashContrasena(v)
	return _u
}

// SetNillableHashContrasena sets the "hash_contrasena" field if the given value is not nil.
func (_u *UsuarioUpdate) SetNillableHashContrasena(v *string) *UsuarioUpdate {
	if v != nil {
		_u.SetHashContrasena(*v)
	}
	return _u
}

// SetEstado sets the "estado" field.
func (_u *UsuarioUpdate) SetEstado(v usuario.Estado) *UsuarioUpdate {
	_u.mutation.SetEstado(v)
	return _u
}

// SetNillableEstado sets the "estado" field if the given value is not nil.
func (_u *UsuarioUpdate) SetNillableEstado(v *usuario.Estado) *UsuarioUpdate {
	if v != nil {
		_u.SetEstado(*v)
	}
	return _u
}

// SetUltimoAcceso sets the "ultimo_acceso" field.
func (_u *UsuarioUpdate) SetUltimoAcceso(v time.Time) *UsuarioUpdate {
	_u.mutation.SetUltimoAcceso(v)
	return _u
}

// SetNillableUltimoAcceso sets the "ultimo_acceso" field if the given value is not nil.
func (_u *UsuarioUpdate) SetNillableUltimoAcceso(v *time.Time) *UsuarioUpdate {
	if v != nil {
		_u.SetUltimoAcceso(*v)
	}
	return _u
}

// ClearUltimoAcceso clears the value of the "ultimo_acceso" field.
func (_u *UsuarioUpdate) ClearUltimoAcceso() *UsuarioUpdate {
	_u.mutation.ClearUltimoAcceso()
	return _u
}

// AddEmpresasUsuarioIDs adds the "empresas_usuario" edge to the EmpresaUsuario entity by IDs.
func (_u *UsuarioUpdate) AddEmpresasUsuarioIDs(ids ...int) *UsuarioUpdate {
	_u.mutation.AddEmpresasUsuarioIDs(ids...)
	return _u
}

// AddEmpresasUsuario adds the "empresas_usuario" edges to the EmpresaUsuario entity.
func (_u *UsuarioUpdate) AddEmpresasUsuario(v ...*EmpresaUsuario) *UsuarioUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEmpresasUsuarioIDs(ids...)
}

// Mutation returns the UsuarioMutation object of the builder.
func (_u *UsuarioUpdate) Mutation() *UsuarioMutation {
	return _u.mutation
}

// ClearEmpresasUsuario clears all "empresas_usuario" edges to the EmpresaUsuario entity.
func (_u *UsuarioUpdate) ClearEmpresasUsuario() *UsuarioUpdate {
	_u.mutation.ClearEmpresasUsuario()
	return _u
}

// RemoveEmpresasUsuarioIDs removes the "empresas_usuario" edge to EmpresaUsuario entities by IDs.
func (_u *UsuarioUpdate) RemoveEmpresasUsuarioIDs(ids ...int) *UsuarioUpdate {
	_u.mutation.RemoveEmpresasUsuarioIDs(ids...)
	return _u
}

// RemoveEmpresasUsuario removes "empresas_usuario" edges to EmpresaUsuario entities.
func (_u *UsuarioUpdate) RemoveEmpresasUsuario(v ...*EmpresaUsuario) *UsuarioUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEmpresasUsuarioIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsuarioUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsuarioUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsuarioUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsuarioUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsuarioUpdate) defaults() {
	if _, ok := _u.mutation.ActualizadoEn(); !ok {
		v := usuario.UpdateDefaultActualizadoEn()
		_u.mutation.SetActualizadoEn(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsuarioUpdate) check() error {
	if v, ok := _u.mutation.Nombres(); ok {
		if err := usuario.NombresValidator(v); err != nil {
			return &ValidationError{Name: "nombres", err: fmt.Errorf(`ent: validator failed for field "Usuario.nombres": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Apellidos(); ok {
		if err := usuario.ApellidosValidator(v); err != nil {
			return &ValidationError{Name: "apellidos", err: fmt.Errorf(`ent: validator failed for field "Usuario.apellidos": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Correo(); ok {
		if err := usuario.CorreoValidator(v); err != nil {
			return &ValidationError{Name: "correo", err: fmt.Errorf(`ent: validator failed for field "Usuario.correo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Telefono(); ok {
		if err := usuario.TelefonoValidator(v); err != nil {
			return &ValidationError{Name: "telefono", err: fmt.Errorf(`ent: validator failed for field "Usuario.telefono": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HashContrasena(); ok {
		if err := usuario.HashContrasenaValidator(v); err != nil {
			return &ValidationError{Name: "hash_contrasena", err: fmt.Errorf(`ent: validator failed for field "Usuario.hash_contrasena": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Estado(); ok {
		if err := usuario.EstadoValidator(v); err != nil {
			return &ValidationError{Name: "estado", err: fmt.Errorf(`ent: validator failed for field "Usuario.estado": %w`, err)}
		}
	}
	return nil
}

func (_u *UsuarioUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usuario.Table, usuario.Columns, sqlgraph.NewFieldSpec(usuario.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActualizadoEn(); ok {
		_spec.SetField(usuario.FieldActualizadoEn, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Nombres(); ok {
		_spec.SetField(usuario.FieldNombres, field.TypeString, value)
	}
	if value, ok := _u.mutation.Apellidos(); ok {
		_spec.SetField(usuario.FieldApellidos, field.TypeString, value)
	}
	if _u.mutation.ApellidosCleared() {
		_spec.ClearField(usuario.FieldApellidos, field.TypeString)
	}
	if value, ok := _u.mutation.Correo(); ok {
		_spec.SetField(usuario.FieldCorreo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Telefono(); ok {
		_spec.SetField(usuario.FieldTelefono, field.TypeString, value)
	}
	if _u.mutation.TelefonoCleared() {
		_spec.ClearField(usuario.FieldTelefono, field.TypeString)
	}
	if value, ok := _u.mutation.HashContrasena(); ok {
		_spec.SetField(usuario.FieldHashContrasena, field.TypeString, value)
	}
	if value, ok := _u.mutation.Estado(); ok {
		_spec.SetField(usuario.FieldEstado, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UltimoAcceso(); ok {
		_spec.SetField(usuario.FieldUltimoAcceso, field.TypeTime, value)
	}
	if _u.mutation.UltimoAccesoCleared() {
		_spec.ClearField(usuario.FieldUltimoAcceso, field.TypeTime)
	}
	if _u.mutation.EmpresasUsuarioCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usuario.EmpresasUsuarioTable,
			Columns: []string{usuario.EmpresasUsuarioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresausuario.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEmpresasUsuarioIDs(); len(nodes) > 0 && !_u.mutation.EmpresasUsuarioCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usuario.EmpresasUsuarioTable,
			Columns: []string{usuario.EmpresasUsuarioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresausuario.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmpresasUsuarioIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usuario.EmpresasUsuarioTable,
			Columns: []string{usuario.EmpresasUsuarioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresausuario.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usuario.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsuarioUpdateOne is the builder for updating a single Usuario entity.
type UsuarioUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsuarioMutation
}

// SetActualizadoEn sets the "actualizado_en" field.
func (_u *UsuarioUpdateOne) SetActualizadoEn(v time.Time) *UsuarioUpdateOne {
	_u.mutation.SetActualizadoEn(v)
	return _u
}

// SetNombres sets the "nombres" field.
func (_u *UsuarioUpdateOne) SetNombres(v string) *UsuarioUpdateOne {
	_u.mutation.SetNombres(v)
	return _u
}

// SetNillableNombres sets the "nombres" field if the given value is not nil.
func (_u *UsuarioUpdateOne) SetNillableNombres(v *string) *UsuarioUpdateOne {
	if v != nil {
		_u.SetNombres(*v)
	}
	return _u
}

// SetApellidos sets the "apellidos" field.
func (_u *UsuarioUpdateOne) SetApellidos(v string) *UsuarioUpdateOne {
	_u.mutation.SetApellidos(v)
	return _u
}

// SetNillableApellidos sets the "apellidos" field if the given value is not nil.
func (_u *UsuarioUpdateOne) SetNillableApellidos(v *string) *UsuarioUpdateOne {
	if v != nil {
		_u.SetApellidos(*v)
	}
	return _u
}

// ClearApellidos clears the value of the "apellidos" field.
func (_u *UsuarioUpdateOne) ClearApellidos() *UsuarioUpdateOne {
	_u.mutation.ClearApellidos()
	return _u
}

// SetCorreo sets the "correo" field.
func (_u *UsuarioUpdateOne) SetCorreo(v string) *UsuarioUpdateOne {
	_u.mutation.SetCorreo(v)
	return _u
}

// SetNillableCorreo sets the "correo" field if the given value is not nil.
func (_u *UsuarioUpdateOne) SetNillableCorreo(v *string) *UsuarioUpdateOne {
	if v != nil {
		_u.SetCorreo(*v)
	}
	return _u
}

// SetTelefono sets the "telefono" field.
func (_u *UsuarioUpdateOne) SetTelefono(v string) *UsuarioUpdateOne {
	_u.mutation.SetTelefono(v)
	return _u
}

// SetNillableTelefono sets the "telefono" field if the given value is not nil.
func (_u *UsuarioUpdateOne) SetNillableTelefono(v *string) *UsuarioUpdateOne {
	if v != nil {
		_u.SetTelefono(*v)
	}
	return _u
}

// ClearTelefono clears the value of the "telefono" field.
func (_u *UsuarioUpdateOne) ClearTelefono() *UsuarioUpdateOne {
	_u.mutation.ClearTelefono()
	return _u
}

// SetHashContrasena sets the "hash_contrasena" field.
func (_u *UsuarioUpdateOne) SetHashContrasena(v string) *UsuarioUpdateOne {
	_u.mutation.SetHashContrasena(v)
	return _u
}

// SetNillableHashContrasena sets the "hash_contrasena" field if the given value is not nil.
func (_u *UsuarioUpdateOne) SetNillableHashContrasena(v *string) *UsuarioUpdateOne {
	if v != nil {
		_u.SetHashContrasena(*v)
	}
	return _u
}

// SetEstado sets the "estado" field.
func (_u *UsuarioUpdateOne) SetEstado(v usuario.Estado) *UsuarioUpdateOne {
	_u.mutation.SetEstado(v)
	return _u
}

// SetNillableEstado sets the "estado" field if the given value is not nil.
func (_u *UsuarioUpdateOne) SetNillableEstado(v *usuario.Estado) *UsuarioUpdateOne {
	if v != nil {
		_u.SetEstado(*v)
	}
	return _u
}

// SetUltimoAcceso sets the "ultimo_acceso" field.
func (_u *UsuarioUpdateOne) SetUltimoAcceso(v time.Time) *UsuarioUpdateOne {
	_u.mutation.SetUltimoAcceso(v)
	return _u
}

// SetNillableUltimoAcceso sets the "ultimo_acceso" field if the given value is not nil.
func (_u *UsuarioUpdateOne) SetNillableUltimoAcceso(v *time.Time) *UsuarioUpdateOne {
	if v != nil {
		_u.SetUltimoAcceso(*v)
	}
	return _u
}

// ClearUltimoAcceso clears the value of the "ultimo_acceso" field.
func (_u *UsuarioUpdateOne) ClearUltimoAcceso() *UsuarioUpdateOne {
	_u.mutation.ClearUltimoAcceso()
	return _u
}

// AddEmpresasUsuarioIDs adds the "empresas_usuario" edge to the EmpresaUsuario entity by IDs.
func (_u *UsuarioUpdateOne) AddEmpresasUsuarioIDs(ids ...int) *UsuarioUpdateOne {
	_u.mutation.AddEmpresasUsuarioIDs(ids...)
	return _u
}

// AddEmpresasUsuario adds the "empresas_usuario" edges to the EmpresaUsuario entity.
func (_u *UsuarioUpdateOne) AddEmpresasUsuario(v ...*EmpresaUsuario) *UsuarioUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEmpresasUsuarioIDs(ids...)
}

// Mutation returns the UsuarioMutation object of the builder.
func (_u *UsuarioUpdateOne) Mutation() *UsuarioMutation {
	return _u.mutation
}

// ClearEmpresasUsuario clears all "empresas_usuario" edges to the EmpresaUsuario entity.
func (_u *UsuarioUpdateOne) ClearEmpresasUsuario() *UsuarioUpdateOne {
	_u.mutation.ClearEmpresasUsuario()
	return _u
}

// RemoveEmpresasUsuarioIDs removes the "empresas_usuario" edge to EmpresaUsuario entities by IDs.
func (_u *UsuarioUpdateOne) RemoveEmpresasUsuarioIDs(ids ...int) *UsuarioUpdateOne {
	_u.mutation.RemoveEmpresasUsuarioIDs(ids...)
	return _u
}

// RemoveEmpresasUsuario removes "empresas_usuario" edges to EmpresaUsuario entities.
func (_u *UsuarioUpdateOne) RemoveEmpresasUsuario(v ...*EmpresaUsuario) *UsuarioUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEmpresasUsuarioIDs(ids...)
}

// Where appends a list predicates to the UsuarioUpdate builder.
func (_u *UsuarioUpdateOne) Where(ps ...predicate.Usuario) *UsuarioUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsuarioUpdateOne) Select(field string, fields ...string) *UsuarioUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Usuario entity.
func (_u *UsuarioUpdateOne) Save(ctx context.Context) (*Usuario, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsuarioUpdateOne) SaveX(ctx context.Context) *Usuario {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsuarioUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsuarioUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsuarioUpdateOne) defaults() {
	if _, ok := _u.mutation.ActualizadoEn(); !ok {
		v := usuario.UpdateDefaultActualizadoEn()
		_u.mutation.SetActualizadoEn(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsuarioUpdateOne) check() error {
	if v, ok := _u.mutation.Nombres(); ok {
		if err := usuario.NombresValidator(v); err != nil {
			return &ValidationError{Name: "nombres", err: fmt.Errorf(`ent: validator failed for field "Usuario.nombres": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Apellidos(); ok {
		if err := usuario.ApellidosValidator(v); err != nil {
			return &ValidationError{Name: "apellidos", err: fmt.Errorf(`ent: validator failed for field "Usuario.apellidos": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Correo(); ok {
		if err := usuario.CorreoValidator(v); err != nil {
			return &ValidationError{Name: "correo", err: fmt.Errorf(`ent: validator failed for field "Usuario.correo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Telefono(); ok {
		if err := usuario.TelefonoValidator(v); err != nil {
			return &ValidationError{Name: "telefono", err: fmt.Errorf(`ent: validator failed for field "Usuario.telefono": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HashContrasena(); ok {
		if err := usuario.HashContrasenaValidator(v); err != nil {
			return &ValidationError{Name: "hash_contrasena", err: fmt.Errorf(`ent: validator failed for field "Usuario.hash_contrasena": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Estado(); ok {
		if err := usuario.EstadoValidator(v); err != nil {
			return &ValidationError{Name: "estado", err: fmt.Errorf(`ent: validator failed for field "Usuario.estado": %w`, err)}
		}
	}
	return nil
}

func (_u *UsuarioUpdateOne) sqlSave(ctx context.Context) (_node *Usuario, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usuario.Table, usuario.Columns, sqlgraph.NewFieldSpec(usuario.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Usuario.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usuario.FieldID)
		for _, f := range fields {
			if !usuario.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usuario.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActualizadoEn(); ok {
		_spec.SetField(usuario.FieldActualizadoEn, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Nombres(); ok {
		_spec.SetField(usuario.FieldNombres, field.TypeString, value)
	}
	if value, ok := _u.mutation.Apellidos(); ok {
		_spec.SetField(usuario.FieldApellidos, field.TypeString, value)
	}
	if _u.mutation.ApellidosCleared() {
		_spec.ClearField(usuario.FieldApellidos, field.TypeString)
	}
	if value, ok := _u.mutation.Correo(); ok {
		_spec.SetField(usuario.FieldCorreo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Telefono(); ok {
		_spec.SetField(usuario.FieldTelefono, field.TypeString, value)
	}
	if _u.mutation.TelefonoCleared() {
		_spec.ClearField(usuario.FieldTelefono, field.TypeString)
	}
	if value, ok := _u.mutation.HashContrasena(); ok {
		_spec.SetField(usuario.FieldHashContrasena, field.TypeString, value)
	}
	if value, ok := _u.mutation.Estado(); ok {
		_spec.SetField(usuario.FieldEstado, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UltimoAcceso(); ok {
		_spec.SetField(usuario.FieldUltimoAcceso, field.TypeTime, value)
	}
	if _u.mutation.UltimoAccesoCleared() {
		_spec.ClearField(usuario.FieldUltimoAcceso, field.TypeTime)
	}
	if _u.mutation.EmpresasUsuarioCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usuario.EmpresasUsuarioTable,
			Columns: []string{usuario.EmpresasUsuarioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresausuario.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEmpresasUsuarioIDs(); len(nodes) > 0 && !_u.mutation.EmpresasUsuarioCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usuario.EmpresasUsuarioTable,
			Columns: []string{usuario.EmpresasUsuarioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresausuario.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmpresasUsuarioIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usuario.EmpresasUsuarioTable,
			Columns: []string{usuario.EmpresasUsuarioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresausuario.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Usuario{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usuario.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
