// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rentals-go/ent/empresausuario"
	"rentals-go/ent/usuario"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UsuarioCreate is the builder for creating a Usuario entity.
type UsuarioCreate struct {
	config
	mutation *UsuarioMutation
	hooks    []Hook
}

// SetCreadoEn sets the "creado_en" field.
func (_c *UsuarioCreate) SetCreadoEn(v time.Time) *UsuarioCreate {
	_c.mutation.SetCreadoEn(v)
	return _c
}

// SetNillableCreadoEn sets the "creado_en" field if the given value is not nil.
func (_c *UsuarioCreate) SetNillableCreadoEn(v *time.Time) *UsuarioCreate {
	if v != nil {
		_c.SetCreadoEn(*v)
	}
	return _c
}

// SetActualizadoEn sets the "actualizado_en" field.
func (_c *UsuarioCreate) SetActualizadoEn(v time.Time) *UsuarioCreate {
	_c.mutation.SetActualizadoEn(v)
	return _c
}

// SetNillableActualizadoEn sets the "actualizado_en" field if the given value is not nil.
func (_c *UsuarioCreate) SetNillableActualizadoEn(v *time.Time) *UsuarioCreate {
	if v != nil {
		_c.SetActualizadoEn(*v)
	}
	return _c
}

// SetUsuario sets the "usuario" field.
func (_c *UsuarioCreate) SetUsuario(v string) *UsuarioCreate {
	_c.mutation.SetUsuario(v)
	return _c
}

// SetHashContrasena sets the "hash_contrasena" field.
func (_c *UsuarioCreate) SetHashContrasena(v string) *UsuarioCreate {
	_c.mutation.SetHashContrasena(v)
	return _c
}

// SetEstado sets the "estado" field.
func (_c *UsuarioCreate) SetEstado(v usuario.Estado) *UsuarioCreate {
	_c.mutation.SetEstado(v)
	return _c
}

// SetNillableEstado sets the "estado" field if the given value is not nil.
func (_c *UsuarioCreate) SetNillableEstado(v *usuario.Estado) *UsuarioCreate {
	if v != nil {
		_c.SetEstado(*v)
	}
	return _c
}

// SetUltimoAcceso sets the "ultimo_acceso" field.
func (_c *UsuarioCreate) SetUltimoAcceso(v time.Time) *UsuarioCreate {
	_c.mutation.SetUltimoAcceso(v)
	return _c
}

// SetNillableUltimoAcceso sets the "ultimo_acceso" field if the given value is not nil.
func (_c *UsuarioCreate) SetNillableUltimoAcceso(v *time.Time) *UsuarioCreate {
	if v != nil {
		_c.SetUltimoAcceso(*v)
	}
	return _c
}

// AddEmpresasUsuarioIDs adds the "empresas_usuario" edge to the EmpresaUsuario entity by IDs.
func (_c *UsuarioCreate) AddEmpresasUsuarioIDs(ids ...int) *UsuarioCreate {
	_c.mutation.AddEmpresasUsuarioIDs(ids...)
	return _c
}

// AddEmpresasUsuario adds the "empresas_usuario" edges to the EmpresaUsuario entity.
func (_c *UsuarioCreate) AddEmpresasUsuario(v ...*EmpresaUsuario) *UsuarioCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEmpresasUsuarioIDs(ids...)
}

// Mutation returns the UsuarioMutation object of the builder.
func (_c *UsuarioCreate) Mutation() *UsuarioMutation {
	return _c.mutation
}

// Save creates the Usuario in the database.
func (_c *UsuarioCreate) Save(ctx context.Context) (*Usuario, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsuarioCreate) SaveX(ctx context.Context) *Usuario {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsuarioCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsuarioCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UsuarioCreate) defaults() {
	if _, ok := _c.mutation.CreadoEn(); !ok {
		v := usuario.DefaultCreadoEn()
		_c.mutation.SetCreadoEn(v)
	}
	if _, ok := _c.mutation.ActualizadoEn(); !ok {
		v := usuario.DefaultActualizadoEn()
		_c.mutation.SetActualizadoEn(v)
	}
	if _, ok := _c.mutation.Estado(); !ok {
		v := usuario.DefaultEstado
		_c.mutation.SetEstado(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsuarioCreate) check() error {
	if _, ok := _c.mutation.CreadoEn(); !ok {
		return &ValidationError{Name: "creado_en", err: errors.New(`ent: missing required field "Usuario.creado_en"`)}
	}
	if _, ok := _c.mutation.ActualizadoEn(); !ok {
		return &ValidationError{Name: "actualizado_en", err: errors.New(`ent: missing required field "Usuario.actualizado_en"`)}
	}
	if _, ok := _c.mutation.Usuario(); !ok {
		return &ValidationError{Name: "usuario", err: errors.New(`ent: missing required field "Usuario.usuario"`)}
	}
	if v, ok := _c.mutation.Usuario(); ok {
		if err := usuario.UsuarioValidator(v); err != nil {
			return &ValidationError{Name: "usuario", err: fmt.Errorf(`ent: validator failed for field "Usuario.usuario": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HashContrasena(); !ok {
		return &ValidationError{Name: "hash_contrasena", err: errors.New(`ent: missing required field "Usuario.hash_contrasena"`)}
	}
	if v, ok := _c.mutation.HashContrasena(); ok {
		if err := usuario.HashContrasenaValidator(v); err != nil {
			return &ValidationError{Name: "hash_contrasena", err: fmt.Errorf(`ent: validator failed for field "Usuario.hash_contrasena": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Estado(); !ok {
		return &ValidationError{Name: "estado", err: errors.New(`ent: missing required field "Usuario.estado"`)}
	}
	if v, ok := _c.mutation.Estado(); ok {
		if err := usuario.EstadoValidator(v); err != nil {
			return &ValidationError{Name: "estado", err: fmt.Errorf(`ent: validator failed for field "Usuario.estado": %w`, err)}
		}
	}
	return nil
}

func (_c *UsuarioCreate) sqlSave(ctx context.Context) (*Usuario, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsuarioCreate) createSpec() (*Usuario, *sqlgraph.CreateSpec) {
	var (
		_node = &Usuario{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usuario.Table, sqlgraph.NewFieldSpec(usuario.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreadoEn(); ok {
		_spec.SetField(usuario.FieldCreadoEn, field.TypeTime, value)
		_node.CreadoEn = value
	}
	if value, ok := _c.mutation.ActualizadoEn(); ok {
		_spec.SetField(usuario.FieldActualizadoEn, field.TypeTime, value)
		_node.ActualizadoEn = value
	}
	if value, ok := _c.mutation.Usuario(); ok {
		_spec.SetField(usuario.FieldUsuario, field.TypeString, value)
		_node.Usuario = value
	}
	if value, ok := _c.mutation.HashContrasena(); ok {
		_spec.SetField(usuario.FieldHashContrasena, field.TypeString, value)
		_node.HashContrasena = value
	}
	if value, ok := _c.mutation.Estado(); ok {
		_spec.SetField(usuario.FieldEstado, field.TypeEnum, value)
		_node.Estado = value
	}
	if value, ok := _c.mutation.UltimoAcceso(); ok {
		_spec.SetField(usuario.FieldUltimoAcceso, field.TypeTime, value)
		_node.UltimoAcceso = &value
	}
	if nodes := _c.mutation.EmpresasUsuarioIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usuario.EmpresasUsuarioTable,
			Columns: []string{usuario.EmpresasUsuarioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(empresausuario.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UsuarioCreateBulk is the builder for creating many Usuario entities in bulk.
type UsuarioCreateBulk struct {
	config
	err      error
	builders []*UsuarioCreate
}

// Save creates the Usuario entities in the database.
func (_c *UsuarioCreateBulk) Save(ctx context.Context) ([]*Usuario, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Usuario, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsuarioMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsuarioCreateBulk) SaveX(ctx context.Context) []*Usuario {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsuarioCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsuarioCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
