package di

import (
	"rentals-go/internal/controller"
	"rentals-go/internal/domain"
	"rentals-go/internal/repository"
	"rentals-go/internal/service"

	"github.com/google/wire"
)

var RepositorySet = wire.NewSet(
	repository.NewAdminRepo,
	wire.Bind(new(domain.AdminRepository), new(*repository.AdminRepoEnt)),
	repository.NewEmpresaRepo,
	wire.Bind(new(domain.EmpresaRepository), new(*repository.EmpresaRepoEnt)),
	repository.NewUsuarioRepo,
	wire.Bind(new(domain.UsuarioRepository), new(*repository.UsuarioRepoEnt)),
	repository.NewRolRepo,
	wire.Bind(new(domain.RolRepository), new(*repository.RolRepoEnt)),
	repository.NewMembresiaRepo,
	wire.Bind(new(domain.MembresiaRepository), new(*repository.MembresiaRepoEnt)),
	repository.NewGastoRepo,
	wire.Bind(new(domain.GastoRepository), new(*repository.GastoRepoEnt)),
	repository.NewClienteRepo,
	wire.Bind(new(domain.ClienteRepository), new(*repository.ClienteRepoEnt)),
	repository.NewInmuebleRepo,
	wire.Bind(new(domain.InmuebleRepository), new(*repository.InmuebleRepoEnt)),
	repository.NewAlquilerRepo,
	wire.Bind(new(domain.AlquilerRepository), new(*repository.AlquilerRepoEnt)),
	repository.NewPagoAlquilerRepo,
	wire.Bind(new(domain.PagoAlquilerRepository), new(*repository.PagoAlquilerRepoEnt)),
	repository.NewMovimientoCajaRepo,
	wire.Bind(new(domain.MovimientoCajaRepository), new(*repository.MovimientoCajaRepoEnt)),
	repository.NewTipoPagoRepo,
	wire.Bind(new(domain.TipoPagoRepository), new(*repository.TipoPagoRepoEnt)),
	repository.NewTipoIdentificacionRepo,
	wire.Bind(new(domain.TipoIdentificacionRepository), new(*repository.TipoIdentificacionRepoEnt)),
	repository.NewStaffRepo,
	wire.Bind(new(domain.StaffRepository), new(*repository.StaffRepoEnt)),
	repository.NewCargoRepo,
	wire.Bind(new(domain.CargoRepository), new(*repository.CargoRepoEnt)),
	repository.NewServicioMedicionRepo,
	wire.Bind(new(domain.ServicioMedicionRepository), new(*repository.ServicioMedicionRepoEnt)),
	repository.NewTicketRepo,
	wire.Bind(new(domain.TicketRepository), new(*repository.TicketRepoEnt)),
	repository.NewDashboardRepo,
	wire.Bind(new(domain.DashboardRepository), new(*repository.DashboardRepoEnt)),
	repository.NewHorarioRepo,
	wire.Bind(new(domain.HorarioRepository), new(*repository.HorarioRepoEnt)),
	repository.NewAsistenciaRepo,
	wire.Bind(new(domain.AsistenciaRepository), new(*repository.AsistenciaRepoEnt)),
	repository.NewPermisoRepo,
	wire.Bind(new(domain.PermisoRepository), new(*repository.PermisoRepoEnt)),
	repository.NewReporteRepo,
	wire.Bind(new(domain.ReporteRepository), new(*repository.ReporteRepoEnt)),
	repository.NewCitaRepo,
	wire.Bind(new(domain.CitaRepository), new(*repository.CitaRepoEnt)),
)

var ServiceSet = wire.NewSet(
	service.NewAdminService,
	service.NewMonedaService,
	service.NewUsuarioService,
	service.NewGastoService,
	service.NewClienteService,
	service.NewInmuebleService,
	service.NewAlquilerService,
	service.NewPagoAlquilerService,
	service.NewStaffService,
	service.NewCargoService,
	service.NewServicioMedicionService,
	service.NewTicketService,
	wire.Bind(new(domain.GastoService), new(*service.GastoService)),
	wire.Bind(new(domain.ClienteService), new(*service.ClienteService)),
	wire.Bind(new(domain.InmuebleService), new(*service.InmuebleService)),
	wire.Bind(new(domain.AlquilerService), new(*service.AlquilerService)),
	wire.Bind(new(domain.PagoAlquilerService), new(*service.PagoAlquilerService)),
	wire.Bind(new(domain.StaffService), new(*service.StaffService)),
	wire.Bind(new(domain.CargoService), new(*service.CargoService)),
	wire.Bind(new(domain.ServicioMedicionService), new(*service.ServicioMedicionService)),
	wire.Bind(new(domain.TicketService), new(*service.TicketService)),
	service.NewDashboardService,
	wire.Bind(new(domain.DashboardService), new(*service.DashboardService)),
	service.NewAsistenciaService,
	wire.Bind(new(domain.AsistenciaService), new(*service.AsistenciaService)),
	service.NewReporteService,
	wire.Bind(new(domain.ReporteService), new(*service.ReporteService)),
	service.NewCitaService,
	wire.Bind(new(domain.CitaService), new(*service.CitaService)),
	ProvideJWTSecret,
)

var ControllerSet = wire.NewSet(
	controller.NewAdminController,
	controller.NewMonedaController,
	controller.NewUsuarioController,
	controller.NewGastoController,
	controller.NewClienteController,
	controller.NewInmuebleController,
	controller.NewAlquilerController,
	controller.NewStaffController,
	controller.NewCargoController,
	controller.NewServicioMedicionController,
	controller.NewTicketController,
	controller.NewDashboardController,
	controller.NewAsistenciaController,
	controller.NewReporteController,
	controller.NewCitasController,
)
