// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"rentals-go/internal/controller"
	"rentals-go/internal/repository"
	"rentals-go/internal/service"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	client, err := ProvideEntClient(config)
	if err != nil {
		return nil, err
	}
	adminRepoEnt := repository.NewAdminRepo(client)
	empresaRepoEnt := repository.NewEmpresaRepo(client)
	usuarioRepoEnt := repository.NewUsuarioRepo(client)
	rolRepoEnt := repository.NewRolRepo(client)
	membresiaRepoEnt := repository.NewMembresiaRepo(client)
	v := ProvideJWTSecret(config)
	adminService := service.NewAdminService(adminRepoEnt, empresaRepoEnt, usuarioRepoEnt, rolRepoEnt, membresiaRepoEnt, v)
	adminController := controller.NewAdminController(adminService)
	monedaService := service.NewMonedaService()
	monedaController := controller.NewMonedaController(monedaService)
	usuarioService := service.NewUsuarioService(usuarioRepoEnt, v)
	usuarioController := controller.NewUsuarioController(usuarioService)
	gastoRepoEnt := repository.NewGastoRepo(client)
	movimientoCajaRepoEnt := repository.NewMovimientoCajaRepo(client)
	tipoPagoRepoEnt := repository.NewTipoPagoRepo(client)
	gastoService := service.NewGastoService(gastoRepoEnt, movimientoCajaRepoEnt, tipoPagoRepoEnt)
	gastoController := controller.NewGastoController(gastoService)
	clienteRepoEnt := repository.NewClienteRepo(client)
	tipoIdentificacionRepoEnt := repository.NewTipoIdentificacionRepo(client)
	clienteService := service.NewClienteService(clienteRepoEnt, tipoIdentificacionRepoEnt)
	clienteController := controller.NewClienteController(clienteService)
	inmuebleRepoEnt := repository.NewInmuebleRepo(client)
	inmuebleService := service.NewInmuebleService(inmuebleRepoEnt)
	inmuebleController := controller.NewInmuebleController(inmuebleService)
	alquilerRepoEnt := repository.NewAlquilerRepo(client)
	alquilerService := service.NewAlquilerService(alquilerRepoEnt)
	pagoAlquilerRepoEnt := repository.NewPagoAlquilerRepo(client)
	pagoAlquilerService := service.NewPagoAlquilerService(pagoAlquilerRepoEnt)
	alquilerController := controller.NewAlquilerController(alquilerService, pagoAlquilerService)
	app := &App{
		Config:       config,
		EntClient:    client,
		AdminCtrl:    adminController,
		MonedaCtrl:   monedaController,
		UsuarioCtrl:  usuarioController,
		GastoCtrl:    gastoController,
		ClienteCtrl:  clienteController,
		InmuebleCtrl: inmuebleController,
		AlquilerCtrl: alquilerController,
	}
	return app, nil
}
