// Code generated by ent, DO NOT EDIT.

package tipopago

import (
	"rentals-go/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldLTE(FieldID, id))
}

// Nombre applies equality check predicate on the "nombre" field. It's identical to NombreEQ.
func Nombre(v string) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldEQ(FieldNombre, v))
}

// NombreEQ applies the EQ predicate on the "nombre" field.
func NombreEQ(v string) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldEQ(FieldNombre, v))
}

// NombreNEQ applies the NEQ predicate on the "nombre" field.
func NombreNEQ(v string) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldNEQ(FieldNombre, v))
}

// NombreIn applies the In predicate on the "nombre" field.
func NombreIn(vs ...string) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldIn(FieldNombre, vs...))
}

// NombreNotIn applies the NotIn predicate on the "nombre" field.
func NombreNotIn(vs ...string) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldNotIn(FieldNombre, vs...))
}

// NombreGT applies the GT predicate on the "nombre" field.
func NombreGT(v string) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldGT(FieldNombre, v))
}

// NombreGTE applies the GTE predicate on the "nombre" field.
func NombreGTE(v string) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldGTE(FieldNombre, v))
}

// NombreLT applies the LT predicate on the "nombre" field.
func NombreLT(v string) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldLT(FieldNombre, v))
}

// NombreLTE applies the LTE predicate on the "nombre" field.
func NombreLTE(v string) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldLTE(FieldNombre, v))
}

// NombreContains applies the Contains predicate on the "nombre" field.
func NombreContains(v string) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldContains(FieldNombre, v))
}

// NombreHasPrefix applies the HasPrefix predicate on the "nombre" field.
func NombreHasPrefix(v string) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldHasPrefix(FieldNombre, v))
}

// NombreHasSuffix applies the HasSuffix predicate on the "nombre" field.
func NombreHasSuffix(v string) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldHasSuffix(FieldNombre, v))
}

// NombreEqualFold applies the EqualFold predicate on the "nombre" field.
func NombreEqualFold(v string) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldEqualFold(FieldNombre, v))
}

// NombreContainsFold applies the ContainsFold predicate on the "nombre" field.
func NombreContainsFold(v string) predicate.TipoPago {
	return predicate.TipoPago(sql.FieldContainsFold(FieldNombre, v))
}

// HasGastos applies the HasEdge predicate on the "gastos" edge.
func HasGastos() predicate.TipoPago {
	return predicate.TipoPago(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GastosTable, GastosColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGastosWith applies the HasEdge predicate on the "gastos" edge with a given conditions (other predicates).
func HasGastosWith(preds ...predicate.Gasto) predicate.TipoPago {
	return predicate.TipoPago(func(s *sql.Selector) {
		step := newGastosStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TipoPago) predicate.TipoPago {
	return predicate.TipoPago(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TipoPago) predicate.TipoPago {
	return predicate.TipoPago(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TipoPago) predicate.TipoPago {
	return predicate.TipoPago(sql.NotPredicates(p))
}
