// Code generated by ent, DO NOT EDIT.

package unidad

import (
	"rentals-go/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Unidad {
	return predicate.Unidad(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Unidad {
	return predicate.Unidad(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Unidad {
	return predicate.Unidad(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Unidad {
	return predicate.Unidad(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Unidad {
	return predicate.Unidad(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Unidad {
	return predicate.Unidad(sql.FieldLTE(FieldID, id))
}

// CreadoEn applies equality check predicate on the "creado_en" field. It's identical to CreadoEnEQ.
func CreadoEn(v time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldCreadoEn, v))
}

// ActualizadoEn applies equality check predicate on the "actualizado_en" field. It's identical to ActualizadoEnEQ.
func ActualizadoEn(v time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldActualizadoEn, v))
}

// PropiedadID applies equality check predicate on the "propiedad_id" field. It's identical to PropiedadIDEQ.
func PropiedadID(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldPropiedadID, v))
}

// Codigo applies equality check predicate on the "codigo" field. It's identical to CodigoEQ.
func Codigo(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldCodigo, v))
}

// Nombre applies equality check predicate on the "nombre" field. It's identical to NombreEQ.
func Nombre(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldNombre, v))
}

// NumeroPiso applies equality check predicate on the "numero_piso" field. It's identical to NumeroPisoEQ.
func NumeroPiso(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldNumeroPiso, v))
}

// Dormitorios applies equality check predicate on the "dormitorios" field. It's identical to DormitoriosEQ.
func Dormitorios(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldDormitorios, v))
}

// Banos applies equality check predicate on the "banos" field. It's identical to BanosEQ.
func Banos(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldBanos, v))
}

// AreaM2 applies equality check predicate on the "area_m2" field. It's identical to AreaM2EQ.
func AreaM2(v float64) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldAreaM2, v))
}

// Capacidad applies equality check predicate on the "capacidad" field. It's identical to CapacidadEQ.
func Capacidad(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldCapacidad, v))
}

// Moneda applies equality check predicate on the "moneda" field. It's identical to MonedaEQ.
func Moneda(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldMoneda, v))
}

// PrecioBase applies equality check predicate on the "precio_base" field. It's identical to PrecioBaseEQ.
func PrecioBase(v int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldPrecioBase, v))
}

// DepositoRequerido applies equality check predicate on the "deposito_requerido" field. It's identical to DepositoRequeridoEQ.
func DepositoRequerido(v int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldDepositoRequerido, v))
}

// IncluyeAgua applies equality check predicate on the "incluye_agua" field. It's identical to IncluyeAguaEQ.
func IncluyeAgua(v bool) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldIncluyeAgua, v))
}

// IncluyeLuz applies equality check predicate on the "incluye_luz" field. It's identical to IncluyeLuzEQ.
func IncluyeLuz(v bool) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldIncluyeLuz, v))
}

// IncluyeInternet applies equality check predicate on the "incluye_internet" field. It's identical to IncluyeInternetEQ.
func IncluyeInternet(v bool) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldIncluyeInternet, v))
}

// Notas applies equality check predicate on the "notas" field. It's identical to NotasEQ.
func Notas(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldNotas, v))
}

// CreadoEnEQ applies the EQ predicate on the "creado_en" field.
func CreadoEnEQ(v time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldCreadoEn, v))
}

// CreadoEnNEQ applies the NEQ predicate on the "creado_en" field.
func CreadoEnNEQ(v time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldCreadoEn, v))
}

// CreadoEnIn applies the In predicate on the "creado_en" field.
func CreadoEnIn(vs ...time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldIn(FieldCreadoEn, vs...))
}

// CreadoEnNotIn applies the NotIn predicate on the "creado_en" field.
func CreadoEnNotIn(vs ...time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldNotIn(FieldCreadoEn, vs...))
}

// CreadoEnGT applies the GT predicate on the "creado_en" field.
func CreadoEnGT(v time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldGT(FieldCreadoEn, v))
}

// CreadoEnGTE applies the GTE predicate on the "creado_en" field.
func CreadoEnGTE(v time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldGTE(FieldCreadoEn, v))
}

// CreadoEnLT applies the LT predicate on the "creado_en" field.
func CreadoEnLT(v time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldLT(FieldCreadoEn, v))
}

// CreadoEnLTE applies the LTE predicate on the "creado_en" field.
func CreadoEnLTE(v time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldLTE(FieldCreadoEn, v))
}

// ActualizadoEnEQ applies the EQ predicate on the "actualizado_en" field.
func ActualizadoEnEQ(v time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldActualizadoEn, v))
}

// ActualizadoEnNEQ applies the NEQ predicate on the "actualizado_en" field.
func ActualizadoEnNEQ(v time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldActualizadoEn, v))
}

// ActualizadoEnIn applies the In predicate on the "actualizado_en" field.
func ActualizadoEnIn(vs ...time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldIn(FieldActualizadoEn, vs...))
}

// ActualizadoEnNotIn applies the NotIn predicate on the "actualizado_en" field.
func ActualizadoEnNotIn(vs ...time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldNotIn(FieldActualizadoEn, vs...))
}

// ActualizadoEnGT applies the GT predicate on the "actualizado_en" field.
func ActualizadoEnGT(v time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldGT(FieldActualizadoEn, v))
}

// ActualizadoEnGTE applies the GTE predicate on the "actualizado_en" field.
func ActualizadoEnGTE(v time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldGTE(FieldActualizadoEn, v))
}

// ActualizadoEnLT applies the LT predicate on the "actualizado_en" field.
func ActualizadoEnLT(v time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldLT(FieldActualizadoEn, v))
}

// ActualizadoEnLTE applies the LTE predicate on the "actualizado_en" field.
func ActualizadoEnLTE(v time.Time) predicate.Unidad {
	return predicate.Unidad(sql.FieldLTE(FieldActualizadoEn, v))
}

// PropiedadIDEQ applies the EQ predicate on the "propiedad_id" field.
func PropiedadIDEQ(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldPropiedadID, v))
}

// PropiedadIDNEQ applies the NEQ predicate on the "propiedad_id" field.
func PropiedadIDNEQ(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldPropiedadID, v))
}

// PropiedadIDIn applies the In predicate on the "propiedad_id" field.
func PropiedadIDIn(vs ...int) predicate.Unidad {
	return predicate.Unidad(sql.FieldIn(FieldPropiedadID, vs...))
}

// PropiedadIDNotIn applies the NotIn predicate on the "propiedad_id" field.
func PropiedadIDNotIn(vs ...int) predicate.Unidad {
	return predicate.Unidad(sql.FieldNotIn(FieldPropiedadID, vs...))
}

// CodigoEQ applies the EQ predicate on the "codigo" field.
func CodigoEQ(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldCodigo, v))
}

// CodigoNEQ applies the NEQ predicate on the "codigo" field.
func CodigoNEQ(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldCodigo, v))
}

// CodigoIn applies the In predicate on the "codigo" field.
func CodigoIn(vs ...string) predicate.Unidad {
	return predicate.Unidad(sql.FieldIn(FieldCodigo, vs...))
}

// CodigoNotIn applies the NotIn predicate on the "codigo" field.
func CodigoNotIn(vs ...string) predicate.Unidad {
	return predicate.Unidad(sql.FieldNotIn(FieldCodigo, vs...))
}

// CodigoGT applies the GT predicate on the "codigo" field.
func CodigoGT(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldGT(FieldCodigo, v))
}

// CodigoGTE applies the GTE predicate on the "codigo" field.
func CodigoGTE(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldGTE(FieldCodigo, v))
}

// CodigoLT applies the LT predicate on the "codigo" field.
func CodigoLT(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldLT(FieldCodigo, v))
}

// CodigoLTE applies the LTE predicate on the "codigo" field.
func CodigoLTE(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldLTE(FieldCodigo, v))
}

// CodigoContains applies the Contains predicate on the "codigo" field.
func CodigoContains(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldContains(FieldCodigo, v))
}

// CodigoHasPrefix applies the HasPrefix predicate on the "codigo" field.
func CodigoHasPrefix(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldHasPrefix(FieldCodigo, v))
}

// CodigoHasSuffix applies the HasSuffix predicate on the "codigo" field.
func CodigoHasSuffix(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldHasSuffix(FieldCodigo, v))
}

// CodigoEqualFold applies the EqualFold predicate on the "codigo" field.
func CodigoEqualFold(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldEqualFold(FieldCodigo, v))
}

// CodigoContainsFold applies the ContainsFold predicate on the "codigo" field.
func CodigoContainsFold(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldContainsFold(FieldCodigo, v))
}

// NombreEQ applies the EQ predicate on the "nombre" field.
func NombreEQ(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldNombre, v))
}

// NombreNEQ applies the NEQ predicate on the "nombre" field.
func NombreNEQ(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldNombre, v))
}

// NombreIn applies the In predicate on the "nombre" field.
func NombreIn(vs ...string) predicate.Unidad {
	return predicate.Unidad(sql.FieldIn(FieldNombre, vs...))
}

// NombreNotIn applies the NotIn predicate on the "nombre" field.
func NombreNotIn(vs ...string) predicate.Unidad {
	return predicate.Unidad(sql.FieldNotIn(FieldNombre, vs...))
}

// NombreGT applies the GT predicate on the "nombre" field.
func NombreGT(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldGT(FieldNombre, v))
}

// NombreGTE applies the GTE predicate on the "nombre" field.
func NombreGTE(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldGTE(FieldNombre, v))
}

// NombreLT applies the LT predicate on the "nombre" field.
func NombreLT(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldLT(FieldNombre, v))
}

// NombreLTE applies the LTE predicate on the "nombre" field.
func NombreLTE(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldLTE(FieldNombre, v))
}

// NombreContains applies the Contains predicate on the "nombre" field.
func NombreContains(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldContains(FieldNombre, v))
}

// NombreHasPrefix applies the HasPrefix predicate on the "nombre" field.
func NombreHasPrefix(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldHasPrefix(FieldNombre, v))
}

// NombreHasSuffix applies the HasSuffix predicate on the "nombre" field.
func NombreHasSuffix(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldHasSuffix(FieldNombre, v))
}

// NombreIsNil applies the IsNil predicate on the "nombre" field.
func NombreIsNil() predicate.Unidad {
	return predicate.Unidad(sql.FieldIsNull(FieldNombre))
}

// NombreNotNil applies the NotNil predicate on the "nombre" field.
func NombreNotNil() predicate.Unidad {
	return predicate.Unidad(sql.FieldNotNull(FieldNombre))
}

// NombreEqualFold applies the EqualFold predicate on the "nombre" field.
func NombreEqualFold(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldEqualFold(FieldNombre, v))
}

// NombreContainsFold applies the ContainsFold predicate on the "nombre" field.
func NombreContainsFold(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldContainsFold(FieldNombre, v))
}

// TipoEQ applies the EQ predicate on the "tipo" field.
func TipoEQ(v Tipo) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldTipo, v))
}

// TipoNEQ applies the NEQ predicate on the "tipo" field.
func TipoNEQ(v Tipo) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldTipo, v))
}

// TipoIn applies the In predicate on the "tipo" field.
func TipoIn(vs ...Tipo) predicate.Unidad {
	return predicate.Unidad(sql.FieldIn(FieldTipo, vs...))
}

// TipoNotIn applies the NotIn predicate on the "tipo" field.
func TipoNotIn(vs ...Tipo) predicate.Unidad {
	return predicate.Unidad(sql.FieldNotIn(FieldTipo, vs...))
}

// NumeroPisoEQ applies the EQ predicate on the "numero_piso" field.
func NumeroPisoEQ(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldNumeroPiso, v))
}

// NumeroPisoNEQ applies the NEQ predicate on the "numero_piso" field.
func NumeroPisoNEQ(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldNumeroPiso, v))
}

// NumeroPisoIn applies the In predicate on the "numero_piso" field.
func NumeroPisoIn(vs ...int) predicate.Unidad {
	return predicate.Unidad(sql.FieldIn(FieldNumeroPiso, vs...))
}

// NumeroPisoNotIn applies the NotIn predicate on the "numero_piso" field.
func NumeroPisoNotIn(vs ...int) predicate.Unidad {
	return predicate.Unidad(sql.FieldNotIn(FieldNumeroPiso, vs...))
}

// NumeroPisoGT applies the GT predicate on the "numero_piso" field.
func NumeroPisoGT(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldGT(FieldNumeroPiso, v))
}

// NumeroPisoGTE applies the GTE predicate on the "numero_piso" field.
func NumeroPisoGTE(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldGTE(FieldNumeroPiso, v))
}

// NumeroPisoLT applies the LT predicate on the "numero_piso" field.
func NumeroPisoLT(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldLT(FieldNumeroPiso, v))
}

// NumeroPisoLTE applies the LTE predicate on the "numero_piso" field.
func NumeroPisoLTE(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldLTE(FieldNumeroPiso, v))
}

// NumeroPisoIsNil applies the IsNil predicate on the "numero_piso" field.
func NumeroPisoIsNil() predicate.Unidad {
	return predicate.Unidad(sql.FieldIsNull(FieldNumeroPiso))
}

// NumeroPisoNotNil applies the NotNil predicate on the "numero_piso" field.
func NumeroPisoNotNil() predicate.Unidad {
	return predicate.Unidad(sql.FieldNotNull(FieldNumeroPiso))
}

// DormitoriosEQ applies the EQ predicate on the "dormitorios" field.
func DormitoriosEQ(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldDormitorios, v))
}

// DormitoriosNEQ applies the NEQ predicate on the "dormitorios" field.
func DormitoriosNEQ(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldDormitorios, v))
}

// DormitoriosIn applies the In predicate on the "dormitorios" field.
func DormitoriosIn(vs ...int) predicate.Unidad {
	return predicate.Unidad(sql.FieldIn(FieldDormitorios, vs...))
}

// DormitoriosNotIn applies the NotIn predicate on the "dormitorios" field.
func DormitoriosNotIn(vs ...int) predicate.Unidad {
	return predicate.Unidad(sql.FieldNotIn(FieldDormitorios, vs...))
}

// DormitoriosGT applies the GT predicate on the "dormitorios" field.
func DormitoriosGT(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldGT(FieldDormitorios, v))
}

// DormitoriosGTE applies the GTE predicate on the "dormitorios" field.
func DormitoriosGTE(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldGTE(FieldDormitorios, v))
}

// DormitoriosLT applies the LT predicate on the "dormitorios" field.
func DormitoriosLT(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldLT(FieldDormitorios, v))
}

// DormitoriosLTE applies the LTE predicate on the "dormitorios" field.
func DormitoriosLTE(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldLTE(FieldDormitorios, v))
}

// BanosEQ applies the EQ predicate on the "banos" field.
func BanosEQ(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldBanos, v))
}

// BanosNEQ applies the NEQ predicate on the "banos" field.
func BanosNEQ(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldBanos, v))
}

// BanosIn applies the In predicate on the "banos" field.
func BanosIn(vs ...int) predicate.Unidad {
	return predicate.Unidad(sql.FieldIn(FieldBanos, vs...))
}

// BanosNotIn applies the NotIn predicate on the "banos" field.
func BanosNotIn(vs ...int) predicate.Unidad {
	return predicate.Unidad(sql.FieldNotIn(FieldBanos, vs...))
}

// BanosGT applies the GT predicate on the "banos" field.
func BanosGT(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldGT(FieldBanos, v))
}

// BanosGTE applies the GTE predicate on the "banos" field.
func BanosGTE(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldGTE(FieldBanos, v))
}

// BanosLT applies the LT predicate on the "banos" field.
func BanosLT(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldLT(FieldBanos, v))
}

// BanosLTE applies the LTE predicate on the "banos" field.
func BanosLTE(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldLTE(FieldBanos, v))
}

// AreaM2EQ applies the EQ predicate on the "area_m2" field.
func AreaM2EQ(v float64) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldAreaM2, v))
}

// AreaM2NEQ applies the NEQ predicate on the "area_m2" field.
func AreaM2NEQ(v float64) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldAreaM2, v))
}

// AreaM2In applies the In predicate on the "area_m2" field.
func AreaM2In(vs ...float64) predicate.Unidad {
	return predicate.Unidad(sql.FieldIn(FieldAreaM2, vs...))
}

// AreaM2NotIn applies the NotIn predicate on the "area_m2" field.
func AreaM2NotIn(vs ...float64) predicate.Unidad {
	return predicate.Unidad(sql.FieldNotIn(FieldAreaM2, vs...))
}

// AreaM2GT applies the GT predicate on the "area_m2" field.
func AreaM2GT(v float64) predicate.Unidad {
	return predicate.Unidad(sql.FieldGT(FieldAreaM2, v))
}

// AreaM2GTE applies the GTE predicate on the "area_m2" field.
func AreaM2GTE(v float64) predicate.Unidad {
	return predicate.Unidad(sql.FieldGTE(FieldAreaM2, v))
}

// AreaM2LT applies the LT predicate on the "area_m2" field.
func AreaM2LT(v float64) predicate.Unidad {
	return predicate.Unidad(sql.FieldLT(FieldAreaM2, v))
}

// AreaM2LTE applies the LTE predicate on the "area_m2" field.
func AreaM2LTE(v float64) predicate.Unidad {
	return predicate.Unidad(sql.FieldLTE(FieldAreaM2, v))
}

// AreaM2IsNil applies the IsNil predicate on the "area_m2" field.
func AreaM2IsNil() predicate.Unidad {
	return predicate.Unidad(sql.FieldIsNull(FieldAreaM2))
}

// AreaM2NotNil applies the NotNil predicate on the "area_m2" field.
func AreaM2NotNil() predicate.Unidad {
	return predicate.Unidad(sql.FieldNotNull(FieldAreaM2))
}

// CapacidadEQ applies the EQ predicate on the "capacidad" field.
func CapacidadEQ(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldCapacidad, v))
}

// CapacidadNEQ applies the NEQ predicate on the "capacidad" field.
func CapacidadNEQ(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldCapacidad, v))
}

// CapacidadIn applies the In predicate on the "capacidad" field.
func CapacidadIn(vs ...int) predicate.Unidad {
	return predicate.Unidad(sql.FieldIn(FieldCapacidad, vs...))
}

// CapacidadNotIn applies the NotIn predicate on the "capacidad" field.
func CapacidadNotIn(vs ...int) predicate.Unidad {
	return predicate.Unidad(sql.FieldNotIn(FieldCapacidad, vs...))
}

// CapacidadGT applies the GT predicate on the "capacidad" field.
func CapacidadGT(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldGT(FieldCapacidad, v))
}

// CapacidadGTE applies the GTE predicate on the "capacidad" field.
func CapacidadGTE(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldGTE(FieldCapacidad, v))
}

// CapacidadLT applies the LT predicate on the "capacidad" field.
func CapacidadLT(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldLT(FieldCapacidad, v))
}

// CapacidadLTE applies the LTE predicate on the "capacidad" field.
func CapacidadLTE(v int) predicate.Unidad {
	return predicate.Unidad(sql.FieldLTE(FieldCapacidad, v))
}

// MonedaEQ applies the EQ predicate on the "moneda" field.
func MonedaEQ(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldMoneda, v))
}

// MonedaNEQ applies the NEQ predicate on the "moneda" field.
func MonedaNEQ(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldMoneda, v))
}

// MonedaIn applies the In predicate on the "moneda" field.
func MonedaIn(vs ...string) predicate.Unidad {
	return predicate.Unidad(sql.FieldIn(FieldMoneda, vs...))
}

// MonedaNotIn applies the NotIn predicate on the "moneda" field.
func MonedaNotIn(vs ...string) predicate.Unidad {
	return predicate.Unidad(sql.FieldNotIn(FieldMoneda, vs...))
}

// MonedaGT applies the GT predicate on the "moneda" field.
func MonedaGT(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldGT(FieldMoneda, v))
}

// MonedaGTE applies the GTE predicate on the "moneda" field.
func MonedaGTE(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldGTE(FieldMoneda, v))
}

// MonedaLT applies the LT predicate on the "moneda" field.
func MonedaLT(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldLT(FieldMoneda, v))
}

// MonedaLTE applies the LTE predicate on the "moneda" field.
func MonedaLTE(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldLTE(FieldMoneda, v))
}

// MonedaContains applies the Contains predicate on the "moneda" field.
func MonedaContains(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldContains(FieldMoneda, v))
}

// MonedaHasPrefix applies the HasPrefix predicate on the "moneda" field.
func MonedaHasPrefix(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldHasPrefix(FieldMoneda, v))
}

// MonedaHasSuffix applies the HasSuffix predicate on the "moneda" field.
func MonedaHasSuffix(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldHasSuffix(FieldMoneda, v))
}

// MonedaEqualFold applies the EqualFold predicate on the "moneda" field.
func MonedaEqualFold(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldEqualFold(FieldMoneda, v))
}

// MonedaContainsFold applies the ContainsFold predicate on the "moneda" field.
func MonedaContainsFold(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldContainsFold(FieldMoneda, v))
}

// PrecioBaseEQ applies the EQ predicate on the "precio_base" field.
func PrecioBaseEQ(v int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldPrecioBase, v))
}

// PrecioBaseNEQ applies the NEQ predicate on the "precio_base" field.
func PrecioBaseNEQ(v int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldPrecioBase, v))
}

// PrecioBaseIn applies the In predicate on the "precio_base" field.
func PrecioBaseIn(vs ...int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldIn(FieldPrecioBase, vs...))
}

// PrecioBaseNotIn applies the NotIn predicate on the "precio_base" field.
func PrecioBaseNotIn(vs ...int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldNotIn(FieldPrecioBase, vs...))
}

// PrecioBaseGT applies the GT predicate on the "precio_base" field.
func PrecioBaseGT(v int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldGT(FieldPrecioBase, v))
}

// PrecioBaseGTE applies the GTE predicate on the "precio_base" field.
func PrecioBaseGTE(v int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldGTE(FieldPrecioBase, v))
}

// PrecioBaseLT applies the LT predicate on the "precio_base" field.
func PrecioBaseLT(v int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldLT(FieldPrecioBase, v))
}

// PrecioBaseLTE applies the LTE predicate on the "precio_base" field.
func PrecioBaseLTE(v int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldLTE(FieldPrecioBase, v))
}

// DepositoRequeridoEQ applies the EQ predicate on the "deposito_requerido" field.
func DepositoRequeridoEQ(v int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldDepositoRequerido, v))
}

// DepositoRequeridoNEQ applies the NEQ predicate on the "deposito_requerido" field.
func DepositoRequeridoNEQ(v int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldDepositoRequerido, v))
}

// DepositoRequeridoIn applies the In predicate on the "deposito_requerido" field.
func DepositoRequeridoIn(vs ...int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldIn(FieldDepositoRequerido, vs...))
}

// DepositoRequeridoNotIn applies the NotIn predicate on the "deposito_requerido" field.
func DepositoRequeridoNotIn(vs ...int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldNotIn(FieldDepositoRequerido, vs...))
}

// DepositoRequeridoGT applies the GT predicate on the "deposito_requerido" field.
func DepositoRequeridoGT(v int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldGT(FieldDepositoRequerido, v))
}

// DepositoRequeridoGTE applies the GTE predicate on the "deposito_requerido" field.
func DepositoRequeridoGTE(v int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldGTE(FieldDepositoRequerido, v))
}

// DepositoRequeridoLT applies the LT predicate on the "deposito_requerido" field.
func DepositoRequeridoLT(v int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldLT(FieldDepositoRequerido, v))
}

// DepositoRequeridoLTE applies the LTE predicate on the "deposito_requerido" field.
func DepositoRequeridoLTE(v int64) predicate.Unidad {
	return predicate.Unidad(sql.FieldLTE(FieldDepositoRequerido, v))
}

// IncluyeAguaEQ applies the EQ predicate on the "incluye_agua" field.
func IncluyeAguaEQ(v bool) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldIncluyeAgua, v))
}

// IncluyeAguaNEQ applies the NEQ predicate on the "incluye_agua" field.
func IncluyeAguaNEQ(v bool) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldIncluyeAgua, v))
}

// IncluyeLuzEQ applies the EQ predicate on the "incluye_luz" field.
func IncluyeLuzEQ(v bool) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldIncluyeLuz, v))
}

// IncluyeLuzNEQ applies the NEQ predicate on the "incluye_luz" field.
func IncluyeLuzNEQ(v bool) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldIncluyeLuz, v))
}

// IncluyeInternetEQ applies the EQ predicate on the "incluye_internet" field.
func IncluyeInternetEQ(v bool) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldIncluyeInternet, v))
}

// IncluyeInternetNEQ applies the NEQ predicate on the "incluye_internet" field.
func IncluyeInternetNEQ(v bool) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldIncluyeInternet, v))
}

// NotasEQ applies the EQ predicate on the "notas" field.
func NotasEQ(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldNotas, v))
}

// NotasNEQ applies the NEQ predicate on the "notas" field.
func NotasNEQ(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldNotas, v))
}

// NotasIn applies the In predicate on the "notas" field.
func NotasIn(vs ...string) predicate.Unidad {
	return predicate.Unidad(sql.FieldIn(FieldNotas, vs...))
}

// NotasNotIn applies the NotIn predicate on the "notas" field.
func NotasNotIn(vs ...string) predicate.Unidad {
	return predicate.Unidad(sql.FieldNotIn(FieldNotas, vs...))
}

// NotasGT applies the GT predicate on the "notas" field.
func NotasGT(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldGT(FieldNotas, v))
}

// NotasGTE applies the GTE predicate on the "notas" field.
func NotasGTE(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldGTE(FieldNotas, v))
}

// NotasLT applies the LT predicate on the "notas" field.
func NotasLT(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldLT(FieldNotas, v))
}

// NotasLTE applies the LTE predicate on the "notas" field.
func NotasLTE(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldLTE(FieldNotas, v))
}

// NotasContains applies the Contains predicate on the "notas" field.
func NotasContains(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldContains(FieldNotas, v))
}

// NotasHasPrefix applies the HasPrefix predicate on the "notas" field.
func NotasHasPrefix(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldHasPrefix(FieldNotas, v))
}

// NotasHasSuffix applies the HasSuffix predicate on the "notas" field.
func NotasHasSuffix(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldHasSuffix(FieldNotas, v))
}

// NotasIsNil applies the IsNil predicate on the "notas" field.
func NotasIsNil() predicate.Unidad {
	return predicate.Unidad(sql.FieldIsNull(FieldNotas))
}

// NotasNotNil applies the NotNil predicate on the "notas" field.
func NotasNotNil() predicate.Unidad {
	return predicate.Unidad(sql.FieldNotNull(FieldNotas))
}

// NotasEqualFold applies the EqualFold predicate on the "notas" field.
func NotasEqualFold(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldEqualFold(FieldNotas, v))
}

// NotasContainsFold applies the ContainsFold predicate on the "notas" field.
func NotasContainsFold(v string) predicate.Unidad {
	return predicate.Unidad(sql.FieldContainsFold(FieldNotas, v))
}

// EstadoEQ applies the EQ predicate on the "estado" field.
func EstadoEQ(v Estado) predicate.Unidad {
	return predicate.Unidad(sql.FieldEQ(FieldEstado, v))
}

// EstadoNEQ applies the NEQ predicate on the "estado" field.
func EstadoNEQ(v Estado) predicate.Unidad {
	return predicate.Unidad(sql.FieldNEQ(FieldEstado, v))
}

// EstadoIn applies the In predicate on the "estado" field.
func EstadoIn(vs ...Estado) predicate.Unidad {
	return predicate.Unidad(sql.FieldIn(FieldEstado, vs...))
}

// EstadoNotIn applies the NotIn predicate on the "estado" field.
func EstadoNotIn(vs ...Estado) predicate.Unidad {
	return predicate.Unidad(sql.FieldNotIn(FieldEstado, vs...))
}

// HasPropiedad applies the HasEdge predicate on the "propiedad" edge.
func HasPropiedad() predicate.Unidad {
	return predicate.Unidad(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PropiedadTable, PropiedadColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPropiedadWith applies the HasEdge predicate on the "propiedad" edge with a given conditions (other predicates).
func HasPropiedadWith(preds ...predicate.Propiedad) predicate.Unidad {
	return predicate.Unidad(func(s *sql.Selector) {
		step := newPropiedadStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasContratos applies the HasEdge predicate on the "contratos" edge.
func HasContratos() predicate.Unidad {
	return predicate.Unidad(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ContratosTable, ContratosColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContratosWith applies the HasEdge predicate on the "contratos" edge with a given conditions (other predicates).
func HasContratosWith(preds ...predicate.Contrato) predicate.Unidad {
	return predicate.Unidad(func(s *sql.Selector) {
		step := newContratosStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasServicioMediciones applies the HasEdge predicate on the "servicio_mediciones" edge.
func HasServicioMediciones() predicate.Unidad {
	return predicate.Unidad(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ServicioMedicionesTable, ServicioMedicionesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServicioMedicionesWith applies the HasEdge predicate on the "servicio_mediciones" edge with a given conditions (other predicates).
func HasServicioMedicionesWith(preds ...predicate.ServicioMedicion) predicate.Unidad {
	return predicate.Unidad(func(s *sql.Selector) {
		step := newServicioMedicionesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGastos applies the HasEdge predicate on the "gastos" edge.
func HasGastos() predicate.Unidad {
	return predicate.Unidad(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GastosTable, GastosColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGastosWith applies the HasEdge predicate on the "gastos" edge with a given conditions (other predicates).
func HasGastosWith(preds ...predicate.Gasto) predicate.Unidad {
	return predicate.Unidad(func(s *sql.Selector) {
		step := newGastosStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Unidad) predicate.Unidad {
	return predicate.Unidad(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Unidad) predicate.Unidad {
	return predicate.Unidad(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Unidad) predicate.Unidad {
	return predicate.Unidad(sql.NotPredicates(p))
}
