// Code generated by ent, DO NOT EDIT.

package serviciomedicion

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the serviciomedicion type in the database.
	Label = "servicio_medicion"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreadoEn holds the string denoting the creado_en field in the database.
	FieldCreadoEn = "creado_en"
	// FieldUnidadID holds the string denoting the unidad_id field in the database.
	FieldUnidadID = "unidad_id"
	// FieldContratoID holds the string denoting the contrato_id field in the database.
	FieldContratoID = "contrato_id"
	// FieldTipoServicio holds the string denoting the tipo_servicio field in the database.
	FieldTipoServicio = "tipo_servicio"
	// FieldFechaLectura holds the string denoting the fecha_lectura field in the database.
	FieldFechaLectura = "fecha_lectura"
	// FieldLecturaAnterior holds the string denoting the lectura_anterior field in the database.
	FieldLecturaAnterior = "lectura_anterior"
	// FieldLecturaActual holds the string denoting the lectura_actual field in the database.
	FieldLecturaActual = "lectura_actual"
	// FieldConsumo holds the string denoting the consumo field in the database.
	FieldConsumo = "consumo"
	// FieldPrecioUnitario holds the string denoting the precio_unitario field in the database.
	FieldPrecioUnitario = "precio_unitario"
	// FieldFactor holds the string denoting the factor field in the database.
	FieldFactor = "factor"
	// FieldCargoFijo holds the string denoting the cargo_fijo field in the database.
	FieldCargoFijo = "cargo_fijo"
	// FieldMonto holds the string denoting the monto field in the database.
	FieldMonto = "monto"
	// FieldProcesado holds the string denoting the procesado field in the database.
	FieldProcesado = "procesado"
	// EdgeUnidad holds the string denoting the unidad edge name in mutations.
	EdgeUnidad = "unidad"
	// EdgeContrato holds the string denoting the contrato edge name in mutations.
	EdgeContrato = "contrato"
	// EdgeCargo holds the string denoting the cargo edge name in mutations.
	EdgeCargo = "cargo"
	// Table holds the table name of the serviciomedicion in the database.
	Table = "servicio_mediciones"
	// UnidadTable is the table that holds the unidad relation/edge.
	UnidadTable = "servicio_mediciones"
	// UnidadInverseTable is the table name for the Unidad entity.
	// It exists in this package in order to avoid circular dependency with the "unidad" package.
	UnidadInverseTable = "unidades"
	// UnidadColumn is the table column denoting the unidad relation/edge.
	UnidadColumn = "unidad_id"
	// ContratoTable is the table that holds the contrato relation/edge.
	ContratoTable = "servicio_mediciones"
	// ContratoInverseTable is the table name for the Contrato entity.
	// It exists in this package in order to avoid circular dependency with the "contrato" package.
	ContratoInverseTable = "contratos"
	// ContratoColumn is the table column denoting the contrato relation/edge.
	ContratoColumn = "contrato_id"
	// CargoTable is the table that holds the cargo relation/edge.
	CargoTable = "cargos"
	// CargoInverseTable is the table name for the Cargo entity.
	// It exists in this package in order to avoid circular dependency with the "cargo" package.
	CargoInverseTable = "cargos"
	// CargoColumn is the table column denoting the cargo relation/edge.
	CargoColumn = "servicio_medicion_cargo"
)

// Columns holds all SQL columns for serviciomedicion fields.
var Columns = []string{
	FieldID,
	FieldCreadoEn,
	FieldUnidadID,
	FieldContratoID,
	FieldTipoServicio,
	FieldFechaLectura,
	FieldLecturaAnterior,
	FieldLecturaActual,
	FieldConsumo,
	FieldPrecioUnitario,
	FieldFactor,
	FieldCargoFijo,
	FieldMonto,
	FieldProcesado,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreadoEn holds the default value on creation for the "creado_en" field.
	DefaultCreadoEn func() time.Time
	// DefaultLecturaAnterior holds the default value on creation for the "lectura_anterior" field.
	DefaultLecturaAnterior float64
	// DefaultLecturaActual holds the default value on creation for the "lectura_actual" field.
	DefaultLecturaActual float64
	// DefaultConsumo holds the default value on creation for the "consumo" field.
	DefaultConsumo float64
	// DefaultPrecioUnitario holds the default value on creation for the "precio_unitario" field.
	DefaultPrecioUnitario float64
	// DefaultFactor holds the default value on creation for the "factor" field.
	DefaultFactor float64
	// DefaultCargoFijo holds the default value on creation for the "cargo_fijo" field.
	DefaultCargoFijo int64
	// DefaultMonto holds the default value on creation for the "monto" field.
	DefaultMonto int64
	// DefaultProcesado holds the default value on creation for the "procesado" field.
	DefaultProcesado bool
)

// TipoServicio defines the type for the "tipo_servicio" enum field.
type TipoServicio string

// TipoServicioAgua is the default value of the TipoServicio enum.
const DefaultTipoServicio = TipoServicioAgua

// TipoServicio values.
const (
	TipoServicioAgua     TipoServicio = "agua"
	TipoServicioLuz      TipoServicio = "luz"
	TipoServicioGas      TipoServicio = "gas"
	TipoServicioInternet TipoServicio = "internet"
	TipoServicioOtro     TipoServicio = "otro"
)

func (ts TipoServicio) String() string {
	return string(ts)
}

// TipoServicioValidator is a validator for the "tipo_servicio" field enum values. It is called by the builders before save.
func TipoServicioValidator(ts TipoServicio) error {
	switch ts {
	case TipoServicioAgua, TipoServicioLuz, TipoServicioGas, TipoServicioInternet, TipoServicioOtro:
		return nil
	default:
		return fmt.Errorf("serviciomedicion: invalid enum value for tipo_servicio field: %q", ts)
	}
}

// OrderOption defines the ordering options for the ServicioMedicion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreadoEn orders the results by the creado_en field.
func ByCreadoEn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreadoEn, opts...).ToFunc()
}

// ByUnidadID orders the results by the unidad_id field.
func ByUnidadID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnidadID, opts...).ToFunc()
}

// ByContratoID orders the results by the contrato_id field.
func ByContratoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContratoID, opts...).ToFunc()
}

// ByTipoServicio orders the results by the tipo_servicio field.
func ByTipoServicio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTipoServicio, opts...).ToFunc()
}

// ByFechaLectura orders the results by the fecha_lectura field.
func ByFechaLectura(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFechaLectura, opts...).ToFunc()
}

// ByLecturaAnterior orders the results by the lectura_anterior field.
func ByLecturaAnterior(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLecturaAnterior, opts...).ToFunc()
}

// ByLecturaActual orders the results by the lectura_actual field.
func ByLecturaActual(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLecturaActual, opts...).ToFunc()
}

// ByConsumo orders the results by the consumo field.
func ByConsumo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsumo, opts...).ToFunc()
}

// ByPrecioUnitario orders the results by the precio_unitario field.
func ByPrecioUnitario(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrecioUnitario, opts...).ToFunc()
}

// ByFactor orders the results by the factor field.
func ByFactor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFactor, opts...).ToFunc()
}

// ByCargoFijo orders the results by the cargo_fijo field.
func ByCargoFijo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCargoFijo, opts...).ToFunc()
}

// ByMonto orders the results by the monto field.
func ByMonto(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonto, opts...).ToFunc()
}

// ByProcesado orders the results by the procesado field.
func ByProcesado(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcesado, opts...).ToFunc()
}

// ByUnidadField orders the results by unidad field.
func ByUnidadField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUnidadStep(), sql.OrderByField(field, opts...))
	}
}

// ByContratoField orders the results by contrato field.
func ByContratoField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newContratoStep(), sql.OrderByField(field, opts...))
	}
}

// ByCargoField orders the results by cargo field.
func ByCargoField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCargoStep(), sql.OrderByField(field, opts...))
	}
}
func newUnidadStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UnidadInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UnidadTable, UnidadColumn),
	)
}
func newContratoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ContratoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ContratoTable, ContratoColumn),
	)
}
func newCargoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CargoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, CargoTable, CargoColumn),
	)
}
